### ISSUE TITLE
What is a different between day and days?

### ISSUE THREAD

**Issue by ozzyst** [go-co-op/gocron#125]
Hello!

What is a different between day and days, month and months, etc? For example, I want to start some function every the first day of every month. Should I use month or months?

I'm a little confused after checking the doc. Also I haven't tried the code yet.

**Comment by JohnRoesler** [comment]
They are the same! Just to make it read well if you want to do, every 1 month, vs every 2 months. 

these are valid but don’t read well:

Every(1).Months 
Every(2).Month

anything we can do to make it more clear in the docs?? Thanks!

**Comment by ozzyst** [comment]
I think the best way is write about are the same :D

Thank you!
