### ISSUE TITLE
[FEATURE] - Support running weekly schedule on multiple days of the week

### ISSUE THREAD

**Issue by JohnRoesler** [go-co-op/gocron#127]
### Is your feature request related to a problem? Please describe

This would be nice to allow a single job to be run multiple days of the week.

### Describe the solution you'd like

```golang
s.Every(1).Week().Monday().Thursday().Saturday().At("02:00").Do(func() {})
```

### Describe alternatives you've considered

```golang
s.Every(1).Week().Monday().At("02:00").Do(func() {})
s.Every(1).Week().Thursday().At("02:00").Do(func() {})
s.Every(1).Week().Saturday().At("02:00").Do(func() {})
```

### Additional context

Perhaps scheduledWeekday becomes a slice, and then we figure out the right way to support that in calculating the duration to next run

```golang
// Job struct stores the information necessary to run a Job
type Job struct {
	...
	scheduledWeekday  *time.Weekday // Specific day of the week to start on
	...
}
```

A custom struct with the 7 weekdays as bools might be a good option.

**Comment by joaolcaas** [comment]
Hi guys, how are you? Is this issue available still? I would like to crack it up

**Comment by JohnRoesler** [comment]
@joaolcaas yes, that would be wonderful!
