### ISSUE TITLE
[FEATURE] - Limit task by tag name

### ISSUE THREAD

**Issue by gopherine** [go-co-op/gocron#131]
### Is your feature request related to a problem? Please describe

I am not really sure if this is already present and i am missing something out in this library but it would be nice to have functionality to run only one job with assigned tag name. Right now this can be added N times. I have a requirement where i would like to add only one cron per tag

### Describe the solution you'd like

`s.Every(1).Second().Tag(tag).Lock(1).Do(task)`

**Comment by JohnRoesler** [comment]
Correct, currently tags are free form strings and multiple tags can be assigned to each job and the same tag(s) can be applied to many jobs.

Sounds like you’re interested in the ability to force tags to be unique across the scheduler?

**Comment by gopherine** [comment]
@JohnRoesler Thanks for the response, Rather than unique i would say , I would like to have more control over the tags. So right now the only power of tags as I see is i can remove it using tags. What I Want is to limit how many jobs we can run at a time with the tag.

So if I define lock(1) only one unique job should run for that tag, now this job can have multiple tags. But that tag with the log can only hold 1 job or specified number of jobs. If that makes sense.

Right now I do not know how to achieve this, other than storing and keeping track of the tag

**Comment by JohnRoesler** [comment]
Have you looked at the LimitRunsTo, Singleton or SetMaxConcurrentJob funcs? Are any of those helpful? 

Also, there isn’t a Lock func anymore...

I’m just trying to follow, so you want to limit multiple tagged jobs, like 3 jobs have this same tag and you want only one to run at a time? Or am I still missing it?

**Comment by gopherine** [comment]
I looked at LimitRunsTo, but that is for number of times a specific job should run
I tried singleton but i think it blocks job as a whole

```go
	if jobs[tag] == 0 || jobs[tag] == 2 {
		var t asset.T
		task := func() { reflect.Indirect(reflect.ValueOf(t).MethodByName(tag)).Call(nil) }
		s.Every("1s").Tag(tag).Do(task)
		s.StartAsync()
	}
	jobs[tag] = 1
	return
```

So like in the above code I am handling, the functionality I want using maps. I want the same thing here.
For example, if i pass a tag name A-> this should run only one job under that tag

Now in theory I can have multiple tags = A, B , C etc and there can be N jobs running under those tags which is right now the current behaviour also one job can be tagged with any number of tags

But if i specify a rule for a certain Tag lets say i only want one job to be running whenever any job is marked with this tag. Then this tag cannot execute any other extra job.But I can still create new jobs under different tag names.

This also makes removing jobs by tag name powerful as then i know for sure that there is no job running with Tag A when removed since this tag could hold only 1 job.

**Comment by JohnRoesler** [comment]
We could look at expanding the singleton mode to allow it to apply to job tags vs a single job.

**Comment by JohnRoesler** [comment]
I’m thinking this could be done on the scheduler with a map of tags to singleflights. Then when this mode is enabled, it would check the job tags and run the against the singleflight associated with the tag. That way, only one job could run at a time.

How would we handle if a job had two tags that each had a singleflight? Not allow it, pick the first?

**Comment by gopherine** [comment]
> I’m thinking this could be done on the scheduler with a map of tags to singleflights. Then when this mode is enabled, it would check the job tags and run the against the singleflight associated with the tag. That way, only one job could run at a time.
> 
> How would we handle if a job had two tags that each had a single flight? Not allow it, pick the first?

Originally, I did not like the idea of map because this can leave a huge memory footprint. If there would be a friendly way to handle it via struct or array but with array then timecomplexity would be a problem this would be more efficient i think though i am not sure how this is being handled in singleton mode.But lets say we have like 1 million tags in a map this would be memory intensive. Just an exception though i dont mind using map here but as long as this can be avoided it should be good.

if there are two tags and each have this single flight this should result in an error since the tags are already filled. We can think of it like an array of pre-defined size 1. anything extra cannot be accommodated this throws an error if someone tries to force push into it.

Another behaviour could be with a unique syntax would be to replace job with the last one. So like a stack FIFO first in first out with length of 1. if someone pushes a new job on already occupied tag this should replace the existing job. However, the default behaviour should be an error i feel and this should be given with some flag if needed be though i don't think so this is second behaviour is really needed as we already have remove by tag and anyone who wants to replace this with new job can just use that.

**Comment by JohnRoesler** [comment]
Are you wanting the unique behavior to block job creation or only job runs? If block creation then I think that becomes much simpler!

**Comment by gopherine** [comment]
> Are you wanting the unique behavior to block job creation or only job runs? If block creation then I think that becomes much simpler!

I don't really understand how is blockjob creation different from job runs. I just expect a behaviour where we could limit number of jobs for the given tag. now if blockjob creation does this job and is much simpler and performant, i would say go with it.

The idea being tag A should only be allowed to have 1 job  running under that tag and no more. and we can have millions of tags each running 1 unique job of their own or more if its not made singleton. like i described earlier in the code i would like to have similar behaviour to that code.

**Comment by JohnRoesler** [comment]
Ok, making tags unique across the scheduler shouldn’t be too bad. I’ll look to get that feature in before long.

**Comment by JohnRoesler** [comment]
This is implemented on master - please let me know if that meets your needs.
