### ISSUE TITLE
Investigate better options for parsing time in Scheduler At func

### ISSUE THREAD

**Issue by JohnRoesler** [go-co-op/gocron#14]
There should be a better way than taking in a string and parsing time

**Comment by arjunmahishi** [comment]
A better way to parse time would be to use the time layout `15:04:05` and/or `15:04` with `time.Parse()` and then 
```go
parsedTime , err := time.Parse("15:04:05", t)
return parsedTime.Hour(), parsedTime.Minute(), parsedTime.Second(), nil
```
We could use regex to check the format and pick the correct template.

**Comment by arjunmahishi** [comment]
I guess we can close this now.
