### ISSUE TITLE
[BUG] - Improve documentation of `.Month()` & related functions

### ISSUE THREAD

**Issue by frapa** [go-co-op/gocron#141]
### Describe the bug

The Documentation is vague on the use of `dayOfTheMonth` in `.Month()` and `.Months()`

### To Reproduce

https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.Months

### Version

github.com/go-co-op/gocron v1.0.0

### Expected behavior

From a comment in the source code, it seems that setting -1 will run on the last day of the previous month. That's useful but not clear from the docs. There also should be a note indicating if this day is starting from 0 or from 1. If it starts from 1, what happens if I set 0? Keeping in mind -1 seems to be the previous day of the month, 0 seems like undefined behavior.

### Additional context

The package is great, but a bit better doc of such edge cases would be extremely helpful.

**Comment by JohnRoesler** [comment]
Thanks for the issue! Definitely something we can get cleaned up so the docs are clear.

PRs are always welcome 😀 otherwise I’ll get to this before too long

**Comment by patrickascher** [comment]
Hello, just run into the same issue.
I thought with -1 it will be the last day of the month. but actually its not. 

If i run it today... (24.03.2021) the next runtime will be 24.04.2021.
`cron.Every(1).Month(-1).Name("XY").Tag("Import").Do(func(){})
`
I would expect, it would be the last day of the month.

Also if you add a more negative number like -10, it will still be the 24.04.2021
`cron.Every(1).Month(-1).Name("XY").Tag("Import").Do(func(){})
`

So i was wondering if there is an option to set the last day of every month with the actual code?

Btw: good work with the fork.

**Comment by Streppel** [comment]
@patrickascher interesting idea with that, it shouldn't be too hard to implement. Currently, I don't think there's a way to do that, but we'll take a look into that

**Comment by JohnRoesler** [comment]
closing this in favor of feature request issue
