### ISSUE TITLE
Feature: RunAll by tag

### ISSUE THREAD

**Issue by bobmcallan** [go-co-op/gocron#143]
At program startup, it is common to execute a job then enter the schedule. It would be great to execute a selection of jobs (by tag?) at startup.

`
	
    scheduler = gocron.NewScheduler(time.UTC)

    scheduler.Every(5).Minutes().SingletonMode().Do(p.users, false)
    scheduler.Every(30).Minutes().SingletonMode().Tag("startup").Do(p.users, true)

    scheduler.StartAsync()

    // Execute @ Startup
    for j := range scheduler.Tag("startup").Jobs(){
        j.RunOnce()
    }

    // or Execute @ Startup	
    scheduler.Tag("startup").RunAllWithDelay(10 * time.Second)
`

**Comment by JohnRoesler** [comment]
How about we had a function similar to run all with delay? `RunByTagWithDelay(time.Duration)`

**Comment by bobmcallan** [comment]
Yes, RunByTagWithDelay(time.Duration, tag) would work.

**Comment by JohnRoesler** [comment]
correct - by design all jobs are run once the scheduler is started.

**Comment by JohnRoesler** [comment]
@bobmcallan we added support in the form of two new methods:

- RunByTag
- RunByTagWithDelay

Checkout #149 for more details. We'll get it released soon.

**Comment by JohnRoesler** [comment]
This is out in release [v1.2.0](https://github.com/go-co-op/gocron/releases/tag/v1.2.0)
