### ISSUE TITLE
s.NotAtStart().Every(1).Hours || s.AwaitFirstSchedule()

### ISSUE THREAD

**Issue by bobmcallan** [go-co-op/gocron#152]
To configure an efficient service start-up, can you please either add a function to prevent the job from starting when the scheduler starts. Or, a global setting to not start all jobs when the scheduler starts.

`
s.NotAtStart().Every("5m").Do(func(){ ... })

or 

s.AwaitFirstSchedule()

`
Thanks,
Bob

**Comment by JohnRoesler** [comment]
Hello @bobmcallan 👋 

You could currently accomplish this with the [`StartAt()`](https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.StartAt) method, for example:

```
s := gocron.NewScheduler(time.UTC)	
fiveMinute := time.Minute * 5
s.Every(fiveMinute).StartAt(time.Now().Add(fiveMinute)).Do(func(){ log.Println("hello") })
```

I could see value in the global option you suggest to allow defaulting the scheduler to start the jobs only on their first interval. Thanks for bringing this up.

**Comment by JohnRoesler** [comment]
I have a PR coming soon for this feature

**Comment by JohnRoesler** [comment]
This is in latest release
