### ISSUE TITLE
Update() won't work for singleton mode jobs

### ISSUE THREAD

**Issue by zliu74** [go-co-op/gocron#157]
When a job is running in singleton mode, if you call Update(), the job will never run again.

**Comment by JohnRoesler** [comment]
@zliu74 thanks for reporting this! It's an issue with context cancellation. I've got a PR up to fix it 👍

**Comment by JohnRoesler** [comment]
[v1.4.0](https://github.com/go-co-op/gocron/releases/tag/v1.4.0) has this fix in it!
