### ISSUE TITLE
[BUG] - Weekly schedule > 1 week waits until the next week to start

### ISSUE THREAD

**Issue by JohnRoesler** [go-co-op/gocron#165]
### Describe the bug

discovered: https://github.com/go-co-op/gocron/pull/164#issuecomment-827649958

> the schedule starts the next week when the interval is 2. Then it back to the week jump

### To Reproduce

1.  `s.Every(2).Weeks().Friday()`

### Version

v1.5.0

### Expected behavior

the schedule should start at the next available opportunity to run rather than waiting a week

**Comment by joaolcaas** [comment]
It would be awful if the `calculateTotalDaysDifference` also checks if the job runCount is less than scheduledWeekday length?
