### ISSUE TITLE
README: Unable to figure out that Scheduler needs to be started. 

### ISSUE THREAD

**Issue by pranav292gpt** [go-co-op/gocron#169]
The current README gives examples to initialize a new shceduler and schedule simple tasks at various intervals. Going by the README, it is unclear that a scheduler needs to be started either in Async or Blocking fashion. It would be better to provide a full example of running a scheduler to perform simple tasks in the README as well. 

(I personally had to look up a third party article of sorts to figure out what i'm doing wrong.)

**Comment by JohnRoesler** [comment]
Good call
