### ISSUE TITLE
[BUG] - Out of sync, multiple executions of same task

### ISSUE THREAD

**Issue by alexandre-dias-cj** [go-co-op/gocron#174]
When using a 30s interval scheduler, after a few hours it runs multiple times the same task, per second

Example snippet 

```
var partialUpdatesTag = []string{"partial"}
var partialIndexer *gocron.Scheduler

func indexSomeData(){
	log.Println("Indexing data...")
	time.Sleep(1 * time.Second) 
}

func runPartialReindex() {
	log.Println("Runing partial...")
	stopPartial()
	indexSomeData()//dummy function won't take more than 200ms to complete
	startPartial()
}

func schedulePartialReindex() {
	log.Println("Partial reindex scheduler running each 30 seconds")
	partialIndexer = gocron.NewScheduler(time.Local)
	partialIndexer.Every(30 * time.Second).Tag(partialUpdatesTag...).SingletonMode().Do(runPartialReindex)
	partialIndexer.StartAsync()
}

func startPartial() {
	if partialIndexer == nil {
		partialIndexer = gocron.NewScheduler(time.Local)
	}
	if !partialIndexer.IsRunning() {
		partialIndexer.Clear() //make sure the old scheduler is cleared and no settings are kept
		for _, tag := range partialUpdatesTag {
			partialIndexer.RemoveByTag(tag)
		}
		partialIndexer = gocron.NewScheduler(time.Local)
		partialIndexer.Every(30 * time.Second).Tag(partialUpdatesTag...).SingletonMode().Do(runPartialReindex)
		time.Sleep(30 * time.Second) //we want to delay 30s start
		partialIndexer.StartAsync()
	}
}
func stopPartial() {
	if partialIndexer == nil {
		partialIndexer = gocron.NewScheduler(time.Local)
	}
	if partialIndexer.IsRunning() {
		partialIndexer.Stop()
		partialIndexer.WaitForSchedule().Stop() //make sure no runing tasks
	}
}
```

It wasn't expected that the runPartialReindex function was run more than once per 30s interval
I did try with partialIndexer.Every(30).Second() and partialIndexer.Every(30).Seconds() but the described problem is even worse
Not sure if it matters but I'm using go mod.

**Comment by Streppel** [comment]
Thanks for the detailed report, @alexandre-dias-cj! We will take a look at it!

**Comment by JohnRoesler** [comment]
@alexandre-dias-cj how are you running this? local machine, docker, etc.

**Comment by alexandre-dias-cj** [comment]
Docker, forgot to mention it

**Comment by alexandre-dias-cj** [comment]
Sure, we actually had 3 schedulers running, there are 2 different functions which interact with one single data repository. 
That repository is incremented or decremented using one 30 scheduler but 24h on 24h we're doing a full-rebuild of that data and we don't want the partial indexer running for obvious reasons.

We did actually ended up rebuilding our service to get rid of the problem.
