### ISSUE TITLE
[BUG] - RemoveByTag removes jobs containing substring of a tag

### ISSUE THREAD

**Issue by skinnaj** [go-co-op/gocron#184]
### Describe the bug

When you have multiple jobs, where each has a tag containing a number for example:

First jobs has the tag: 1
Second job has the tag: 11
Third job has the tag: 21

When using `RemoveByTag("1")` its removing all three jobs because its finding jobs by substring:

findJobsByTag:
`strings.Contains(strings.Join(job.Tags(), " "), tag)`

### Expected behavior

I expect only the first job to be removed.
But I'm not sure if the current behaviour is expected.

### Additional context

A solution would be something like this to find the jobs:

`Jobs:
	for _, job := range s.Jobs() {
		tags := job.Tags()
		for _, t := range tags {
			if t == tag {
				jobs = append(jobs, job)
				continue Jobs
			}
		}
	}`

**Comment by JohnRoesler** [comment]
It should not remove tags by substring IMO, but only exact matches. Thanks for opening this issue
