### ISSUE TITLE
Tests are deterministic

### ISSUE THREAD

**Issue by Streppel** [go-co-op/gocron#19]
[copy/paste from here](https://github.com/jasonlvhit/gocron/issues/88)

Current implementation depends too much on using time manipulation and because of that some tests take a long time to run (testTaskAt is one example, as it depends on the system changing minute, even though I believe we could fix this by testing it differently. Another example is the recent locking implementation).

This also causes some weird bugs that happen only at certain times (I've seen cases where `time.Now().Minute() + 1` was used to compare times, causing failures if you ran the test suite anytime at `HH:59`

We should find a way to end this by wrapping the system clock and thus being able to mock and control it.

[Further reading](https://martinfowler.com/articles/nonDeterminism.html)

**Comment by Streppel** [comment]
We already have our interface working so now we only need to update the tests

**Comment by JohnRoesler** [comment]
The problematic time related tests are fixed using the mock time.

I think it would be interesting to see about mocking the time after func so we could run daily or hourly tests in seconds.

**Comment by Streppel** [comment]
After that I believe we'll be done with this issue. I'll take a look into it!

**Comment by JohnRoesler** [comment]
I think this is reasonably complete now that we have the ability to set the current time with the fake time.
