### ISSUE TITLE
"Delayed" scheduling vs "Every" scheduling

### ISSUE THREAD

**Issue by aljumaro** [go-co-op/gocron#209]
Hi,

We have a scheduled task that should run as frequently as possible. Currently our scheduling configuration is:

```go
s.Every(60).Seconds().Do(func(){ ... })
```

The problem we are facing is that we don't actually know if the previous task has already finished when the next execution starts. Every cycle the task has an unknown number of subtask to perform.

The question we have is if there is a way of defining a delayed scheduling between runs. Something like:

```go
s.Delay(15).Seconds().Do(func(){ ... })
```
This code should start the job immediately or at a defined time and from that moment execute every 15 seconds after the previous execution ended.

Thanks.

**Comment by JohnRoesler** [comment]
There are two options we support today along these lines.

Singleton mode, which will allow only a single instance of the job to run at a time, and it will backup the jobs and continue to run them when the previous one stops. You can set this at the individual job level or the global scheduler level:

- Job level: https://pkg.go.dev/github.com/go-co-op/gocron#Job.SingletonMode
- Scheduler (all jobs): https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.SingletonMode

The other option is using the scheduler's limit to concurrent jobs using the wait mode

- https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.SetMaxConcurrentJobs
- https://pkg.go.dev/github.com/go-co-op/gocron#pkg-constants

Will one of those options work for what you're trying to achieve?

**Comment by aljumaro** [comment]
I think singleton mode will work for us.

Thanks.
