### ISSUE TITLE
[BUG] - Job deletion and addition fails when the job was started with LimitRunsTo(1).

### ISSUE THREAD

**Issue by indranil-elisity** [go-co-op/gocron#210]
### Describe the bug

I am adding a job with tag 'oneTimeJob' and using option LimitRunsTo(1). The package documentation says that the job will run only once but will stay on scheduler. However, once the job has run I can neither delete the job nor I can add a new job with same tag. Please see the code below.

### To Reproduce

```
package main

import (
        "bufio"
        "fmt"
        "os"
        "time"

        "github.com/go-co-op/gocron"
)

var s1 *gocron.Scheduler

func taskWithParams(a int, b string, isMono bool) {
    fmt.Println(a, b)
    t := time.Now()
    fmt.Printf("Cron taskWithParams tag %s ran at %s\n", b, t.Local())
    if isMono == true {
        fmt.Println("This is an one time job")
    }
}

func main() {
    t := time.Now()
    fmt.Printf("Go launched at %s\n", t.Local())

    // defines a new scheduler that schedules and runs jobs
    s1 = gocron.NewScheduler(time.Local)
    s1.TagsUnique()
    s1.StartAsync()

    scanner := bufio.NewScanner(os.Stdin)

    for {
        fmt.Print("Enter add for adding job, rem for removing job, run for running a job: ")
        var option string
        var cronString string
        var tag        string
        scanner.Scan()
        option = scanner.Text()
        switch option {
        case "add":
                fmt.Print("Enter crontab: ")
                scanner.Scan()
                cronString = scanner.Text()
                fmt.Print("Enter tag: ")
                scanner.Scan()
                tag = scanner.Text()
                job, err := s1.Cron(cronString).Tag(tag).LimitRunsTo(1).Do(taskWithParams, 1, tag, true)
                if err != nil {
                    fmt.Println(err)
                    break
                }
                t = time.Now()
                fmt.Printf("Cron job with tag %s added at %s\n", job.Tags(), t.Local())
        case "rem":
                fmt.Print("Enter tag to delete: ")
                scanner.Scan()
                tag = scanner.Text()
                err := s1.RemoveByTag(tag)
                if err != nil {
                    fmt.Println(err)
                    break
                }
                fmt.Println("Remaining number of jobs ", s1.Len())
        case "run":
                fmt.Print("Enter tag to run:" )
                scanner.Scan()
                tag = scanner.Text()
                s1.RunByTag(tag)
        default:
                fmt.Print("invalid option chosen \n")
        }
    }
    s1.Clear()
    s1.Stop()
}

```
$ go run gocronWithIo.go
Go launched at 2021-08-12 00:53:43.0323366 +0530 IST
Enter add for adding job, rem for removing job, run for running a job: add
Enter crontab: 58 00 * * *
Enter tag: oneTimeJob
Cron job with tag [oneTimeJob] added at 2021-08-12 00:57:18.2042977 +0530 IST
Enter add for adding job, rem for removing job, run for running a job: 1 oneTimeJob
Cron taskWithParams tag oneTimeJob ran at 2021-08-12 00:58:00.0074596 +0530 IST
This is an one time job
rem
Enter tag to delete: oneTimeJob
no jobs found with given tag >>>>> I can't remove the job
Enter add for adding job, rem for removing job, run for running a job: add
Enter crontab: 00 10 * * *
Enter tag: oneTimeJob
a non-unique tag was set on the job: oneTimeJob >>>>> I can't add the job either.

### Version

gocron v1.6.0

### Expected behavior

The document says that after run limit is reached the job stays on the scheduler. However I have ended up in a situation that I neither delete the job not add the job with same tag. Please note that I have configured the scheduler with TagsUnique().

**Comment by JohnRoesler** [comment]
@indranil-elisity looks to be a two part problem! 

1. The documentation on `LimitRunsTo` was incorrect. The job is removed when it reaches its limit.
2. The remove functions have a bug where the unique tags set at the scheduler are only removed when using `RemoveByTag` which isn't used by the removal that occurs when the limit runs to is reached. I'll open a PR to fix that. 

Thanks for reporting!
