### ISSUE TITLE
Feature request: Store job/schedule data

### ISSUE THREAD

**Issue by cybervagabond** [go-co-op/gocron#22]
Thanks for awesome library that really helps :)

Maybe it will be good idea.
In some cases people neen to run task only once.
Yes i can run task and then remove.

And also. What will happend if there are 30 tasks in scheduler and app crashed. After restart we will lose all tasks.

If it will be good idea, can try to do this

**Comment by JohnRoesler** [comment]
The run once has been asked about before. It is something we could certainly add support for - but have not prioritized it.

Regarding storing tasks - yes it's an idea worth exploring. If we were going to do it, I'd like to have done in an abstract enough way that we're not forcing users to a specific data store but allow them to implement an interface e.g. that they could then put any data store underneath.

**Comment by Streppel** [comment]
Hi @cybervagabond, thanks for your contribution. 

Storing tasks seems like an idea worth exploring indeed. Is there any real use case for this? I can't think of anything right now... What would you store, the function being executed itself? It'd only make sense if the function body in question were to be declared on the fly using code injection.

**Comment by cybervagabond** [comment]
@Streppel 

Basic use cases is mircoservices that integrates with this awesome library.
My use case is a microservice for making scheduling publications.
Users create jobs via rest api.  
`curl -X POST /api/publications/schedule`
For example: At 11 April 08:00 am need to publish text from user in blog.

But critical situation:
What will happen if service will go down. And after restart jobs array will be empty, so publications will not be posted


as @JohnRoesler mentioned above. There are way to create interface where users can plug any database. Will it be good idea? Because there are library https://github.com/rakanalh/scheduler where implemeted interface where you can plug db. But it works very bad.
What case will be better for storing jobs.
noSQL, SQL, or storing bytes in Redis?

**Comment by Streppel** [comment]
Hm, I see... Maybe we could work on something aiming for a plugin-like approach to executing code before or after something happens to the scheduler, going beyond databases. We'll try to expand this idea. Any contributions are more than welcome in the meantime

**Comment by JohnRoesler** [comment]
@cybervagabond I am splitting these issues up - opened one here for run once. If you would like to work on that code - we'd welcome the contribution! https://github.com/go-co-op/gocron/issues/24

**Comment by SaurusXI** [comment]
@Streppel @JohnRoesler any updates on the store job feature?
I'm writing an application daemon where a scheduler executes a fixed task. This means the scheduling information would be lost every time the user reboots. For the present version, I imagine serializing the scheduler and deserializing on reboot (a little hackish) might do it for me?

**Comment by Streppel** [comment]
Hi @SaurusXI! Just to keep you informed, there's no one working on this feature at the moment that we are currently trying to focus on delivering a stable version one before trying to add new features like this. 

Just to have a better understanding, what kind of schedule information do you need to be saved? ￼￼

Loading these preconditions from a persisted file might do it depending on your case.

**Comment by SaurusXI** [comment]
Hey @Streppel! I need to run an external script periodically, but the interval at which this script is run is decided by the user and can be changed at any time. These specifications are then managed by a daemon, and the information is stored in a persisted file.
I want to plug the scheduler in the daemon application. I imagine if I just use the scheduler normally, the time offset since the previous boot will be lost on shut down (since the scheduler object won't persist). So would the serialization/deserialization approach help?
I'm aware that I could just write a script to schedule a cron job in the system, but handling this natively in my go app would be simpler.

**Comment by Streppel** [comment]
@SaurusXI I see! That's interesting. We have a feature on the roadmap to be implemented to change job's the scheduling pattern during runtime, so I believe that this feature, alongside with persisting your configurations anyway you want to, would be exactly what you need. Meanwhile, you can stop the current scheduler and start a new one or remove the given job and add this new one with the new configuration. What do you think?

**Comment by SaurusXI** [comment]
Right, that feature would be perfect! 
If I try the alternative approach however, wouldn't I lose out on the time offset every time the user reboots? 
Say that the user has an hour long session before they shut down. The scheduler registers that an hour has passed. However when the system shuts down, this object is lost. So when the user starts a new session, even though the configuration is imported, the time offset would be lost right? Or am I missing something?

**Comment by JohnRoesler** [comment]
@SaurusXI I am wondering, could you store the time of the next run before the session is shut down? https://pkg.go.dev/github.com/go-co-op/gocron#Job.ScheduledTime

**Comment by SaurusXI** [comment]
Yes, that would work. Alternatively, what if I serialise the scheduler object instance and stored that? Then I can deserialise the object when daemon starts up, and I shouldn't lose time offset or scheduling information right? So then I wouldn't have to set up a new job according to configs, I'd be directly importing what I've set previously?

**Comment by JohnRoesler** [comment]
That sounds reasonable

**Comment by JohnRoesler** [comment]
Closing as it appears we have some solutions based on the discussion. Please re-open if there is still something lacking in gocron!

**Comment by kushalhalder** [comment]
Hi, I am afraid, I am opening this thread again because I feel no one could explain the reason for the requirement of a data store. 
Right now, How I see it, we are saving the tickers or cron statements in the memory. What happens when the server shuts down, we will loose all the schedules. The storage is needed to resume the state of the machine with all the pending jobs. 

I hope this explains the requirement for a storage layer.
