### ISSUE TITLE
[FEATURE] - Is there a way to tell if any job is actively running?

### ISSUE THREAD

**Issue by scottadamsmith** [go-co-op/gocron#225]
### Is your feature request related to a problem? Please describe

I want to see if I can wait for any in-progress jobs to complete when detecting a shutdown from the OS. I have been digging through the scheduler and job implementations and haven't seen any way to tell if a Job is actively running.

### Describe the solution you'd like

Some flag or really any mechanism to tell if a job is actively running.

### Describe alternatives you've considered

N/A

### Additional context

If you think there is indeed already an approach to doing this, can you point me in the right direction?

**Comment by JohnRoesler** [comment]
Hey @scottadamsmith thanks for opening this request. Right now the only way you could tell would be by having something inside your job function that reports it’s state.

However, I think we could add something around the function invocation by our executor to set a flag or something that notes the job as actively running.

**Comment by JohnRoesler** [comment]
It might be slightly tricky as the executor doesn’t receive any job details but only the function to run.

**Comment by scottadamsmith** [comment]
I actually came to that same conclusion. I looked into your code to see how your executor works and found the usage of WaitGroup to be a good solution. I am working on a function that "wraps" a job function with another function that calls the job function and registers the call the WaitGroup. This allows me to be able to wait for all jobs to complete.

The only thing I haven't done yet is ensure that another job won't get started while I am waiting. My thoughts are that I could use the scheduler's Stop method first to ensure no new jobs are started and then wait for the WaitGroup to complete. Does this sound correct? The scheduler Stop method won't have any impact on already running jobs, right?

**Comment by JohnRoesler** [comment]
Yeah I think a wait group could work. The scheduler stop wont stop in flight jobs but it will stop any that are scheduled and not yet run. I’m going to be afk for a week here but I’d be happy to hack on this when I’m back or review something if you decide to work on it!

Nice my fellow Minnesoten - let’s connect on slack (link in our repo) or LinkedIn (on my git profile)

**Comment by JohnRoesler** [comment]
I tried a couple different ways of doing this with wait groups and channels, but kept running to into issues with race conditions. So, I went with an implementation using atomic ints. Take a look and let me know what you think! https://github.com/go-co-op/gocron/pull/233

**Comment by scottadamsmith** [comment]
Thanks! I glanced at it briefly on my phone, but plan to look at it more closely on Monday. I can also share what I ended up doing on my end outside of the library itself. It allows me to see if "any" job is running, as opposed to checking if a specific job is running like your change introduces. With my approach, I know nothing about the job that is running, but rather that at least one job is running.

**Comment by Streppel** [comment]
@scottadamsmith even though we have an open PR that adds an IsRunning functionality, could you please check if [this](https://github.com/go-co-op/gocron/issues/237) solves your issue?

**Comment by scottadamsmith** [comment]
Yeah I think it would eliminate the need for some of my code. I'd be using the proposed "job.IsRunning" feature from the PR to do essentially what this new Stop implementation is doing. 

You'll see in my code, I have a "maximum timeout" that we would wait for in-progress jobs to complete. My line of thinking is - what if someone introduced a job that was unreasonably long or hung? With the bug fix you introduced here, do you know how it would handle that situation? A quick glance led me to believe it will wait indefinitely. 

Here is my abstraction of the scheduler that provides a similar feature along with some other things I wanted in place. Disclaimer - I am relatively new to Golang, so if I am doing anything egregious or naive, I welcome any feedback. Also, I borrowed some the techniques for validating the function and params from this library 😅 

```
package scheduler

import (
	"errors"
	"fmt"
	"os"
	"os/signal"
	"reflect"
	"sync"
	"syscall"
	"time"

	"github.com/go-co-op/gocron"
)

// Scheduler is a wrapper around gocron.Scheduler that provides detailed logging, error handling, and resiliency
type Scheduler struct {
	logger        Logger
	waitGroup     sync.WaitGroup
	cronScheduler *gocron.Scheduler
	done          chan bool
}

type Logger interface {
	LogInfo(message string, data map[string]interface{})
	LogError(message string, data map[string]interface{})
}

type JobFunctionResult struct {
	Success bool
	Message string
	Data    map[string]interface{}
}

// NewScheduler creates an instance of Scheduler
func NewScheduler(logger Logger, schedule func(scheduler *Scheduler, cronScheduler *gocron.Scheduler)) *Scheduler {
	var wg sync.WaitGroup
	cronScheduler := gocron.NewScheduler(time.UTC)

	sigs := make(chan os.Signal, 1)
	done := make(chan bool, 1)

	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)

	newScheduler := &Scheduler{logger, wg, cronScheduler, done}

	go func() {
		sig := <-sigs
		newScheduler.logInfo("Scheduler", fmt.Sprintf("detected %s signal", sig), nil)
		done <- true
	}()

	schedule(newScheduler, cronScheduler)

	return newScheduler
}

var (
	errNotAFunction      = errors.New("only functions can be scheduled")
	errWrongParams       = errors.New("wrong list of params")
	errWrongOutputParams = errors.New("job functions must return (jobFunctionResult, error)")
)

var scheduledJobLogType = "ScheduledJob"

func (scheduler *Scheduler) logInfo(jobName string, message string, data *map[string]interface{}) {
	message = fmt.Sprintf("Scheduled Job Info (%s) - %s", jobName, message)

	var enrichedData map[string]interface{} = map[string]interface{}{}
	if data != nil {
		enrichedData = *data
	}

	enrichedData["logType"] = scheduledJobLogType
	enrichedData["jobName"] = jobName

	scheduler.logger.LogInfo(message, enrichedData)
}

func (scheduler *Scheduler) logError(jobName string, message string, data *map[string]interface{}) {
	message = fmt.Sprintf("Scheduled Job Error (%s) - %s", jobName, message)

	var enrichedData map[string]interface{} = map[string]interface{}{}
	if data != nil {
		enrichedData = *data
	}

	enrichedData["logType"] = scheduledJobLogType
	enrichedData["jobName"] = jobName

	scheduler.logger.LogError(message, enrichedData)
}

func (scheduler *Scheduler) ScheduleJob(jobName string, cronScheduler *gocron.Scheduler, jobFunc interface{}, params ...interface{}) {
	typ := reflect.TypeOf(jobFunc)
	if typ.Kind() != reflect.Func {
		scheduler.logError(jobName, errNotAFunction.Error(), nil)
		return
	}

	f := reflect.ValueOf(jobFunc)
	if len(params) != f.Type().NumIn() {
		scheduler.logError(jobName, errWrongParams.Error(), &map[string]interface{}{
			"Params": params,
		})
		return
	}

	hasExpectedOutputParameters := f.Type().NumOut() == 2 &&
		f.Type().Out(0).Kind() == reflect.Struct && f.Type().Out(0).Name() == "JobFunctionResult" &&
		f.Type().Out(1).Implements(reflect.TypeOf((*error)(nil)).Elem())

	if !hasExpectedOutputParameters {
		scheduler.logError(jobName, errWrongOutputParams.Error(), nil)
		return
	}

	wrappedJobFunc := func(params []interface{}) {
		scheduler.waitGroup.Add(1)
		defer scheduler.waitGroup.Done()

		in := make([]reflect.Value, len(params))
		for k, param := range params {
			in[k] = reflect.ValueOf(param)
		}

		scheduler.logInfo(jobName, "started", &map[string]interface{}{
			"Params": params,
		})

		start := time.Now()
		result := f.Call(in)
		duration := time.Since(start)

		jobResult := result[0].Interface().(JobFunctionResult)

		if !result[1].IsNil() {
			jobError := result[1].Interface().(error)
			scheduler.logError(jobName, jobError.Error(), nil)
		}

		scheduler.logInfo(jobName, jobResult.Message, &map[string]interface{}{
			"Success":      jobResult.Success,
			"DurationInMS": duration.Milliseconds(),
			"Params":       params,
			"Data":         jobResult.Data,
		})
	}

	_, err := cronScheduler.Do(wrappedJobFunc, params)

	if err != nil {
		scheduler.logError(jobName, "scheduling job failed", &map[string]interface{}{
			"Params": params,
			"Error":  err,
		})
	} else {
		scheduler.logInfo(jobName, "scheduling job was successful", &map[string]interface{}{
			"Params": params,
		})
	}
}

func (scheduler *Scheduler) Start(jobCompleteTimeoutOnShutdown time.Duration) {
	scheduler.cronScheduler.StartAsync()

	<-scheduler.done

	scheduler.cronScheduler.Stop()

	scheduler.logInfo("Scheduler", "waiting for jobs to complete", &map[string]interface{}{
		"TimeoutDuration": jobCompleteTimeoutOnShutdown,
	})

	start := time.Now()

	doneWaiting := make(chan struct{})

	go func() {
		scheduler.waitGroup.Wait()
		close(doneWaiting)
	}()

	select {
	case <-doneWaiting:
		duration := time.Since(start)
		scheduler.logInfo("Scheduler", "all jobs completed", &map[string]interface{}{
			"WaitedInMS": duration.Milliseconds(),
		})
	case <-time.After(jobCompleteTimeoutOnShutdown):
		duration := time.Since(start)
		scheduler.logInfo("Scheduler", "timed out waiting for jobs to completed", &map[string]interface{}{
			"WaitedInMS": duration.Milliseconds(),
		})
	}
}
```

**Comment by Streppel** [comment]
@scottadamsmith I see your point! Definitely worth bringing it out. I'd just argue that, from a functionality point of view, `.Stop()` intuitively should stop running jobs from rescheduling and wait for inflight jobs to stop as well, which covers over 90% of real world use cases, I believe.

I believe that if someone is afraid of `.Stop()` taking long to return they could always call it in a separate goroutine, as in `go sched.Stop()`, in which you'd have no guarantees that jobs will finish processing in the meantime (which is exactly what was happening before), and should give enough control to abort everything if needed using some control flow with a `select` statement (kind of exactly what you did in your code!).

Having `.IsRunning()` is still useful from my point of view, though, if one is concerned about jobs individually!

What do you guys think about all this?

**Comment by JohnRoesler** [comment]
Thanks for sharing all the detail @scottadamsmith - I find it really helpful to see how people are actually using the library! 

As for the logic...I see the point around long running jobs, and it seems like the responsibility of the caller to not schedule jobs that block forever, or at least know they have very long jobs. But, I could also see it being a nice feature to have the `scheduler.Stop()` accept a timeout and handle terminating the inflight jobs for the caller. 

I like the per job `IsRunning()` as it may be useful to a caller to know about the state of a specific job if for example they have a particular job that is highly critical running on the scheduler along with some less critical ones.

As for the current scope of the ticket, I would say we've completed the ask. However, we could open additional tickets for any enhancements, like the timeout if there seems to be value in that.
