### ISSUE TITLE
[FEATURE] - Need an option for cron job so that job which was supposed to run in the past on the same day, runs immediately.

### ISSUE THREAD

**Issue by indranil-elisity** [go-co-op/gocron#227]
### Is your feature request related to a problem? Please describe

Let's say the cron expression used to add a job to scheduler is "30 9 * * THU". But the time on which it was added is  10:30AM on Thursday (i.e. the same day). At present the task will run on next Thursday at 9:30AM. The cron expression could also be such  that it contains steps, ranges etc.

### Describe the solution you'd like

If a job is scheduled with this option then the above job, added at 10:30AM Thu, will run immediately.

### Describe alternatives you've considered

I considered the option of using version v1.6.2 where any job runs immediately after addition. However, it runs for all cases i.e. if a job is supposed to run at 9:30AM everyday and it is added on 8:30AM, it runs immediately. So it breaks other cases.

**Comment by JohnRoesler** [comment]
The linked PR #229 may not solve your issue for all cases, but will at least provide a way to force the cron job to start immediately and then get scheduled for its next run per the crontab schedule.

This would be a hard feature to implement given we don't how far in the past to look back. Anything on a schedule will have a time in the past it should have run, but if it is going to run soon you likely don't want it to be run immediately. 

It sounds somewhat like you're suggesting if it's adding on the current day it should be run, but what if we add one today and it was supposed to run the previous day?

**Comment by indranil-elisity** [comment]
Hello JohnRoseler, I really appreciate your help. PR #229 actually breaks my case. So if a job is supposed to start at 10AM and it was added at 9AM then also it is going to start immediately. I thought some more after reading your question about the previous day case. So this enhancement request can have two cases :
            Case1: Say user adds a cron for 14:00 at MONDAY and the program it started at 13:59 but for some system delay it got added at 14:02 at MONDAY (same day). So this probably requires a check for start time being in 1min/1sec in the past. 

             Case2: This is where the start time can be hours in the past. We can put a condition that as long as start time is in the past on the same day then it will be run immediately. 

Thank you.

**Comment by JohnRoesler** [comment]
The difficulty here is that we don't calculate past run times and only calculate the next run time. There would be a lot of logic additions needed to determine when the previous run should have been and then accept some criteria for determining when to kick off an immediate run of a past job. 

Do you have ideas on how to integrate the logic? I'm currently thinking that this sort of logic would need to be handled by the application calling gocron. For example, the caller could calculate when the last run should be, and use https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.RunByTag to execute a single run of the specific job.

**Comment by indranil-elisity** [comment]
I am trying to use another package github.com/gorhill/cronexpr to calculate the next time and compare that with the current system time. So if current time is 11:02AM Thursday and the cron was supposed to start at 11:00AM (everyday) then nextStarttime should be in future compared to current time. If not then job is getting added before the first cron expiry. Somehow 'Before()' and 'After()' function do not work as expected. But Before() always returns false

```
        timeNow := time.Now()
        nextStartTime := cronexpr.MustParse("37 01 * * ?").Next(time.Now())
        fmt.Println("nextStartTime:", nextStartTime)
        fmt.Println("timeNow:", time.Now())
        rslt := nextStartTime.Before(timeNow)
        if rslt {
                fmt.Println("Cron not late")
        } else {
                fmt.Println("Cron got late")
        }
```
output
=====
nextStartTime: 2021-09-10 01:47:00 +0530 IST
timeNow: 2021-09-10 01:46:07.3478727 +0530 IST m=+0.005003601
Cron got late

**Comment by indranil-elisity** [comment]
Is there an API available which can return the next execution time?

**Comment by JohnRoesler** [comment]
After creating a job you can call https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.NextRun

example:

```go
job, err := gocron.NewScheduler(time.UTC).Cron("* * * * *").Do(func() {})

fmt.Println(job.NextRun())
```
