### ISSUE TITLE
[BUG] - Scheduler should wait all jobs to finish before returning .Stop()

### ISSUE THREAD

**Issue by Streppel** [go-co-op/gocron#237]
### Describe the bug

Scheduler should wait all jobs to finish before returning .Stop()

### To Reproduce

```go
i := 0
s := NewScheduler(time.UTC)
s.Every(1).Second().Do(func() {
	time.Sleep(2 * time.Second)
	i = 1
})
s.StartAsync()
time.Sleep(1 * time.Second) // time to ignite job
s.Stop()
// on this line variable i should be 1 
```

### Version

v1.8.0

**Comment by JohnRoesler** [comment]
I see, so the scheduler doesn't wait, but it also doesn't stop that inflight job. If you add another sleep after s.Stop, it will increment to 1.

Good idea though!
