### ISSUE TITLE
[BUG] - Goroutine leak on singleton mode

### ISSUE THREAD

**Issue by lggomez** [go-co-op/gocron#242]
### Describe the bug

The job executor is leaking the goroutines of each job execution when running in singleton mode

### To Reproduce

1. Set up a single scheduler with the following configuration:

```go
        myJob := func() { ... }

	sched := gocron.NewScheduler(time.UTC)
	job, _ := sched.Every(5).Minutes().Do(myJob)

	job.SingletonMode()
	sched.StartAsync()
```

By performing a goroutine stacktrace dump I could get a bunch of these goroutines adding up during program execution:

```
goroutine 113300 [semacquire, 5 minutes]:
sync.runtime_Semacquire(0xc00036f568)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc00036f560)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
golang.org/x/sync/singleflight.(*Group).Do(0xc00180f300, 0xfad657, 0x4, 0xc0006cfe98, 0x5, 0x10, 0x4, 0x40f91b, 0x7f5071694f40)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:94 +0x1e5
github.com/go-co-op/gocron.(*executor).start.func1(0xc001f20014, 0xc0006b4ee0, 0x117f4d8, 0xc0007320c0, 0xe6bce0, 0xff3f28, 0xc00054b240, 0x4, 0x4, 0x12ee661, ...)
	/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/executor.go:82 +0x1c6
created by github.com/go-co-op/gocron.(*executor).start
	/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/executor.go:49 +0x145
```

### Version

v1.6.2, go 1.16.8

### Expected behavior

The executor should finish the goroutine execution properly and let it be collected by the runtime

**Comment by JohnRoesler** [comment]
@lggomez thanks for reporting this! I will definitely dig into it soon.

**Comment by JohnRoesler** [comment]
hey @lggomez if you print out the number of active goroutines i don't see any leaking or piling up.

```golang
func main() {
	s := gocron.NewScheduler(time.UTC)

	_, err := s.Every("1s").SingletonMode().Do(func() {
		log.Println("job run")

		// NumGoroutine returns the number of goroutines that currently exist.
		log.Printf("num goroutines: %v", runtime.NumGoroutine())
		debug.PrintStack()
	})
	if err != nil {
		log.Fatal(err)
	}
	s.StartBlocking()
}
```

This will show that yes, we are using a lot of goroutines, but they are being collected by the runtime and not left open. The goroutine id just continues to increment. You can see the number of goroutines in this case stays at 3. 1 for the scheduler, 1 for the executor and 1 for the single job.

Output:

```
2021/09/16 10:25:46 job run
2021/09/16 10:25:46 num goroutines: 3
goroutine 25 [running]:
runtime/debug.Stack()
    ...
    ...
```

Are you seeing anything different or something I am missing here?

**Comment by lggomez** [comment]
Sorry for the delay in the response. The example maybe lacks contexts as it has a 5 minute span and it may seem long for a local test. We've a polling job and our APM monitor shows an evergrowing (although with a slow pace) goroutine count:

![5042ef57-9353-48e4-af9e-e5bb6d91e607](https://user-images.githubusercontent.com/6326271/133939606-3b65cb19-b5c5-4db4-949b-517ca4c7121b.png)

Upon turning on pprof and executing a full goroutine dump I find hundreds of stale goroutines with the stacktrace described in the issue report. If there's anything I can do help discard this package as the leak source I can apply changes (altough I cannot share the involved worker's implementation since it's employer's code)

**Comment by JohnRoesler** [comment]
What did you use to make that graph? I’d like to recreate the same with a simplistic gocron scheduler. Or if you can recreate with one using a simple task that just prints out a log line.

**Comment by lggomez** [comment]
The graph comes from NewRelic golang runtime metrics, altough the full goroutine stack dump is done via pprof web handler (using the path /debug/pprof/goroutine?debug=2)

**Comment by JohnRoesler** [comment]
I don't believe it's an issue with gocron. I just added pprof to my previous example and it never has more than 5 goroutines running:

1. main where scheduler runs from
1. executor
1. job
1. pprof related
1. pprof related

```golang
package main

import (
	"log"
	"net/http"
	"runtime"
	"time"

	"github.com/go-co-op/gocron"

	_ "net/http/pprof"
)

func main() {
	// we need a webserver to get the pprof webserver
	go func() {
		log.Println("starting http listener")
		log.Println(http.ListenAndServe("localhost:6060", nil))
	}()

	s := gocron.NewScheduler(time.UTC)
	_, err := s.Every("1s").SingletonMode().Do(func() {

		// NumGoroutine returns the number of goroutines that currently exist.
		log.Printf("num goroutines: %v", runtime.NumGoroutine())
	})
	if err != nil {
		log.Fatal(err)
	}

	s.StartBlocking()
}
```

If you include the HTTP server, which is needed to report pprof as http response vs. a file, then you can see what goroutines are currently running.

```bash
curl http://localhost:6060/debug/pprof/goroutine?debug=1
```

I can see goroutine growth if I create a bunch of groutines that block, for example:

```golang
_, err := s.Every("1s").SingletonMode().Do(func() {

	// NumGoroutine returns the number of goroutines that currently exist.
	log.Printf("num goroutines: %v", runtime.NumGoroutine())

	go func() {
		select {}
	}()
})
```

**Comment by lggomez** [comment]
I finally found the cause and the issue can be closed, I tracked down the leak to a seemingly unrelated but existing leak from an sql.Rows instance not being closed from the worker.

It could be worth noting that leaks in goroutines spawned from the worker will propagate to the executor (which is obvious in hindsight) but may be difficult to diagnose in scenarios which involve connection pooling and singleton instances like sql clients

Thanks for your help!

**Comment by JohnRoesler** [comment]
You're welcome! And yes, perhaps some additional commentary to the readme could be added around this issue.
