### ISSUE TITLE
[BUG] - Weekdays scheduler scheduling every day

### ISSUE THREAD

**Issue by venugopalnaiduch** [go-co-op/gocron#243]
Created a scheduler to run schedule on Saturday of 1st, 2nd and 3rd weeks at a particular time, but the scheduler running every day at same time instead of scheduled weekdays.
 
The below is the cron which we are generating 
30 17 1-21 * 6
And when i check the next schedule time its showing as 2021-09-25 17:30:00 instead of 2021-10-02 17:30:00
And if the cron is as below it is scheduling every day
30 17 1-28 * 6
2021-09-22 17:30:00

We are using the below call for creating the cron scheduler
cronInstance.Cron("30 17 1-28 * 6").Tag("test").Do(<Func>, args)

Is there any thing we are doing wrong here while initialising cron

Thanks In Advance,
Venu.

**Comment by JohnRoesler** [comment]
Yes this looks like an issue with your crontab. Take a look at https://crontab.guru/#30_17_1-28_*_6 - it's a good tool for making sure your crontab is doing what you expect it to do.

For this cron it says: 

> At 17:30 on every day-of-month from 1 through 28 and on Saturday.

From a quick google search, it doesn't look like cron supports what you're suggesting. You could do https://crontab.guru/#30_17_*_*_6 for every saturday and then within your task, skip if it's the 4th or 5th saturday.
