### ISSUE TITLE
[FEATURE] - .Midday()

### ISSUE THREAD

**Issue by vaughany** [go-co-op/gocron#254]
### Is your feature request related to a problem? Please describe

No problem, just a (frivolous) enhancement: `.Midday()` - scheduling something to happen at midday.

### Describe the solution you'd like

Currently I have to write something like `s.Cron("0 12 * * *").Do(...)` to make something happen daily at midday (or
`s.Cron("0 12 * * 1-5").Do(...)` for midday on weekdays).

It would be much nicer to be able to write `s.Every(1).Midday().Do()` (or perhaps `s.Every(1).Day().Midday().Do()`).

### Describe alternatives you've considered

My original code does work exactly as expected.  There's nothing wrong with it. The solution is more characters, but less cognitive load to understand, and obviously more convenient.

### Additional context

This really is a 'nice to have' feature request and I'll totally understand if it gets rejected. That said, I may have a stab at implementing this myself and send along a PR.

**Comment by JohnRoesler** [comment]
I would welcome this feature. I agree it’s a nice to have but it does flow with the syntax we have going here.

**Comment by AlexanderSutul** [comment]
@JohnRoesler  Hey! I'd do this. Could you assign it on me?

**Comment by JohnRoesler** [comment]
Done! Ty @AlexanderSutul I’ll keep an eye out for the PR

**Comment by AlexanderSutul** [comment]
@JohnRoesler Hey! Sorry for a long delay. I was waiting my new laptop.
There is a PR https://github.com/go-co-op/gocron/pull/281

**Comment by JohnRoesler** [comment]
Thanks for coming back to it. Merged!
