### ISSUE TITLE
Great Library! - Does it support avoiding creating schedules that overlap ?

### ISSUE THREAD

**Issue by iangregsondev** [go-co-op/gocron#259]
Hi,

Does anybody know if supports something that tells me if a schedule overlaps an already existing schedule?

I would like to create the schedules in a DB, I am using GORM.

I want to validate in code that avoids a duplicate OR overlapping schedule.

For example, if a schedule runs One a week on Friday for 4 hours starting at 1pm.

If another schedule is created to start for 1 hour on Monday at 5pm - this would be fine - as there is no overlap.

BUT......

I would like to avoid overlap, so in code, if I try to create a schedule that runs Once a week on Friday for 1 hour starting at 3pm - this SHOULD error out (or some way of detecting it) because the FIRST example is currently running - there is an overlap.

Does anybody know if this is supported or if there is some kind of pattern to support this ?

Thanks in advance

**Comment by JohnRoesler** [comment]
Hi @iangregsondev 

There isn’t support for this case exactly where you’re suggesting blocking overlapping schedules from being added. 

Could you share some additional details on the use case so perhaps we can suggest how best to consider handling it either in your code or potentially a feature request?

We do support limiting concurrently running jobs if you were ok allowing schedules to overlap but simply wanted to make sure they didn’t run at the same time.

cheers!

**Comment by iangregsondev** [comment]
hi @JohnRoesler , thanks for the reply. Sure, let me give you a rundown.

I have a service (external daemon) that needs to run. I have already implemented the manually way - start and stop - works great.

So I wanted to use the schedule.. For example.

1. Needs to be able to start at a specific time and "END" at a specific time - not sure if the end is implemented here either ?

2. A person can create more than 1 schedule, for example, I want the service to be run twice on a Saturday, once at 2pm for 5 minutes and the other at 9pm until 11pm - no conflict/overlap here - all should be fine.

3. I am simply exposing some endpoints to allow the creation/deletion/editing of schedules. But I need to ensure that a user doesn't create a schedule at 10pm for example, because its already running between 9 and 11pm (see above). The external service should only run once. So I need to have a way of detecting that the current job I am creating does not overlap any other job created previously, if it does, in my case - it should error, but maybe there is a better way - or passing indicating to the developer that there is an overlap so they can decide to error or not.

I was planning on serializing all this in a sqlite db (using GORM :-) ).

Does that cover everything? Let me know if I can expand 

Ian

**Comment by iangregsondev** [comment]
I support the support for a TTR (time to run), that's what I was meaning by "END"

**Comment by JohnRoesler** [comment]
Hi @iangregsondev interesting use case! This isn't supported today, but natively Cron can do things like run between periods. However, there is no way to lookup what the scheduled periods would be through gocron. 

This would take some consideration for how it could be implemented. What I'm thinking about that you'd need:
- a method to report times between which the job is scheduled, for example `GetScheduledTimes("week", time.Now())` that would get the times the job is scheduled in the next week.
- a setting at the scheduler level perhaps that would then cause new jobs to have a lookup of the scheduled times to compare for the requested job and block overlap

It's not something I'd have the bandwidth for and I am not sure how well it fits. Perhaps if there is more interest in the feature or if someone wanted to push it forward it could happen.
