### ISSUE TITLE
[BUG] - executor nil pointer dereference running jobs

### ISSUE THREAD

**Issue by frenos** [go-co-op/gocron#269]
### Describe the bug

Trying out the lib, I just can't get it work at all. Even using the most basic example it crashes at this line https://github.com/go-co-op/gocron/blob/c3be44d54fb58382559e16160de33ab222916ac4/executor.go#L81
`runState` seems to be nil.

### To Reproduce

I try to run the following example:
```
package main

import (
	"github.com/go-co-op/gocron"
	"time"
)

func main() {
	scheduler := gocron.NewScheduler(time.Local)
	scheduler.StartAt(time.Now().Add(time.Second * 5)).Do(func() { println("hello") })
	scheduler.StartBlocking()
}
```

### Version

`go 1.17.4`
`github.com/go-co-op/gocron v1.11.0`

### Expected behavior

The example above should print "hello" after 5 seconds.

### Additional context
Did I miss anything to set it up correctly? I kind of doubt nobody realized basically the main feature of this lib is broken :)

**Comment by JohnRoesler** [comment]
hey @frenos thanks for bringing this up! 

So, the reason you're having an issue is that you're not calling the `Every()` function to set the interval (seconds, minutes, etc.)

Something like: `scheduler.Every("5s").StartAt(time.Now().Add(time.Second * 5)).Do(func() { println("hello") })`

I am raising a PR to catch that nil pointer issue and returning an error. Making sure to check errors on the job schedule is a good idea

```golang
func main() {
	scheduler := gocron.NewScheduler(time.Local)
	_, err := scheduler.StartAt(time.Now().Add(time.Second * 5)).Do(func() { println("hello") })
	if err != nil {
		log.Fatalln(err)
	}
	scheduler.StartBlocking()
}
```

**Comment by JohnRoesler** [comment]
It's also worth noting that without the Every() interval being set you'll get the odd behavior of the job being run as fast as your compute can handle over and over...

**Comment by frenos** [comment]
Thank you for helping me out. While testing how to integrate this into my app I switched between cron and the fluent api. When trying to distill a minimal example I must have lost the `Every` along the way :). When calling it everything works fine.
