### ISSUE TITLE
[FEATURE] - Run a job every first Tuesday of the month

### ISSUE THREAD

**Issue by JohnRoesler** [go-co-op/gocron#274]
### Describe the solution you'd like

A job should be able to be run every 1st, 2nd, 3rd, 4th, etc. day of the week of the month. For example:

```golang
scheduler.Every(1).Month().FirstTuesday()
```

### Additional context

Started with discussion: https://github.com/go-co-op/gocron/discussions/273

**Comment by AlexanderSutul** [comment]
@JohnRoesler Hey! Could you assign it on me? I'll have time to make this on weekend.

**Comment by AlexanderSutul** [comment]
> 

Hey! Sorry. Was very busy at work, going to finish this week.

**Comment by AlexanderSutul** [comment]
@JohnRoesler  Hey! Sorry, this weekend is full home stuff. 
If there is some more time till next release day, you can leave this issue assigned to me or assign it to someone else.
