### ISSUE TITLE
[BUG] - Cron expressions are not supporting to run second Monday of the month

### ISSUE THREAD

**Issue by sharanuainapur** [go-co-op/gocron#278]
### Describe the bug

Cron expressions are not functioning as expected. i.e **"0 0 0 * * 1#2**" this should work  for seond monday of month. But its saying invalid expression.

Also Cron expression not supporting year configuration. 

### To Reproduce

1. A
1. B
1. C

### Version

v1.11.0

### Expected behavior

cron expression should work for configuration ("**0 0 0 * * 1#2**") . I should run **At 12:00 AM, on the second Monday of the month**

### Additional context

Cron expressions are not working as expected like other platforms. 

"**0 0 0 * * 1#2**" this should work .

**Comment by JohnRoesler** [comment]
Hi @sharanuainapur could you share with me where you are seeing that `#` is a valid cron symbol? Everything I have read says it is not. I tried putting your provided cron expression in here https://crontab.guru/# and it confirms invalid expression.

There is already an open issue to support running on the first, second, etc. day of a week of a month -> https://github.com/go-co-op/gocron/issues/274 and if you look through the linked discussion in that issue -> https://github.com/go-co-op/gocron/discussions/273 you can see some of the code that was proposed to add this feature. 

As noted in that issue/discussion, crontab alone doesn't support running this case of "second Monday of the month". 

Cheers

**Comment by sharanuainapur** [comment]
> Hi @sharanuainapur could you share with me where you are seeing that `#` is a valid cron symbol? Everything I have read says it is not. I tried putting your provided cron expression in here https://crontab.guru/# and it confirms invalid expression.
> 
> There is already an open issue to support running on the first, second, etc. day of a week of a month -> #274 and if you look through the linked discussion in that issue -> #273 you can see some of the code that was proposed to add this feature.
> 
> As noted in that issue/discussion, crontab alone doesn't support running this case of "second Monday of the month".
> 
> Cheers
