### ISSUE TITLE
[FEATURE] - support Cron expression

### ISSUE THREAD

**Issue by yisany** [go-co-op/gocron#28]
Maybe you can do something to support cron expression.
such as:
cron.Every("0/40 * * * * ? ").Do(task)

**Comment by Streppel** [comment]
Hey yisany, thanks for reaching out. This could be implemented indeed... will make a few adjustments to see how it currently fits in our api, but I think we'd use a whole new methods set for this to keep things simple

**Comment by excxapp** [comment]
I think  this package can help parse cron expression
[https://github.com/robfig/cron](https://github.com/robfig/cron)

**Comment by DandyDev** [comment]
I would love to see this functionality as well. This library seems somewhat more robust and well maintained than https://github.com/reugn/go-quartz, but I want to be able to specify jobs in a config file, and cron expressions lend themselves really well for that.

Anyone going to work on this? I'm too new to Go to give it a shot sadly.

**Comment by Streppel** [comment]
Hey @DandyDev, thank you for the feedback. We're talking about this issue to see who's going to take it, but we have our eyes on it! :)

**Comment by JohnRoesler** [comment]
It's definitely something we'd like to support! I will have a PR up soon

**Comment by JohnRoesler** [comment]
@DandyDev @excxapp @yisany test the master branch if you have a chance. cron support is available now 👍  we've just pulled in robfig's parser and leveraged that.

**Comment by JohnRoesler** [comment]
This is released in https://github.com/go-co-op/gocron/releases/tag/v1.3.0
