### ISSUE TITLE
[FEATURE] - Passing some job/scheduled time metadata to the function called.

### ISSUE THREAD

**Issue by flevanti** [go-co-op/gocron#283]
### Is your feature request related to a problem? Please describe

_Not a problem but a nice to have._ 
Would it be possible to pass some information to the function called like the scheduled time?
In high frequency scheduled tasks (let's say every 3 minutes with unknown start time) it could be nice to know the scheduled time of the current run.

### Describe the solution you'd like
Somehow we need to change the called function signature.
We can have just one parameter that is a struct with the metadata related to the job and then a dedicated element is the list of parameters for the function itself 
OR
if the last parameter of the function is a specific type (e.g. JobMetadata) then metadata is added automatically to the parameters list when function is called.

My preferred one is the second option. it is less invasive and more eleganti and we can keep data types in the other parameters.

### Describe alternatives you've considered

Currently i make an assumption after few times the same function is called and estimate frequency and starting point hence the scheduled time/delay. not precise and a bit too complicated.

### Additional context

Another possible "solution" would be to expose the `scheduler.findJobsbyTag()` method , at that point I could easily look for the unique tag I already assign to each job and look for the scheduled run using the  `job.LastRun()` method.

**Comment by defc0n** [comment]
In my case, I need the task function to know the time the job of the task was scheduled at (`ScheduledTime()`) and when its next run will be (`NextRun()`). It seems my current attempt at getting this information from the job within the task handler function is subject to race conditions, though.

**Comment by defc0n** [comment]
Perhaps `DoWithInfo()` or something.

**Comment by flevanti** [comment]
> 
> > Another possible "solution" would be to expose the scheduler.findJobsbyTag()
> 
> That was added in the latest release! https://github.com/go-co-op/gocron/releases/tag/v1.12.0
> 
This is great, thanks!


> Another option I've considered is a job metadata / run channel to send out details when jobs are triggered, added, removed, etc. Would something like that help?
it would help in general, in my specific case given the frequency of some triggered jobs (tens every second) it could be hard to reconcile the triggered job with the received message in the channel.

I'm happy with the exposed the scheduler.findJobsbyTag() method personally.

PS just to give all this a bit of context ..... I am trying to determine the exact time a triggered job was scheduled doing some math because over time the time jobs are triggered is shifting ... few seconds... but over some days/weeks it becomes hard to determine the original scheduled time.

In any case... thanks for now!

If you are ok I will close the issue.

**Comment by JohnRoesler** [comment]
@flevanti I am fine with the issue being closed. 

@defc0n if you'd like to open a new feature request for the DoWithInfo we can sketch out more details of what that would like there.
