### ISSUE TITLE
[BUG] - method RemoveByTags() doesnt work

### ISSUE THREAD

**Issue by mrqiwi** [go-co-op/gocron#290]
### Describe the bug

RemoveByTags() doesnt remove a few jobs

### To Reproduce

1. add a few jobs:
    cron.Every(1).Minute().Tag("1").Do(func)
    cron.Every(1).Minute().Tag("2").Do(func)
2. try to remove all jobs by tag:
    cron.RemoveByTags("1", "2")
3. "error": "no jobs found with given tag"
   
### Version

github.com/go-co-op/gocron v1.11.0

### Expected behavior
method RemoveByTag() removes the tags without problems

**Comment by JohnRoesler** [comment]
Hi @mrqiwi 

The function is working as designed per the function description:

```golang
// RemoveByTags will remove Jobs that match all given tags.
func (s *Scheduler) RemoveByTags(tags ...string) error {
...
```

I can see how that would be confusing and that you'd expect a job that matched any of the tags not all of the tags would be removed. 

For this scenario, you'd have to call `RemoveByTag` twice, once with each tag.

I think it could be worth expanding the functionality of the RemoveByTags func to accept a match criteria, like "any" or "all". Or to add another function RemoveByTagsAny.

**Comment by mrqiwi** [comment]
function RemoveByTagsAny - is a good idea =)
