### ISSUE TITLE
[FEATURE] - Please how can I see what schedules are running?

### ISSUE THREAD

**Issue by jpastorm** [go-co-op/gocron#301]
I would like to know if there is a way to see its characteristics, such as tag and the time in which they will be executed

**Comment by JohnRoesler** [comment]
There isn't a single method to get details about all the jobs, but you can get info about each job. For example:

```golang
s := gocron.NewScheduler(time.UTC)
// add a bunch of jobs
// ...
// then get the jobs from the scheduler
jobs := s.Jobs()

for _, job := range jobs {
    fmt.Println(job.IsRunning())
    fmt.Println(job.NextRun())
    fmt.Println(job.Tags())
}
```

Docs:
- https://pkg.go.dev/github.com/go-co-op/gocron#Job.IsRunning
- https://pkg.go.dev/github.com/go-co-op/gocron#Job.NextRun
- https://pkg.go.dev/github.com/go-co-op/gocron#Job.Tags
