### ISSUE TITLE
[BUG] - Every() function will create new job when input is integer in update mode

### ISSUE THREAD

**Issue by YakDa** [go-co-op/gocron#308]
https://github.com/go-co-op/gocron/blob/20ce0b90de2ab4576cdaa79574ded5fb3d83d8aa/scheduler.go#L493
If it's update job or created job, why still create new job here? This will cause bug when the input of Every() function is an integer

For example, below code will give an exception because if it cannot find the job function in the scheduler jobs because of this bug.
```
package main

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron"
)

var task = func() { fmt.Println("hello") }

func main() {
	s := gocron.NewScheduler(time.UTC)
	j, _ := s.Every(1).Second().Do(task)
	s.StartAsync()

	time.Sleep(10 * time.Second)
	_, _ = s.Job(j).Every(5).Second().Update()

	time.Sleep(30 * time.Minute)
	_, _ = s.Job(j).Every(1).Day().At("02:00").Update()
}
```

**Comment by JohnRoesler** [comment]
@YakDa thank you for reporting! Something is certainly not working right. I will have time in the coming weeks to dig into this.
