### ISSUE TITLE
How remove job?

### ISSUE THREAD

**Issue by excxapp** [go-co-op/gocron#31]
### Is your feature request related to a problem? Please describe

If we send job by api, how delete old job? delete by *task object is not work,

### Describe the solution you'd like

I think we can add Id or tag ,for add job repeat,and can delete by tag/id

### Describe alternatives you've considered

We can set job tag/id,and this can use this can find job,and handler job by this

**Comment by auzty** [comment]
yes, i know that not only me thinking for deleting specific jobs.
so i edit to this file on my local, and just put a few function to delete by tag and working (i just don't know how to proper pull request to this repository)
if you mind, you can edit this following code

**scheduler.go**

```
// Remove First found Job by Tag
func (s *Scheduler) RemoveJobByTag(tag string) {
	jobindex := s.findJobsIndexByTag(tag)
	removeAtIndex(s.jobs, jobindex)
}

// Find first job index by given string
func (s *Scheduler) findJobsIndexByTag(tag string) int {
	for i, job := range s.jobs {
		if strings.Contains(strings.Join(job.Tags(), " "), tag) {
			return i
		}
	}
	return -1
}
// Set Tag when creating a job
func (s *Scheduler) SetTag(t []string) *Scheduler {
	job := s.getCurrentJob()
	job.tags = t
	return s
}

```

example : 

```

schedule1.Every(1).Day().At("05:00").SetTag("mytag").Do(runsamplefunction)

...
schedule1.RemoveJobByTag("mytag")
...
```

and it will be remove first job found that contain "mytag"

_notes :_  make sure you set unique tags or not null tags (i didn't test the null tags)

hope it works on you..
