### ISSUE TITLE
Adding schedules from a database in a loop causes the last record to be adding multiple times

### ISSUE THREAD

**Issue by saul-data** [go-co-op/gocron#313]
I keep all my schedules in a database. I am pulling the records off and loading them into the scheduler. The problem is the scheduler seems to be adding the schedules but only keeps the latest record values. 

Records look as follows:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/63714857/157844221-6ce55143-a5e5-40fa-b368-c070a0e7b7d0.png">

Here is the code:
```golang
	var pipelineSchedules []*models.Scheduler
	err := database.DBConn.Find(&pipelineSchedules).Error
	if err != nil {
		logging.PrintSecretsRedact("Platform nodes leader election:", err)

	}

for _, s := range pipelineSchedules {

				config.PipelineScheduler.Tag("pipelines", s.NodeID).CronWithSeconds(s.Schedule).Do(func() {
					log.Println("Trigger me", s.NodeID, s.Timezone)

				})
}
```

The output is giving this - which means its only taking the last database record. 
```
2022/03/11 09:46:35 Trigger me 1 Africa/Johannesburg
2022/03/11 09:46:35 Trigger me 1 Africa/Johannesburg
2022/03/11 09:46:40 Trigger me 1 Africa/Johannesburg
2022/03/11 09:46:40 Trigger me 1 Africa/Johannesburg
2022/03/11 09:46:45 Trigger me 1 Africa/Johannesburg
2022/03/11 09:46:45 Trigger me 1 Africa/Johannesburg
```

**Comment by saul-data** [comment]
I think I have worked it out - would be good to show how parameters get passed in documentation.

```golang
config.PipelineScheduler[s.Timezone].Tag("pipelines", s.NodeID).CronWithSeconds(s.Schedule).Do(mytask, s.NodeID, s.Timezone, x)

func mytask(nodeID string, timezone string, x int) {

	log.Println("Trigger me", nodeID, timezone, x)

}
```

**Comment by JohnRoesler** [comment]
@saul-data agreed on adding more documentation! The `Do` example should have one and I just added it 👍
