### ISSUE TITLE
[FEATURE] - Job event listener

### ISSUE THREAD

**Issue by Tochemey** [go-co-op/gocron#315]
Thanks for the great library. I would like to suggest to have some kind of events listeners on Job that can help hook into to them to track information related to a job.

**Comment by AlexanderSutul** [comment]
@Tochemey Hey! Could you, please, describe a feature you suggest in more detailed way. Maybe I'd like to implement this in that library.

**Comment by Tochemey** [comment]
@AlexanderSutul the features I am asking for are hooks that we can implement or add to handle some events once a job is running. The events for instance are:

- When a job has started event hook
- When a job has ended event hook
- When a job is in terminal state

I hope this make sense.

**Comment by AlexanderSutul** [comment]
> @AlexanderSutul the features I am asking for are hooks that we can implement or add to handle some events once a job is running. The events for instance are:
> 
> * When a job has started event hook
> * When a job has ended event hook
> * When a job is in terminal state
> 
> I hope this make sense.

I got it. But what is `terminal state`. Is that state when job only registered but not run yet? Or something different?

**Comment by Tochemey** [comment]
@AlexanderSutul Terminal state means the job is not running or failed. Yeah I understand that panic recovery can help handle that though

**Comment by AlexanderSutul** [comment]
@JohnRoesler Hey! Are you ok with this feature?
@Tochemey Ok, I've got it. I'll try to do this on this or next week, if @JohnRoesler will give an approval 😊  Have a good weekend 😊

**Comment by JohnRoesler** [comment]
sure @AlexanderSutul

**Comment by AlexanderSutul** [comment]
Hey guys @JohnRoesler  @Tochemey! 
I've created a [PR](https://github.com/go-co-op/gocron/pull/328) for this feature but with some constrains.
I didn't add the terminal handler because I'm not sure where it should be called in job life cycle. Could you review this. If you have an idea about `terminal` callback, please, let me know if you know how to add it to the codebase. Thanks and have a good weekend 😊

**Comment by AlexanderSutul** [comment]
This issue can be closed, I guess.
