### ISSUE TITLE
[BUG] - Script execute immediately and ignore cron expression

### ISSUE THREAD

**Issue by xccatana** [go-co-op/gocron#325]
### Describe the bug

If we provide parameters for a task that is called with `s.Cron().Do(task(params))` it makes the cronjob to run at the beginning of the program and once again when the cronjob meet the expression. 
If we don't provide parameters for `s.Cron().Do(task)` it is only executed when the cronjob meet the expression

### To Reproduce

```
func task(std string) string {
	// Function without return for collecting data
	fmt.Println(std)
	
        return std
}

func executeCronJob() {
	// Run the collector using env variable for cron expression
	// Read the CRON_EXPRESSION variable from envrionment
	cron_expression := lib.ReadEnvVariable("CRON_EXPRESSION")
	// Create new gocron scheduler
	s := gocron.NewScheduler(time.UTC)
        // Create the CronJob and call the task
	s.Cron(cron_expression).WaitForSchedule().Do(task("stdsss"))
}
```

### Version

v1.10.0

### Expected behavior

Run the script only once when the cronjob meet the expression not when the program starts and once again when the cronjob meet the expression.

**Comment by JohnRoesler** [comment]
Hi @xccatana ,

The code you posted doesn't appear to work. In order to call Cron you would need to call like this with the function parameter after the func name inside of `Do`:

```golang
s.Cron(cron_expression).Do(task, "stdsss")
```

Please use the latest version of the library and try again.
