### ISSUE TITLE
[FEATURE] - Add "lastRunFinished" counter which is increased after the job has finished 

### ISSUE THREAD

**Issue by reinkrul** [go-co-op/gocron#326]
### Is your feature request related to a problem? Please describe

When using `RunAll()` in unit tests to assert behavior of a some scheduled logic, there's no definite way to determine whether the jobs (or all jobs) have actually run. There's `Job.rounCount` but that is increased when the run is scheduled for execution, not after the job has actually finished. This leads to buggy test code which sleeps for X time, hoping the job will have finished by then.

### Describe the solution you'd like

Provide a counter per-job holding the number of finished executions. Probably together with the timestamp of when it finished, to keep the API in sync with `runCount` & `lastRun`

Or maybe a `RunAllAndWait()` function that blocks until all scheduled jobs have finished. 

### Describe alternatives you've considered

The function below blocks until all jobs have finished, but is not 100% reliable and pretty hacky:

```go
func runAllSchedulerJobs(scheduler *gocron.Scheduler) {
	// Limit max concurrent jobs so that the job below doesn't run concurrently with others, but order is not guaranteed
	scheduler.SetMaxConcurrentJobs(1, gocron.WaitMode)

	// Register a job that we can monitor when it has been executed
	wg := sync.WaitGroup{}
	wg.Add(1)
	job, _ := scheduler.Every(1).Hour().WaitForSchedule().Do(func() {
		wg.Done()
	})

	// Now run all jobs
	scheduler.RunAll()

	// Wait until the last job has been executed
	wg.Wait()
	scheduler.Remove(job)

	// Assert all jobs have finished
outer:
	for {
		time.Sleep(10 * time.Millisecond)
		for _, job := range scheduler.Jobs() {
			if job.IsRunning() {
				continue outer
			}
		}
		break outer
	}
}
```

**Comment by JohnRoesler** [comment]
hey @reinkrul sorry it took me forever to get to this request. I've added the finished run count in #452 that will allow you to check in your test for the expected number of completed runs.

**Comment by reinkrul** [comment]
> hey @reinkrul sorry it took me forever to get to this request. I've added the finished run count in #452 that will allow you to check in your test for the expected number of completed runs.

Thanks, awesome! 👍
