### ISSUE TITLE
Run or don't run a job between a period

### ISSUE THREAD

**Issue by arigon** [go-co-op/gocron#327]
Hello

is it possible to run a job between a period or don't run it between a period?
For example I want to run a job every 15 minutes but only from 07:00 a.m. to 05:00 a.m. the following day (2 hours stop time).

best
Alex

**Comment by JohnRoesler** [comment]
You should be able to do that with a cron expression -> https://crontab.guru/#*/15_0-5,7-23_*_*_*

And that would be `scheduler.Cron("*/15 0-5,7-23 * * *").Do(task)`

**Comment by arigon** [comment]
Thank you! This is exactly what I was looking for.
