### ISSUE TITLE
[FEATURE] - no mechanism to handle panic in jobs

### ISSUE THREAD

**Issue by pkuashi** [go-co-op/gocron#332]
### Is your feature request related to a problem? Please describe

See code below, currenlty gocron does not capture the panic in child job and crash

package main

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron"
)

var task = func() {
	fmt.Println("Task is started!")
	panic("a problem")
}

func main() {
	s := gocron.NewScheduler(time.UTC)
	s.Every(1).Second().Do(task)
	s.StartAsync()
	time.Sleep(2 * time.Second)
	j := s.Jobs()[0]
	fmt.Println(j.Error())
}

### Describe the solution you'd like

The job.Error() not only provide the error during job scheduling but also panic raised by job

### Describe alternatives you've considered

N/A

**Comment by fenisteel** [comment]
It would be a great feature to have a global PanicHandler func at package level.

I think it should be a type of `func(jobName string, recoverData interface{})` and in the executor's loop defer it if it's not nil.

Suggested changes:

**gocron.go:**
```
type PanicHandlerFunc func(jobName string, recoverData interface{})

var PanicHandler PanicHandlerFunc = nil
```

**executor.go:**

```
func (e *executor) start() {
    stopCtx, cancel := context.WithCancel(context.Background())
    runningJobsWg := sync.WaitGroup{}

    for {
        select {
        case f := <-e.jobFunctions:
            runningJobsWg.Add(1)
            go func() {
                if PanicHandler != nil {
                    defer func(){
                        if r := recover(); r != nil {
                            PanicHandler(f.name, r)
                        }
                    }()
                }
                defer runningJobsWg.Done()
                ...

```

**Use case:**

```
import "github.com/go-co-op/gocron"

func MyPanicHandler(jobName string, recoverData interface{}) {
	fmt.Println("A panic occured during running job: " + jobName)
}

func main() {
	Cron = gocron.PanicHandler = MyPanicHandler
	...
}
```

**Comment by JohnRoesler** [comment]
looks reasonable. @fenisteel would you like to make a PR for this?

**Comment by fenisteel** [comment]
What do you think, when could a new version released which includes this PR?

**Comment by pkuashi** [comment]
@JohnRoesler The latest release was at Feb this year. Any planned release recently.

**Comment by JohnRoesler** [comment]
Released!

**Comment by fenisteel** [comment]
Great job! Thanks!
