### ISSUE TITLE
[BUG] - CPU usage 100% in WaitMode

### ISSUE THREAD

**Issue by aibotsoft** [go-co-op/gocron#333]
With this test code:

```
package main

import (
	"github.com/go-co-op/gocron"
	"time"
)

func job() {
	time.Sleep(time.Second * 3)
}

func main() {
	s := gocron.NewScheduler(time.UTC)
	s.SetMaxConcurrentJobs(1, gocron.WaitMode)
	s.Every(time.Second * 5).Do(job)
	s.Every(time.Second * 5).Do(job)
	s.StartBlocking()
}
```
I get 100% CPU utilization (at least one core) which is equivalent to an infinite loop:

```
package main

func main() {
	for {
		
	}
}
```

**Version**
v1.13.0

**Expected behavior**
While waiting for a free executor, the processor should not be loaded at 100%

**Comment by AlexanderSutul** [comment]
@JohnRoesler Is that a good approach to add a delay in 1 * nanosecond? It's just a fastest solution I can suggest for now 😊

**Comment by AlexanderSutul** [comment]
@aibotsoft  Hey! Are you sure it's a problem? I just checked that 100% here doesn't effect  any I/O operations. So, yeah it's 100% but it's like fake 100% of usage. So, it's just flooded OS scheduler.  
Correct me, if I'm wrong, please. (links for articles about that are appreciated)

**Comment by AlexanderSutul** [comment]
Thanks for your thoughts. Let's see what I can do. I'll try to fix it till the end of next week.

**Comment by JohnRoesler** [comment]
@aibotsoft this is interesting! The reason it is done the way currently is to allow checking the state of both the scheduler and individual job context states. The Acquire method allows waiting for a single context to be done, but I notice even in that case, it can still run the job even after the context done occurs:

> // Acquired the semaphore after we were canceled.  Rather than trying to
			// fix up the queue, just pretend we didn't notice the cancelation.

Now maybe that's a cost worth paying to lower CPU. I haven't tried it yet with this method, but it looks to be doing something similar to the executor logic under the hood.
