### ISSUE TITLE
[BUG] - Program level exit

### ISSUE THREAD

**Issue by mhxw** [go-co-op/gocron#341]
### Describe the bug

```
goroutine 76763 [running]:
golang.org/x/sync/singleflight.(*Group).doCall.func1()
        /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:165 +0x2b3
golang.org/x/sync/singleflight.(*Group).doCall(0x85edc0, 0xc01055a4b0, {0x8d0ebe, 0x4}, 0x519b88)
        /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:200 +0xc8
golang.org/x/sync/singleflight.(*Group).Do(0xc01056c000, {0x8d0ebe, 0x4}, 0xc0002a8f38)
        /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:108 +0x154
github.com/go-co-op/gocron.(*executor).start.func1()
        /root/go/pkg/mod/github.com/go-co-op/gocron@v1.13.0/executor.go:84 +0x214
created by github.com/go-co-op/gocron.(*executor).start
        /root/go/pkg/mod/github.com/go-co-op/gocron@v1.13.0/executor.go:49 +0x76
```

### To Reproduce

`_, err := Cs.Every("1s").SingletonMode().Do(func() {`

### Version

1.13.0

**Comment by JohnRoesler** [comment]
Please explain

**Comment by mhxw** [comment]
I guess it's a bit similar to this https://github.com/go-co-op/gocron/issues/333. If my program executes logic inside more than 1s, he will wait for the inside program to finish before executing the next one.

**Comment by mhxw** [comment]
The program will execute for some time before it throws an exception and exits

**Comment by JohnRoesler** [comment]
I'm not able to reproduce this issue. Can you provide a full example that hits this issue? Re-open if you'd like assistance.

**Comment by JohnRoesler** [comment]
I'm not able to reproduce this issue. Can you provide a full example that hits this issue? Re-open if you'd like assistance.
