### ISSUE TITLE
Setting time.Duration while scheduling job using Every fails

### ISSUE THREAD

**Issue by cyberbandya007** [go-co-op/gocron#342]
### Describe the bug

If we use time.Duration value while scheduling job, it doesn't work.

### To Reproduce

1. Set time.Duration while scheduling the job
2. Start jobs asynchronously
3. Check if job executes.

### Version

1.14.1

### Expected behavior

We should be able to schedule jobs using time.Duration since it is provided as option in the documentation

### Additional context
As I can see the implementation of Every() method, it clearly sets interval as 0. I believe this should be causing problem.
case time.Duration:
		job.interval = 0
		job.setDuration(interval)
		job.setUnit(duration)

**Comment by JohnRoesler** [comment]
@cyberbandya007 could you please share the code you are running which is failing? 

These both work for me:

```go
package main

import (
	"log"
	"time"

	"github.com/go-co-op/gocron"
)

func main() {
	log.SetFlags(log.LstdFlags | log.Lmicroseconds)

	s := gocron.NewScheduler(time.UTC)
	s.Every("2s").Do(func() { log.Println("hello 1") })
	s.Every(2 * time.Second).Do(func() { log.Println("hello 2") })

	s.StartBlocking()
}
```

It's not a problem that `job.interval` is being set to zero because when the unit is duration, the calculation doesn't consider interval, it considers the duration value.
