### ISSUE TITLE
release-v0.1.1 doesn't have StartBlocking

### ISSUE THREAD

**Issue by huangp0600** [go-co-op/gocron#36]
when I use the release version of V0.1.1 to do some cronjob test, I found that it doesn't have the function `StartBlocking`. I have to use `<- xxx.Start()` as an instead.
Is it be added in recent days? or what's the plan to add it to a new release version?

**Comment by Streppel** [comment]
@huangp0600 we will address this today

**Comment by Streppel** [comment]
fixed :) https://github.com/go-co-op/gocron/releases/tag/v0.2
