### ISSUE TITLE
[BUG] - github.com/jasonlvhit/gocron/example/go.mod:8:2: require github.com/go-redis/redis: version "v8.11.2" invalid: should be v0 or v1, not v8

### ISSUE THREAD

**Issue by BaSO4** [go-co-op/gocron#371]
### Describe the bug

github.com/jasonlvhit/gocron/example/go.mod:8:2: require github.com/go-redis/redis: version "v8.11.2" invalid: should be v0 or v1, not v8

### Version

master branch

### Expected behavior
go mod right

**Comment by JohnRoesler** [comment]
> github.com/jasonlvhit/gocron/example

That isn't this library. We forked from jasonlvhit a while back but I don't see any references in the code to it.

**Comment by BaSO4** [comment]
sorry, should be opened to /jasonlvhit/gocron

**Comment by JohnRoesler** [comment]
@BaSO4 FYI - that repo is no longer maintained. We moved it here.
