### ISSUE TITLE
Run funciton after some time.

### ISSUE THREAD

**Issue by wahello** [go-co-op/gocron#373]
### Specify the function lunch after some time, such as 5 seconds, or 5 minutes.
eg: 
```
s.Every(20).Seconds().After("5m").Do(func() { 

})
```

**Comment by JohnRoesler** [comment]
hi @wahello i'd suggest reading through the go docs. This is already supported https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.StartAt
