### ISSUE TITLE
[BUG] - "call of reflect.Value.Type on zero Value" error when using in SingletonMode

### ISSUE THREAD

**Issue by Jonas096** [go-co-op/gocron#376]
### Describe the bug

When using the SingletonMode the module panics with the error "call of reflect.Value.Type on zero Value". The weird thing is, this error applys only 3 of 4 times. Sometimes the applications starts well.

### To Reproduce

My Setup is like this

`func InitScheduler() {
	gocron.SetPanicHandler(func(jobName string, recoverData interface{}) {
		logs.Logger.Panicln("jobName", jobName, "error", recoverData)
	})
	Scheduler = gocron.NewScheduler(time.UTC)

	//maximal werden 5 Jobs gleichzeitig durchgeführt
	//jeder Job danach wird einfach in eine Warteschlange gesetzt
	Scheduler.SetMaxConcurrentJobs(5, gocron.WaitMode)

	//wenn der Job noch läuft, und eigentlich jetzt wieder an der Zeit durchgeführt werden sollte
	//wird er nicht wieder ausgeführt
	Scheduler.SingletonMode()

	defer Scheduler.StartAsync()
}`

### Version

go 1.18
github.com/go-co-op/gocron v1.16.2

### Expected behavior

No Panic at start of the application

**Comment by JohnRoesler** [comment]
@jerebtw @Jonas096 sorry for the late reply! 

Scheduler.SingletonMode() is meant to be called in a chain defining a job. For example:

```golang
Scheduler.Every(10).Second().SingletonMode().Do(func() {
	log.Println("hello")
})
```

The global scheduler option is:

```golang
Scheduler = gocron.NewScheduler(time.UTC)
Scheduler.SetMaxConcurrentJobs(5, gocron.WaitMode)
Scheduler.SingletonModeAll()
```

This isn't handled well currently as you've encountered. I'll push up a fix to catch this situation.
