### ISSUE TITLE
[BUG] - incorrectly calculating nextRun for daily interval

### ISSUE THREAD

**Issue by Maksim-YmnIchkA** [go-co-op/gocron#383]
### Describe the bug

Job that scheduled periodically with "day" interval incorrectly calculates nextRun time.

### To Reproduce

1) time.UTC locale setup
scheduler := gocron.NewScheduler(time.UTC)

2) schedule job every 1 day
scheduler.Every(1).Day().StartAt(startTime).Do(test)

If now call job.NextRun() you will get 0001-01-01 00:00:00 +0000 UTC
there are 2 options for the job behaviour:
1) If you set timeStart in the past the job will start at 03:00 AM every day;
2) If you set timeStart in the future the job will start at correct time specified.

In both ways on call job.NextRun() you will get 0001-01-01 00:00:00 +0000 UTC.

### Version

go 1.17.6
gocron v1.16.3

### Expected behavior

1) If you set timeStart in the past, scheduler should correctly calculate time in the future to run job by adding 24 hours (for example;
2) If you set timeStart in the future. scheduler works correctly.

In both ways on call job.NextRun() expected to get correct time of the NextRun.

**Comment by JohnRoesler** [comment]
Hi @Maksim-YmnIchkA 

can you show a full example where you call job.NextRun? If you are calling it before starting the scheduler then it will be a zero time as the scheduler doesn't calculate the next run for each job until the scheduler is started.

**Comment by Maksim-YmnIchkA** [comment]
> 

I'm sorry, it seems that I miss it in documentation, i was sure i can use this method anytime I need it, that's my fault, close the issue please.

**Comment by JohnRoesler** [comment]
No worries!
