### ISSUE TITLE
[BUG] - CPU usage 100% and next schedule is blocking after the system time is changed

### ISSUE THREAD

**Issue by allanche** [go-co-op/gocron#385]
### Describe the bug

use this code run cron scheduler，CPU usage 100% and next schedule is blocking after the system time is changed.
```
package main

import (
	"github.com/go-co-op/gocron"
	"log"
	"time"
)

func task() {
	log.Println("hello world.")
}

func main() {
	s := gocron.NewScheduler(time.UTC)
	_, _ = s.Cron("*/1 * * * *").Do(task)
	s.StartBlocking()
}
```
### To Reproduce

1. current system time: 
```
Mon Aug 29 17:30:22 CST 2022
```
2. change system time forward 1 hour:
```
Mon Aug 29 16:30:51 CST 2022
```
3. next schedule has bug. 
### Version
v1.13.0

### Additional context
use pprof make analysis，test code is:
```
package main

import (
	"github.com/go-co-op/gocron"
	"log"
	"net/http"
	_ "net/http/pprof"
	"time"
)

func task() {
	log.Println("hello world.")
}

func main() {
	go func() {
		http.ListenAndServe("0.0.0.0:6060", nil)
	}()
	s := gocron.NewScheduler(time.UTC)
	_, _ = s.Cron("*/1 * * * *").Do(task)
	s.StartBlocking()
}
```
1. change system time forward 1 hour，wait for the next scheduling exception.
2. use curl command dump profile.
```
curl http://127.0.0.1:6060/debug/pprof/profile\?seconds\=60 > profile.out
``` 
3. use go tool display profile.
```
go tool pprof -http=":8082" profile.out
```
4. get cpu usage 100% code line is:
```
0.95s   100% |   github.com/go-co-op/gocron.(*Scheduler).scheduleNextRun.func1 xxx/go/pkg/mod/github.com/go-co-op/gocron@v1.13.0/scheduler.go:204
```

5. review gocron scheduler line 204:
```
	job.setTimer(time.AfterFunc(next.duration, func() {
		if !next.dateTime.IsZero() {
			for {
				if time.Now().Unix() >= next.dateTime.Unix() {
					break
				}
			}
		}
		s.run(job)
		s.scheduleNextRun(job)
	}))
```
The for loop here can cause CPU usage to reach 100% and block the next schedule.
6. suggest example:
We can set the timer check condition  **time.Now().Unix() >= next.dateTime.Unix()**  and set the timeout to jump out for loop，ensure the next scheduling.
```
job.setTimer(time.AfterFunc(next.duration, func() {
		if !next.dateTime.IsZero() {
			timeout := 30 * time.Second
			interval := 1 * time.Second
			timer := time.NewTimer(timeout)
			ticker := time.NewTicker(interval)
			defer timer.Stop()
			defer ticker.Stop()
			for {
				if time.Now().Unix() >= next.dateTime.Unix() {
					break
				}
				select {
				case <-ticker.C:
					ticker.Reset(interval)
					continue
				case <-timer.C:
					break
				}
				break
			}
		}
		s.run(job)
		s.scheduleNextRun(job)
	}))
```

**Comment by JohnRoesler** [comment]
I did some poking around at this problem. And your solution doesn't seem to work, i'm not exactly sure why. But i think part of the issue with handling system time changing is that we'd need to detect the system time change and then adjust all the jobs last run times by that change amount to properly handle calculations that rely on the last time the job ran.

**Comment by allanche** [comment]
> I did some poking around at this problem. And your solution doesn't seem to work, i'm not exactly sure why. But i think part of the issue with handling system time changing is that we'd need to detect the system time change and then adjust all the jobs last run times by that change amount to properly handle calculations that rely on the last time the job ran.

Your solution idea is right, but I am not sure what impact it will have on the whole project. because the cpu usage will affect other services of the system. Therefore, my solution only ensures that the next scheduling can be executed correctly and the cpu usage remains normal.

**Comment by JohnRoesler** [comment]
> Therefore, my solution only ensures that the next scheduling can be executed correctly and the cpu usage remains normal.

I tested it out though and changed my system clock and the jobs did not continue to run, so something about the logic proposed doesn't work quite right.

It's an interesting problem and possibly the simplest answer would be to include some logic in a system running gocron to restart when a system time change occurs. Otherwise, there isn't currently any mechanism to handle adjusting the jobs to run properly based on the new datetime.

**Comment by allanche** [comment]
> > Therefore, my solution only ensures that the next scheduling can be executed correctly and the cpu usage remains normal.
> 
> I tested it out though and changed my system clock and the jobs did not continue to run, so something about the logic proposed doesn't work quite right.
> 
> It's an interesting problem and possibly the simplest answer would be to include some logic in a system running gocron to restart when a system time change occurs. Otherwise, there isn't currently any mechanism to handle adjusting the jobs to run properly based on the new datetime.

Yeah, this is the simplest way to handle it. maybe we can test the scheduling of linux crontab when the clock is changed? Maybe crontab has the right solution.

**Comment by shtirlic** [comment]
Here is the info for original cron https://stackoverflow.com/questions/13195999/daylight-savings-and-cron

**Comment by JohnRoesler** [comment]
There is an accepted proposal https://github.com/golang/go/issues/36141 for Go to add a concept of `External` time, which is akin to "real time" that will solve this issue in gocron. Until that point, programs will just need to be restarted in the event of a machine changing time.
