### ISSUE TITLE
If the system is in sleep during the time it was scheduled to run, how to trigger it once the PC comes back online?

### ISSUE THREAD

**Issue by shrinidhi111** [go-co-op/gocron#396]
Let's say I have a one-time scheduler that is created using `gocron.NewScheduler().At()` that is set to run at 1 PM (say)

Now suppose the computer goes to sleep at 12 PM and is back online at 2 PM. 

Does the job actually execute once the system is back online? Or does it ignore it since time has passed?

If it doesn't execute, how do I ensure that it will run once the user wakes up from sleep??

**Comment by JohnRoesler** [comment]
This isn't supported by gocron today. 

I can imagine you'd need a way to write the result of each job to a persistent store, and then as part of the scheduler check for jobs in the store and make sure that they have run at the required time and if not run them immediately.

**Comment by shrinidhi111** [comment]
Thanks!

If anyone else is interested, this library works with this use case (as per my testing with sleep)

https://github.com/procyon-projects/chrono

PS : Of course if you're PC is shutdown/restarted, then persistent storage will be required as @JohnRoesler suggested

**Comment by JohnRoesler** [comment]
There is an accepted proposal https://github.com/golang/go/issues/36141 for Go to add a concept of `External` time, which is akin to "real time" that will solve this issue in gocron. Until that point, programs will just need to be restarted in the event of a machine going to sleep.
