### ISSUE TITLE
[FEATURE] - Fedora package

### ISSUE THREAD

**Issue by jamesread** [go-co-op/gocron#397]
Fedora (http://fedoraproject.org) requires that all go applications have the go dependencies also packaged too - especially as packages are built securely, without internet access. I'm the author of https://github.com/OliveTin/OliveTin which has a dependency on gocron, hence it needs a Fedora package :-) 

I have taken the liberty of building a spec file that I believe would be accepted by the Fedora project. I'd like to raise this issue here though as a friendly notification / request permission that this is something that you'd be OK with. 

The spec is autogenerated from go2rpm - I'm told that's generally the way to go now-a-days with Fedora at least. The repository is here for your review / reference; https://github.com/jamesread/gocron-package-fedora

My intentions are to maintain the package on an ongoing basis - or at least while OliveTin keeps being wanted by people! If everything is OK, just a quick "ack" to confirm your support would be great, if not - let's discuss :-)

**Comment by JohnRoesler** [comment]
Yes that is acceptable. Thanks for making the project usable on that platform.
