### ISSUE TITLE
[BUG] - Unable to get v0.2 version using go mod

### ISSUE THREAD

**Issue by urpent** [go-co-op/gocron#40]
### Describe the bug

Unable to get v0.2 version using go mod. The latest version I was able to get is (v0.1.1). Was it due to naming convention of the version?

1. Terminal show an error when using v0.2  -> no matching versions for query "v0.2"

2. Terminal show an error when using v0.2.0  -> unknown revision v0.2.0

**Comment by Streppel** [comment]
@urpent thank you for pointing it out. I've fixed the tag semver, tested it locally and it worked correctly. Could you test it again?

**Comment by urpent** [comment]
It works correctly now. Thanks!
