### ISSUE TITLE
[FEATURE] - Please add limit mode "WaitModeSingle"

### ISSUE THREAD

**Issue by uginroot** [go-co-op/gocron#401]
### Is your feature request related to a problem? Please describe

My function updates links to images that are about to expire for each client.

And it is necessary that its re-call occurs immediately after the previous one, if the previous call "blocked" the schedule.

But there are situations when the previous call can "overlap" not one call in the schedule, but 2, 3 or 4.

### Describe the solution you'd like

In this case, gocron.WaitMode would help me, but now it will call the function 2-4 times in a row.

I would like to have a similar gocron.WaitModeSingle, which would turn into gocron.RescheduleMode if there is already at least 1 next call in the queue.

### Describe alternatives you've considered

Now a timer is used, in an infinite loop, which does not accumulate calls in the queue. But this is cumbersome and harder to understand.

**Comment by JohnRoesler** [comment]
Have you tried using [`SingletonMode()`](https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.SingletonMode)?

**Comment by uginroot** [comment]
Unfortunately, it doesn't suit me. I need the maximum queue size to be one.

Sometimes the function can run for 2 hours, and sometimes for 2 minutes. But it will always do all the necessary work at the time when it started. If I put accumulation in the queue and an interval of 10 minutes, after 2 hours there will be 11 repeated executions in the queue when I only need 1 execution.

I solved the problem like you said with a [SingletonMode()](https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.SingletonMode), but I had to add extra logic to my code. It would be handy if I could just put a limit on the number of executions to one.

I thought that adding another limitMode would help solve similar problems for other users without adding more logic to the task

**Comment by JohnRoesler** [comment]
Thanks for sharing more details. The limit mode `reschedule` didn't work either?

**Comment by uginroot** [comment]
Apologies for not replying for a while.

Yes, it does work as you said, but it still doesn't solve my problem.

I need to adhere to the execution interval. If I don't, I let down those who rely on it, but on the other hand, if I execute the task consecutively 2-3 times, I overload my servers heavily.

If the task was executed "(4*interval)+1s", then it's tolerable. It's bad if right after execution, it didn't start again once to "catch up" with the changes. It's very bad if the task runs 4 times in a row instead of just once.

**Comment by JohnRoesler** [comment]
Hi @uginroot 

In v2 I implemented reschedule as an option on singleton mode. https://pkg.go.dev/github.com/go-co-op/gocron/v2#WithSingletonMode

If I am understanding, it sounds like what you want.
