### ISSUE TITLE
[BUG] Cronjob executed earlier than expected, and executed twice

### ISSUE THREAD

**Issue by shieldnet** [go-co-op/gocron#409]
#### What I did
- I registered a cronjob with cron expression with second (`0 50 9 * * *`) for daily job execution.
```go
// simplified code
var s *gocron.Scheduler = gocron.NewScheduler()
s.CronWithSeconds("0 50 9 * * *").Do(func() {
   // job functions
})
s.StartAsync()
```
- My program executed for about three days (12/23 19:00 GMT+9 ~ 12/26 16:00 GMT+9)

#### What actually happened
- Cronjobs which are scheduled on `12/24 09:50:00` and `12/25 09:50:00` executed exactly on expected time.
- But, job schdueled `12/26 09:50:00` suddenly executed on `12/26 09:48:58.906632`. and After the earlier job finished, the job scheduled on `12/26 09:50:00` executed twice.
- Only 12/26 09:50:00 job executed twice and earlier than expected.

### To Reproduce
- I can not assure that this bug can be reporduced.
 
1. register cronjob with cron expression
2. start async

### Version
- go1.18.3

### Expected behavior
- Just one execution of cronjob, at 09:50:00 AM (or, a few seconds after schedule).

### Additional context
- NA

**Comment by HL130** [comment]
I'm experiencing the same issue with `StartBlocking()`

**Comment by yqchilde** [comment]
I also have a similar problem. In my project, execution is occasionally triggered twice. This problem exists in v1.18.0.

**Comment by fufuok** [comment]
Maybe related to #393?

**Comment by JohnRoesler** [comment]
I ran a cron job every hour on the 30 min mark for a couple days and didn't observe this issue. Is anyone here still seeing it occur?
