### ISSUE TITLE
[FEATURE] - Error chan on scheduler

### ISSUE THREAD

**Issue by 110** [go-co-op/gocron#41]
https://github.com/jasonlvhit/gocron/issues/134

This feature was discussed before.  
hop add this  feature .

**Comment by JohnRoesler** [comment]
This would be a grand addition. Something you're interested in contributing on?

**Comment by ofonimefrancis** [comment]
> This would be a grand addition. Something you're interested in contributing on?

I would love to work on this @JohnRoesler, what logger would you recommend?

**Comment by JohnRoesler** [comment]
Exactly - we'd want an interface that the user would them implement with their specific chosen logger! Let us know if you want to discuss or if you need any assistance! We're on slack - there is a link in the readme

**Comment by arjunmahishi** [comment]
@ofonimefrancis you can use an interface like this:
```go
type Logger interface {
	Debugf(format string, args ...interface{})
	Infof(format string, args ...interface{})
	Printf(format string, args ...interface{})
	Warnf(format string, args ...interface{})
	Warningf(format string, args ...interface{})
	Errorf(format string, args ...interface{})
	Fatalf(format string, args ...interface{})
	Panicf(format string, args ...interface{})

	Debug(args ...interface{})
	Info(args ...interface{})
	Print(args ...interface{})
	Warn(args ...interface{})
	Warning(args ...interface{})
	Error(args ...interface{})
	Fatal(args ...interface{})
	Panic(args ...interface{})
}
```
(Partly taken from logrus)

You can remove some of the methods like `Panic`, `Print` to keep it simple.

**Comment by arjunmahishi** [comment]
I am planning to work on this. Will mostly create a PR sometime today. @ofonimefrancis, let me know if you have already started working on it

**Comment by arjunmahishi** [comment]
@JohnRoesler @Streppel Can we list down the things we want to log with their log-levels?

Here are some things I can think of:
```shell
# Job related
[DEBUG] Running job: <job name>
[INFO] Ran job: <job name>
[ERROR] Failed to run job: <job name>

# Scheduler related
[INFO] Scheduled the job '<job name>' to run at '<time>'
```

**Comment by arjunmahishi** [comment]
I've created a simple custom logging framework and pushed it to the branch [feature/custom-logger](https://github.com/go-co-op/gocron/tree/feature/custom-logger). Let me know what you guys think.

**Comment by Streppel** [comment]
@arjunmahishi Cool! Will take a look at it this weekend (been in a hurry this week)

**Comment by arjunmahishi** [comment]
Made some changes to the initial code and made a PR. Not actually logging anything. This is just a framework as mentioned before. Take a look when you guys get time.

**Comment by Streppel** [comment]
@arjunmahishi putting it on blocked while we discuss

**Comment by JohnRoesler** [comment]
Repurposing this issue to the solution we discussed in #57 

> The scheduler could have a `func (s *sched) CatchErrors() chan` method to expose the error channel.
