### ISSUE TITLE
Run goroutine in background with no dependency from main

### ISSUE THREAD

**Issue by ankurnigam** [go-co-op/gocron#42]
Can this module be used for the case where we want to run the goroutine in background without any dependency on main.

It means main block will complete but that block will keep running till it completes all it's task.

**Comment by JohnRoesler** [comment]
I don’t believe you can accomplish this in golang. When mason is terminated, all other goroutines triggered will be terminated. See this forum for more detail https://groups.google.com/forum/m/#!topic/golang-nuts/jHhXrbb1jC8
