### ISSUE TITLE
[BUG] - when using "time.FixedZone("GMT", 8*3600)" to set timezone,the bianry file would got deadlock in windows

### ISSUE THREAD

**Issue by cdsjsz** [go-co-op/gocron#421]
### Describe the bug

when using "time.FixedZone("GMT", 8*3600)" to set timezone,the bianry would got deadlock in windows.(running the code seems well,but the binary file does not)

### To Reproduce

1.Set the schedule like this:

func main() {
	s := gocron.NewScheduler(time.FixedZone("GMT", 8*3600))
	fmt.Println(time.Now())
	_, _ = s.CronWithSeconds("59 59 12 * * *").Do(start)
	s.StartBlocking()
}

2.Build the binary  for win in windows and then run.
And then you will get "fatal error: all goroutines are asleep - deadlock!"

### Version

v1.18.0

### Expected behavior
It should run without err.

### Additional context

Using "time.Local" will not get broken

**Comment by JohnRoesler** [comment]
This should be resolved by #455
