### ISSUE TITLE
[FEATURE] - Monthly Schedule

### ISSUE THREAD

**Issue by iambudi** [go-co-op/gocron#43]
I could not find a way to schedule cron job every month on specific day (Jan 5, Feb 5, March 5 so on).

`gocron.Every(1).Month().On(5).At("hh:mm")`

Is that already possible now or should be requested as a new feature?

Thanks

**Comment by iambudi** [comment]
I'm thinking doing workaround by running on Every(1).Day and check manually if the day is 5 and do the task.

**Comment by JohnRoesler** [comment]
Correct, `Month` isn't a feature today. I think it would be a good feature to add 👍  I think `Months` as well would be added for every other month ability.

**Comment by arjunmahishi** [comment]
Working on this. Should we just consider a `Month` as 30 days?
