### ISSUE TITLE
[FEATURE] - Upgrade to Go version 1.20.1

### ISSUE THREAD

**Issue by donhuvy** [go-co-op/gocron#431]
Upgrade to Go version 1.20.1

**Comment by fgm** [comment]
Can you clarify expectations here ? Is there a compatibility problem with 1.20.1 and the latest version ? The version in `go.mod` is 1.19 which is the oldest supported Go version, which seems to be the best practice to me: do not force users to upgrade faster than Go itself does.

**Comment by donhuvy** [comment]
Thank you for sharing your mindset.
