### ISSUE TITLE
[FEATURE] - Add a way to use a custom time.Duration

### ISSUE THREAD

**Issue by Depado** [go-co-op/gocron#44]
Hello :wave: 
I'd like to use a custom `time.Duration`. From what I can see in the code of this lib, the user is forced to set a unit, otherwise this error is returned:

```go
// Error declarations for gocron related errors
var (
	// ...
	ErrPeriodNotSpecified  = errors.New("unspecified job period")
	// ...
)

func (j *Job) setPeriodDuration() error {
	interval := time.Duration(j.interval)

	switch j.unit {
	case seconds:
		j.periodDuration = interval * time.Second
	case minutes:
		j.periodDuration = interval * time.Minute
	case hours:
		j.periodDuration = interval * time.Hour
	case days:
		j.periodDuration = interval * time.Hour * 24
	case weeks:
		j.periodDuration = interval * time.Hour * 24 * 7
	default:
		return ErrPeriodNotSpecified
	}
	return nil
}
```

Simply removing that default case would allow users to do something like that (since `time.Duration`'s underlying type is an `int64`):

```go
j, err := scheduler.Every(uint64(mycustomduration)).Do(...)
```

Another solution would be to add a noop unit that doesn't multiply the value of the given duration, or add a way of directly use a `time.Duration` using another method (which would avoid the `interval := time.Duration(j.interval)` cast), something like `sch.WithDuration` or `sch.EveryDuration`, I'm havint trouble finding a good name to be honest :smile: )

**Comment by dustin-decker** [comment]
The current behavior was not intuitive to me. I passed `uint64(time.Duration)` and ran into this error.

I ended up doing this (job.Interval is a `time.Duration`):
```Every(uint64(job.Interval.Seconds())).Seconds().```

**Comment by Streppel** [comment]
Geez, I'm so sorry, I failed to see this issue before. Indeed, this makes a lot of sense! I believe it could be a great change before we reach v1. @JohnRoesler @arjunmahishi keeping you updated on this one. What do you guys think?

**Comment by JohnRoesler** [comment]
I was looking into this some, and I think we could move to having the every func take a duration `Every(t time.Duration)`, which would have quite a few impacts:

- we would no longer need to track units as each jobs next run would simply be it's interval/duration. this would remove the need for all the funcs `Second()` `Hour()` etc.
- it would support setting an every interval to be anything the user desired, some examples
  - second `Every(1 * time.Second)`, day `Every(24 * time.Hour)`, week `Every(168 * time.Hour)`
- it gets a little ugly when you start getting into weeks or months, and the one ting I don't see a good way to handle would be running a job every month on a certain day, currently you can do `Every(1).Month(15)` to run a job on the 15th of each month.

**Comment by JohnRoesler** [comment]
A reasonable approach here as noted would be to add support for allowing custom durations.

@Depado could you give an example of the duration you might like to see that isn't supported today?

**Comment by Depado** [comment]
Hey @JohnRoesler 

I can't really remember the use case I was facing when opening this issue. I think I already had a `time.Duration` and wanted to use that directly.

The `Every(t time.Duration)` technique you're mentioning would indeed fit that need. As you stated though, it would make things complicated when getting to days or months, so maybe a function like `EveryDuration(t time.Duration)` that would eliminate the need to specify a unit would also fit while keeping the initial behavior of `Every(1).Day()` for example.

**Comment by Depado** [comment]
Amazing, thanks! :fireworks:
