### ISSUE TITLE
[BUG] - SingletonMode() uses 100% of the CPU if app is running in the docker

### ISSUE THREAD

**Issue by Sigmanor** [go-co-op/gocron#457]
## Describe the bug

It seems that **SingletonMode()** uses 100% (or more) of the CPU if app is running in the docker. 
Or maybe I am doing something wrong? Or this is normal behaviour?

## To Reproduce

1. Create simple app
```
package main

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron"
)

func main() {
	s := gocron.NewScheduler(time.UTC)
	s.Every(10).Seconds().SingletonMode().Do(func() {
		fmt.Println("hello")
	})
	s.StartAsync()
	time.Sleep(time.Minute * 10)
}
```
2. Create _**Dockerfile**_
```
FROM golang:1.20-alpine

COPY . /home/gocron_test

WORKDIR /home/gocron_test

RUN go mod vendor
RUN go build -o gocron_test .

ENTRYPOINT [ "./gocron_test" ]
```
3. Build docker image `docker build -t gocron_test . `
4. Run container `docker run --name gocron_test -d gocron_test`

### Result

![image](https://user-images.githubusercontent.com/7986067/233068443-0bc079b5-b901-4999-881c-862782c241dc.png)

![image](https://user-images.githubusercontent.com/7986067/233068497-71ef8972-6dc6-49c5-8412-18723d8ff64d.png)

## Version

**gocron**  v1.22.3
**Go** v1.20.3
**Windows** 11 Pro 22H2 10.0.22621.1413

## Expected behavior

Expecting somethig like this:

![image](https://user-images.githubusercontent.com/7986067/233069796-8d8c1099-118a-4b65-bcaa-bd25b9316d49.png)

This is the result if I do not use the **SingletonMode()**

```
package main

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron"
)

func main() {
	s := gocron.NewScheduler(time.UTC)
	s.Every(10).Seconds().Do(func() {
		fmt.Println("hello")
	})
	s.StartAsync()
	time.Sleep(time.Minute * 10)
}
```

## Additional context
If I run the app without a docker, it works as usual

![image](https://user-images.githubusercontent.com/7986067/233073932-d414e452-0db5-498e-9e89-95b8a6f08afd.png)

**Comment by JohnRoesler** [comment]
@Sigmanor thanks for the detailed report. I am able to recreate the same with 100% cpu usage in docker with the go and dockerfile you provided.

I was misusing select statements here as the `default` statement is causing the select to loop infinitely and use all the CPU.
