### ISSUE TITLE
Tag/Release `v1.20.1` has been removed

### ISSUE THREAD

**Issue by zacharyarnaise** [go-co-op/gocron#462]
Hi,

I noticed that a previously published release `v1.20.1` has vanished. Out of curiosity, I was wondering if that was done for a specific reason or if it was a mistake.
Thanks!

**Comment by JohnRoesler** [comment]
Hi @zacharyarnaise, I meant to release it as v1.21.0 and accidentally did as v1.20.1. I thought i had removed it quickly enough that it wouldn't effect anyone. My apologies if it caused any issues for you.
