### ISSUE TITLE
[FEATURE] Allow users be aware of the error if the job failed to run

### ISSUE THREAD

**Issue by git-hulk** [go-co-op/gocron#468]
### Describe the solution you'd like

It's possible that jobs may not be run after introducing the distributed locker: https://github.com/go-co-op/gocron/blob/main/executor.go#L178, since the locker may fail to acquire the locker due to the redis timeout or crash. So I'm wondering if we should give a way to let users be aware of this.

### Describe alternatives you've considered

- Introduce the logger to print errors and allow users to set the custom logger
- Add the onError callback in the event listener

I prefer to use the latter solution and would like to implement this feature if it makes sense to you. @JohnRoesler

**Comment by JohnRoesler** [comment]
Yes I like option 2, adding an onError event listener and I would welcome a PR 👍

**Comment by git-hulk** [comment]
> Yes I like option 2, adding an onError event listener and I would welcome a PR 👍

Thanks, I will submit the PR on those days.

**Comment by git-hulk** [comment]
@JohnRoesler I saw the job has an error field: https://github.com/go-co-op/gocron/blob/019f6e1795ca3f53443231bc22b7923fa8a98974/job.go#L26, so I'm wondering if we should also use the job error to keep consistent. But need to do a minor refactor if wanna using this error field, coz the executor only knows the jobFunction instead of the job itself.

There are two ways to work around this:

1. Pass the job to the executor instead of the job function only.
2. Add an owner filed for the job function, so that we can get the job from its function.

The first solution looks more elegant but needs to change more codes. How do you think? @JohnRoesler

**Comment by JohnRoesler** [comment]
The error field on the job only pertains to errors in setting up the job. What you’re looking for here is to capture the output of the job itself and check if any of the returned elements are errors (probably have to use reflect) and then pass that error to the event error handler

**Comment by git-hulk** [comment]
@JohnRoesler ic, thanks for your explanation.

**Comment by JohnRoesler** [comment]
Additional things to consider. What the job function actually returns, you'll have to either: 1. require the function only returns 1 item, an error. Or 2: scan the returned arguments from the `reflect Value.Call()`

```go
// Call calls the function v with the input arguments in.
// For example, if len(in) == 3, v.Call(in) represents the Go call v(in[0], in[1], in[2]).
// Call panics if v's Kind is not Func.
// It returns the output results as Values.
// As in Go, each input argument must be assignable to the
// type of the function's corresponding input parameter.
// If v is a variadic function, Call creates the variadic slice parameter
// itself, copying in the corresponding values.
func (v Value) Call(in []Value) []Value {
	v.mustBe(Func)
	v.mustBeExported()
	return v.call("Call", in)
}
```

This happens in the gocron.go file in two places:

```go
func callJobFunc(jobFunc interface{}) {
	if jobFunc != nil {
		reflect.ValueOf(jobFunc).Call([]reflect.Value{})
	}
}

func callJobFuncWithParams(jobFunc interface{}, params []interface{}) {
	f := reflect.ValueOf(jobFunc)
	if len(params) != f.Type().NumIn() {
		return
	}
	in := make([]reflect.Value, len(params))
	for k, param := range params {
		in[k] = reflect.ValueOf(param)
	}
	f.Call(in)
}
```
