### ISSUE TITLE
[FEATURE] Add support of the alias name for job

### ISSUE THREAD

**Issue by git-hulk** [go-co-op/gocron#472]
### Is your feature request related to a problem? Please describe
Currently, the executor prevents the same job from being run more than once by the function name, and need to create many different functions if we wanna create a cron job per user. So I'm wondering if it's possible to allow users to set the alias name for the job.

### Describe the solution you'd like

Add a new API like `DoWithName()` to create a job with the customized name, and use this name as the distributed locking key.

I will submit the PR if this proposal sounds good to you. @JohnRoesler

**Comment by JohnRoesler** [comment]
How about instead of a new Do method, add another Job method that can be called in the scheduler chain to ‘SetJobName’. If no name is set, default to the function name as is currently used.

**Comment by git-hulk** [comment]
Sure, thanks for your suggestion.

**Comment by JohnRoesler** [comment]
>  1. The current job name is good to know which function is running, so I'm wondering if we can add another field like job.Key or job.UniqueKey for this case?

I agree. Let's add a field to  the `Job` that is `Name string`.

> 2. The job name needs to be set before scheduling, so we need to set the job name before the Do function. And if we do this with scheduler.Do().SetJobName, the job maybe run before setting job name.

`Do()` returns the `Job` and an `error`, so it cannot be called in the scheduling chain like you have listed in the example `scheduler.Do().SetJobName`

Within the new `func (s *Scheduler) SetJobName() *Scheduler` function, make sure that you call `getCurrentJob()` to get the job like other functions do.
