### ISSUE TITLE
[BUG] - It seems that it does not support Go versions below 1.20

### ISSUE THREAD

**Issue by overstarry** [go-co-op/gocron#483]
![image](https://github.com/go-co-op/gocron/assets/23260162/abe3abab-6da7-41ee-a602-6c1324e9cca0)
It seems that it does not support Go versions below 1.20

**Comment by JohnRoesler** [comment]
@overstarry what version of go are you using? 

yes, per the go.mod 1.20 is required -> https://github.com/go-co-op/gocron/blob/main/go.mod#L3

**Comment by overstarry** [comment]
go1.18

**Comment by overstarry** [comment]
thanks 😊

**Comment by JohnRoesler** [comment]
just a note - the new distributed locker redis implementation will only work with go 1.20. not sure if that's something you're going to use.

**Comment by overstarry** [comment]
I didn't use
