### ISSUE TITLE
[BUG] - panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by artking28** [go-co-op/gocron#486]
### Describe the bug

My runtime is exiting by it, I dont know why, its only When I use ur library

My code 
```
func LaunchCronTasks(port string) error {
	s := gocron.NewScheduler(time.UTC)

	
	if _, err := s.Every(30).Seconds().StartAt(time.Now().Add(10 * time.Second)).Do(func() []error {
		var errs []error
		errs = append(errs, myFunction())
		return errs
	}); err != nil {
		return err
	}

	if s.Len() > 0 {
		s.StartAsync()
		println("\033[32m" + "[PORT" + port + "] Cron launched with success       --> " + utils.IntoString(time.Now()) + "\033[0m")
	}
	return nil
}
```

### Version

v1.18.0

![Captura de ecrã 2023-05-11, às 21 39 06](https://github.com/go-co-op/gocron/assets/78158057/7cf522f5-1ef6-4fd6-9248-30ce3420b37f)

**Comment by JohnRoesler** [comment]
@artking28 have you tried the latest version?

**Comment by artking28** [comment]
Thank u

**Comment by BranislavLazic** [comment]
@JohnRoesler 1.28.0 version - still the same problem. Basically, this is the cause: `StartAt(time.Now().Add(10 * time.Second))`
