### ISSUE TITLE
[FEATURE] - Allow users to have a time window for the execution of job

### ISSUE THREAD

**Issue by abhishek-singla-97** [go-co-op/gocron#495]
### Is your feature request related to a problem? Please describe

I had this requirement a couple of times where I had to schedule a job at a specific time but also consider the service up/down part at that time or basically, fault tolerance. For example, I wanted to run a cron job at 9 am daily. The function being called in the scheduler could take two minutes to complete. Now what if for some reason my service gets restarted at 09:01 while that function was still running? Now when the service is back up, that job would obviously not run. But I still want it to run.

### Describe the solution you'd like

I want the job to run in a specified time window at the earliest time when the service is up. For example, in the above case, though ideally I want the job to run at 9 am but if it fails to do so, I am also fine running it at any other timestamp till 9:10 am. Therefore if the system gets up at 09:05 am, even then I want the job to get triggered. Basically along with `At(i interface{})` method, I want to give another method `For(duration time.Duration)` which should take this 10 minutes or any other duration.

### Describe alternatives you've considered

For my requirements, I had to make use of a continuous for loop with the help of a ticker, that would keep checking if the current time falls between the window mentioned. If yes, then it would do the job. But having a cron scheduler could definitely avoid getting into this hassle.

### Additional context

With the solution proposed above, it is clear that there is a possibility of the job running again in the mentioned window whenever the service is restarted. For example, let's say the job starts at 09:00 and gets completed by 09:02. Now the service is restarted at 09:05. When that will happen, even then the job will get triggered since the current time lies in the window (09:00 - 09:10) and there is no way of knowing whether the previous job was completed or not. Therefore, users should be fine with the job specified in the scheduler to run again if they want to use this functionality.

**Comment by JohnRoesler** [comment]
Hi @abhishek-singla-97 

One way you could accomplish this with the current gocron functionality is to schedule the job to run at 9am, 9:05am and 9:10am and have a data store (e.g. redis) where you write that the task was completed. in each run of the job, check to see if the task was completed, and if it was, skip, otherwise attempt to complete the ask.

If you don't care if the task is executed multiple times, you could just schedule it to run at 9am, 9:05am and 9:10am and skip writing to / checking a db.

Would that work for you?

**Comment by abhishek-singla-97** [comment]
Hi @JohnRoesler

I did thought of hconfiguring multiple scheduled times but there were a couple of issues to that approach.

For the first method that you suggested, it requires an external DB which may not be always viable.

Yes it doesn't matter if my job run multiple times, meaning it is idempotent as a whole. But that doesn't mean we should daily do it, it can still be an expensive job. For example, in my case I have to first query a very heavy usage DB1 and fetch around millions of records and using that data, I have to query another DB2 and process all the 'PENDING' records in DB2 and for each of the record I have to call an external API, and based on the response I have to update the status in DB2. Now it is fine if during a once in a while event of failure, I have to query the DBs multiple times. But doing it thrice (or any other frequency) everyday isn't viable. Moreoever, hardcoding these repeated times (like 09:05, 09:10) would require some assumptions on my end and still the job can fail. For example, if I give times as 9am, 09:05am, what if my service was not up at those two timestamps. I know the chances of this happening are extremely low, but still not impossible. 

And lastly, my requirement was to execute the job as early as possible within the window. I wanted the job to execute at 9am, but since my service got failed, I would still want to execute it at 9:02 rather than 09:05 as every minute is a cost for me. That is the reason that currently I have put a for loop with a ticker for just only 10 seconds to keep checking the time and execute the jobs as early as possible.

So, these are the reasons I would like to have a `For` or a `ValidFor` method and would also like to develop the same myself.

**Comment by JohnRoesler** [comment]
I think I'm understanding your goal. I added a new function `PreviousRun` that exposes the time prior to `LastRun` on the Job. 

I believe you can accomplish your goal by using the `DoWithJobDetails` method and checking the previous and last run times to see if the job never ran, or if the job wasn't run at the previous time.

For example:

```go
package main

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron"
)

func main() {
	s := gocron.NewScheduler(time.UTC)
	atTime := time.Now().UTC().Add(5 * time.Minute)
	atTime2 := atTime.Add(5 * time.Minute)
	s.Every(1).Day().At(atTime).At(atTime2).DoWithJobDetails(func(job gocron.Job) {
		fmt.Printf("previous run: %s\nlast run: %s\nnext run: %s\ntime now: %s\n", job.PreviousRun(), job.LastRun(), job.NextRun(), time.Now().UTC())

		if job.PreviousRun().IsZero() {
			fmt.Println("this is the first run since the scheduler started")
		}

		if job.LastRun().Before(atTime) && 
			(time.Now().UTC().Truncate(time.Second) == atTime2.Truncate(time.Second)) {
			fmt.Println("we're at the second run time and the job didn't run at the" +
				"first run at time")
		}
	})

	s.StartBlocking()
}
```

**Comment by abhishek-singla-97** [comment]
@JohnRoesler 

Can you please give an example of how it would work for my requirement? I wanted my job to be scheduled at 09:00 am. And if my service gets restarted at any time within 10 minutes of that time I still want the job to still run when my service gets up.
Where should I put 09:00 am and 10 minutes in the code you provided?

**Comment by JohnRoesler** [comment]
@abhishek-singla-97 this is what I was thinking:

```go
package main

import (
	"log"
	"time"

	"github.com/go-co-op/gocron"
)

func main() {
	s := gocron.NewScheduler(time.UTC)

	_, err := s.Every(1).Day().
		At("09:00").
		At("09:05").
		At("09:10").
		DoWithJobDetails(func(job gocron.Job) {
			// the previous run will only be zero if this is the very first time the job is being run
			// since the scheduler started
			if !job.PreviousRun().IsZero() &&
				// if the previous run is not zero, and we're at minute 5 or 10, then it means the 
				// job did run at minute 0 or 5, so we don't want to run again. go ahead and return
				// when you're inside the job's run LastRun() ~= time.Now()
				( job.LastRun().Minute() == 5 || job.LastRun().Minute() == 10 ) {
				return
			}
			// we'll get here if the previous run IsZero, or we're in the minute 0 run.
			// run your regular logic here
		})
	if err != nil {
		log.Fatalf("failed to add job: %s", err)
	}
	s.StartBlocking()
}
```
