### ISSUE TITLE
[BUG] - Lock service is not working

### ISSUE THREAD

**Issue by ldegaetano** [go-co-op/gocron#50]
Hi every one, i was checking that the feature for preventing run a task twice using lock service is not working at all. In the function   `func (s *Scheduler) run(job *Job) error`  at line 180, when call to `locker.Lock(key)`  the response is ignored, so if `lock()`  return false the job can be executed.

```
func (s *Scheduler) run(job *Job) error {
	if job.lock {
		if locker == nil {
			return fmt.Errorf("trying to lock %s with nil locker", job.jobFunc)
		}
		key := getFunctionKey(job.jobFunc)

		locker.Lock(key)
		defer locker.Unlock(key)
	}

	job.lastRun = s.time.Now(s.loc)
	go job.run()

	return nil
}
```

Is there a scenario I am not seeing or is it a bug?

Thanks you very  much.

**Comment by maxsuelmarinho** [comment]
It started to ignore the return of the `locker.Lock(key)` in this [pull request #151](https://github.com/jasonlvhit/gocron/pull/151/files#diff-0ab145ca0ab7d0d679361c0f6263a49aR63). 
As we can see the @Streppel's comment: 
"will change our locker signature in the future to remove errors just like Sync.Locker", which is this one:
https://golang.org/pkg/sync/#Locker

`type Locker interface {
    Lock()
    Unlock()
}`

But it indeed prevents previous Locker implementations to work properly. For instance, the [lock example using redis](https://github.com/go-co-op/gocron/blob/master/example/lock.go#L40) is not working anymore.

**Comment by Streppel** [comment]
Indeed, this is critical. @arjunmahishi do you think you can take a look at this? I'm still reviewing the log PR and fixing some stuff on our scheduler V2

**Comment by JohnRoesler** [comment]
Hey all, we have since removed the lock implementation from gocron and are recommending the jobs themselves handle locking in the event that is needed. This is in our readme now:

>  * Q: I'm running multiple pods on a distributed environment. How can I make a job not run once per pod causing duplication? 
> * A: We recommend using your own lock solution within the jobs themselves (you could use [Redis](https://redis.io/topics/distlock), for example)
