### ISSUE TITLE
[Question] - Run jobs in SingletonMode using WithDistributedLocker option

### ISSUE THREAD

**Issue by kostiamol** [go-co-op/gocron#510]
I'm running multiple pods on a distributed environment and I want to use your `WithDistributedLocker` option but my jobs are run in `SingletonMode` which will not work with a distributed locker as described [here](https://github.com/go-co-op/gocron/blob/main/scheduler.go#L1427). What could you advise as a way to handle this case?

**Comment by JohnRoesler** [comment]
@kostiamol what are the timing requirements and run duration of your job? I could advise better then.

I'd like to get singleton mode supported with the distributed cache, but it will take a bigger implementation than I have had time for.

**Comment by kostiamol** [comment]
@JohnRoesler hi, thanks for the answers)
the job is run once a day, the run duration is around several seconds

**Comment by JohnRoesler** [comment]
Then I would not use SingletonMode at all. As the docs mention, https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.SingletonMode it's really only needed if your job sometimes runs longer than the interval. Say you are running every 1s and most of the time the jobs takes 100ms but sometimes takes 2s, singletonmode prevents it from running until the previous run completed.
