### ISSUE TITLE
[FEATURE] - Supporting pause of execution 

### ISSUE THREAD

**Issue by mcbenjemaa** [go-co-op/gocron#516]
### Is your feature request related to a problem? Please describe

I want to set a flag in my app to say that I want to pause the upcoming jobs.
when this flag become false, it will resume running new jobs. 

### Describe the solution you'd like

I need a way of pausing the scheduler or the execution.

**Comment by JohnRoesler** [comment]
@mcbenjemaa you’re looking for a global pause of all jobs, right?
