### ISSUE TITLE
[FEATURE] - at the beginning of interval

### ISSUE THREAD

**Issue by baronets-turk** [go-co-op/gocron#519]
### Is your feature request related to a problem? Please describe

Make options to run tasks at the beginning of the interval, for example at the beginning of day/ hour/minute
### Describe the solution you'd like
	s.Every(1).Hour().AtTheBeginning().Do()
	s.Every(1).Minute().AtTheBeginning().Do()
	s.Every(1).Day().AtTheBeginning().Do()

### Additional context

Now only every day can be specified by .At("00:00")

**Comment by JohnRoesler** [comment]
hi @baronets-turk 

This can currently be accomplished in two ways.

1. using `StartAt`.

    ```go
    s := gocron.NewScheduler(time.UTC)

    t := time.Now().UTC().Truncate(time.Minute)
    s.Every(1).Minute().StartAt(t).Do()

    t2 := time.Now().UTC().Truncate(time.Hour)
    s.Every(1).Hour().StartAt(t2).Do()


    t3 := time.Now()
    t4 := time.Date(t3.Year(), t3.Month(), t3.Day(), 0, 0, 0, 0, time.UTC)
    s.Every(1).Day().StartAt(t4).Do()
    ```

2. using `Cron` (i like https://crontab.guru/ for making sure i have the cron right)

    ```go
    s := gocron.NewScheduler(time.UTC)
    s.Cron("* * * * *").Do() // at every minute
    s.Cron("0 * * * *").Do() // at every hour minute 0
    s.Cron("0 0 * * *").Do() // at every day
    ```
