### ISSUE TITLE
[FEATURE] Is there a way to dynamically add all public methods in a package

### ISSUE THREAD

**Issue by iakirago** [go-co-op/gocron#522]
In package tasks, there has some public function,

```
func A(){
}

func B(){
}

func C(){
}
```

In main file, is there a way to dynamically add all public methods in tasks.

**Comment by JohnRoesler** [comment]
@iakirago not anything specific to gocron. I'm not sure if you could do something with reflect, but I am not familiar with a way to do what you're suggesting.
