### ISSUE TITLE
[FEATURE] - Give jobs a unique ID

### ISSUE THREAD

**Issue by JohnRoesler** [go-co-op/gocron#526]
### Is your feature request related to a problem? Please describe

To better support uniqueness, give jobs a UUID rather than relying on the runtime function name (as this can be duplicated in certain cases, e.g. loops)

### Describe the solution you'd like

- Job struct has a UUID. Prefer a package that supports UUID v4 with a method that returns only a UUID and no error.
- For distributed locking, the default should be to lock based on the user provided name, and then fallback to UUID.
- Expose the job ID to the end user and provide a method to `RemoveByID(id UUID)`
- Store jobs on the scheduler in a map instead of a slice

**Comment by mikayzo** [comment]
By having UUID you could store jobs in a map instead of a list and removal would be much faster. In our case we have 80k jobs which are currently being cleaned up using tags. This iteration process is waaaay too long.
