### ISSUE TITLE
[BUG] - Updating an existing job with a single parameter of `gocron.Job` unexpectedly fails

### ISSUE THREAD

**Issue by marcoferrer** [go-co-op/gocron#528]
### Describe the bug

Updating an existing job whose function takes a single argument of `gocron.Job` results in an error due to parameter length mismatch

### To Reproduce
```go
        // Step 1
        // schedule a job. this will complete as expected with no error
	job, _ := c.jobScheduler.
		Name("test").
		Tag("test").
		Every(1 * time.Minute).
		DoWithJobDetails(
			func(job gocron.Job) {
				print(job.NextRun().String())
			},
		)
	// Step 2
	// update that job with a new interval.
	_, err := c.jobScheduler.Job(job).Every(5 *time.Minute).Update()
	println(err.Error())
        
```

In step 1, `DoJobWithDetails` ends up calling `job.parametersLen = len(params)` and results in the value being 0
But in step 2, `Update` calls `s.DoWithJobDetails(job.function, job.parameters...)`. And since the job was previously initialized, it includes the "job" parameter in its list.

Links to the related code
https://github.com/go-co-op/gocron/blob/76f5162037f84e4642ab6fc90b13893bc6fac312/scheduler.go#L1300-L1302

https://github.com/go-co-op/gocron/blob/76f5162037f84e4642ab6fc90b13893bc6fac312/scheduler.go#L987-L987

### Version

v1.30.1

### Expected behavior

Updating a job whose function accepts a single param of `gocron.Job` does not produce an error

**Comment by JohnRoesler** [comment]
closed by #532
