### ISSUE TITLE
[FEATURE] - Maximum concurrent jobs

### ISSUE THREAD

**Issue by dustin-decker** [go-co-op/gocron#53]
### Is your feature request related to a problem? Please describe

When running resource intensive jobs, it may be desirable to limit how many are executed at once.

### Describe the solution you'd like

I would like to be able to configure maximum running jobs.

### Describe alternatives you've considered

I can probably do a hacky implementation of this with the Locker feature.

**Comment by Streppel** [comment]
This is interesting. How should we approach the situation where the time to run a job has come but the threshold doesn't allow it to run? We could evolve this thought to something like a queue-delivery system for workers allowing up to N concurrent jobs.

**Comment by dustin-decker** [comment]
I think setting the maximum concurrency value would have to imply a best-effort attempt at job scheduling. If the limit is hit, jobs would have to wait on a channel for the next available worker.

**Comment by Algalish** [comment]
@Streppel 
I wanted a cron firing every 10 minutes, but not counting from when cron is loaded but from the real time : like 10:00 10:10 10:20.
The only solution that I thought of was to  setup daily crons for all those time intervals: 0:00 0:10 and so on. So total of 144 open jobs to the same function.

And that resulted in crash for me today. Pretty sure that this is because of the amount of jobs.

```
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 44934 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x175fdd5aee8)
        /usr/local/go/src/reflect/value.go:1877 +0x166
github.com/go-co-op/gocron.callJobFuncWithParams(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x175fe0375a8, 0x40fd526000000000, 0x0, 0x0)
       /projects/src/src/github.com/go-co-op/gocron/gocron.go:53 +0xc5
github.com/go-co-op/gocron.(*Job).run(0xc0000dc540)
        /projects/src/src/github.com/go-co-op/gocron/job.go:52 +0x13b
created by github.com/go-co-op/gocron.(*Scheduler).run
        /projects/src/src/github.com/go-co-op/gocron/scheduler.go:290 +0x3f
```

**Comment by JohnRoesler** [comment]
@Algalish we'll take a look at that issue you uncovered.

In the meantime, are you able to schedule a job every 10 minutes starting on the nearest 10 min time and avoid scheduling 144 jobs?

`s.Every(10).Minutes().StartAt(time now rounded to next 10 min time).Do(task)`

**Comment by Algalish** [comment]
@JohnRoesler  Thank you , this is exactly what I wanted! And just wanted to add that the above crash happened 2 times, 3am for me and it was GMT+3 so its midnight GMT time. hope that helps you find the crash.

**Comment by Algalish** [comment]
@JohnRoesler 

some more information, maybe it will help you too. so this happened the third time at midnight GMT and this time I had half the amount of timers active. (every 20 minutes)

here is the code that I used
```
cronScheduler = gocron.NewScheduler(time.UTC)
	for h := 0; h < 24; h++ {
		for m := 0; m < 60; m += 20 {
			timeString := fmt.Sprint(h) + ":" + fmt.Sprint(m)
			cronScheduler.Every(1).Day().At(timeString).Do(getModDetails)
			log.Println(timeString)
		}
	}
```
