### ISSUE TITLE
[FEATURE] - Ability to terminate remaining jobs when having a special output

### ISSUE THREAD

**Issue by ErfanMomeniii** [go-co-op/gocron#534]
### Is your feature request related to a problem? Please describe
We use go cron to call functions at specific time intervals as jobs. However, we want to have better control over these jobs. For instance, if any of these jobs produce some special output like an error, we want to stop running the remaining jobs.
### Describe the solution you'd like
The solution is creating methods like `StopOn(output interface{})` for the scheduler. These methods terminate all jobs and prevent further execution if the function returns an invalid output.

### Describe alternatives you've considered
We can handle this situation by using panic within the function, but it is not considered a good solution.

**Comment by JohnRoesler** [comment]
Hi @ErfanMomeniii 

Could make a solution using the https://pkg.go.dev/github.com/go-co-op/gocron#WhenJobReturnsError event listener? 

For example:

```go
package main

import (
	"errors"
	"fmt"
	"log"
	"time"

	"github.com/go-co-op/gocron"
)

var MyError = fmt.Errorf("bad")

const jobOne = "job_1"

func main() {

	s := gocron.NewScheduler(time.UTC)
	_, err := s.Every("1s").Name(jobOne).Tag(jobOne).Do(func() error {
		log.Println("job running and returning and error")
		return MyError
	})
	if err != nil {
		log.Fatalf("failed to setup job: %s", err)
	}

	errHandleCh := make(chan string)

	s.RegisterEventListeners(
		gocron.WhenJobReturnsError(func(jobName string, err error) {
			log.Println("error return event listener running")
			if jobName == jobOne && errors.Is(err, MyError) {
				errHandleCh <- jobName
			}
		}),
	)
	s.StartAsync()

	for resp := range errHandleCh {
		log.Println("removing job")
		if resp != jobOne {
			continue
		}
		err := s.RemoveByTag(jobOne)
		if err != nil {
			log.Fatalf("failed to remove job: %v", err)
		}
		break
	}

	log.Println("no more runs of the job will occur")
	time.Sleep(2 * time.Second)
	log.Println("done")
}
```

**Comment by ErfanMomeniii** [comment]
Hi @JohnRoesler, Thank you for your help. It works for me.

**Comment by JohnRoesler** [comment]
Great!
