### ISSUE TITLE
[QUESTION/FEATURE] - Combine Singleton and RescheduleMode

### ISSUE THREAD

**Issue by haroldbouley** [go-co-op/gocron#537]
Hello,

It might already exist but after browsing every function of the library I did not manage to find what I was looking for. I also went through the issues but did not find anything like it. I feel like my use case is very common so I am tempted to think that I am missing something obvious.

I'm not entirely sure about the terminology but by "job" I mean "the function that will be called periodically by the scheduler" and not "a specific instance of execution of the function that is called by the scheduler".

I would like to limit how many concurrent instances of a specific job are running at the same time within a single Scheduler.
Basically, if I have 3 different jobs J1,J2,J3 executed by a Scheduler, I would like that 2 instances of J1 are never executed at the same time, but J1 being executed at the same time as J2 is fine. Also, since I have no guarantee on how much time those jobs will take, I would like to be able to use the RescheduleMode mode so they don't stack up.
Basically, I would like to use something like scheduler.SetMaxConcurrentJobs(1, RescheduleMode) but for each Job type instead of the whole scheduler.

I have not looked at what's inside the functions in depth, but I would guess that would translate to "I would like to have a lock per job, instead of a lock per scheduler".

I guess I can work around it by having an instance of Scheduler by job I want to run. I would rather not to (I feel that it would probably make "graceful exit" code more complex on my side), so I first wanted to make sure it is not something that can be done with the current version (or something that happens to be scheduled -my apologies for the bad pun- in the near future)

Thanks a lot for your time! And sorry if I missed something obvious.

**Comment by JohnRoesler** [comment]
Hi @haroldbouley - I appreciate the tone of your post 😄 

You summed it up quite well. The feature you desire doesn't currently exist, except via the method of using a scheduler per job.

I don't think the logic would be too wildly complicated to implement per job concurrent limitations, but not something I had been planning to do. Doesn't mean it can't happen 😉

**Comment by haroldbouley** [comment]
I totally understand!
Thank you for your (very quick!) reply :)
