### ISSUE TITLE
[BUG] - Distributed locker and singleton mode can't work together

### ISSUE THREAD

**Issue by tseman1206** [go-co-op/gocron#538]
### Distributed locker and singleton mode can't work together

When SingletonMode enabled, distributed locker can't work.

**Comment by JohnRoesler** [comment]
Correct - as noted in the documentation this is not supported  https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.WithDistributedLocker

> NOTE - the Locker will NOT lock jobs using the singleton options: SingletonMode, or SingletonModeAll
