### ISSUE TITLE
[BUG] - error since 1.32.0 (`cannot convert i (variable of type uuid.UUID) to type int`)

### ISSUE THREAD

**Issue by the-hotmann** [go-co-op/gocron#543]
### Version

1.32.0

### Expected behavior

Should not break, if following semver.

### Additional context

This is my code:

```
for i, job := range jobs {

	tags := job.Tags()
	var jobID string
	if len(tags) > 0 {
		jobID = tags[0]
	} else {
		// Handle the case where Tags() is empty (no ID available)
		jobID = "Unknown ID"
	}

	runningJobs[i] = RunningCronJob{
		ID:        jobID,
		NextRun:   job.NextRun(),
		IsRunning: job.IsRunning(),
		LastRun:   job.LastRun(),
		Err:       job.Error(),
	}
}
```

It complains about:

`cannot convert i (variable of type uuid.UUID) to type int`

But it worked just fine before. The line in question is:

`runningJobs[i] = RunningCronJob{`

Thanks in advance!

**Comment by the-hotmann** [comment]
I worked around this problem by fixing `github.com/go-co-op/gocron` to version `v1.31.2` like this:

`go get github.com/go-co-op/gocron@v1.31.2`

**Comment by JohnRoesler** [comment]
Hi @the-hotmann 

Ah, I see that the change from Jobs[] returning a slice to returning a map does break some use cases. My apologies!

**Comment by JohnRoesler** [comment]
[v1.32.1](https://github.com/go-co-op/gocron/releases/tag/v1.32.1) has a fix for this

**Comment by the-hotmann** [comment]
Thanks for the swift fix! :)
Can confirm - it is working.

**Comment by JohnRoesler** [comment]
Thanks for reporting and confirming the fix!
