### ISSUE TITLE
[BUG] - Please add descriptive title

### ISSUE THREAD

**Issue by idomic** [go-co-op/gocron#547]
### Describe the bug
Having a docker container working fine with go-cron but on the actual machine via kubernetes it's failing.
I'm running first the `--help` cmd inside docker which seems fine:
<img width="427" alt="Screen Shot 2023-08-21 at 5 30 53 PM" src="https://github.com/go-co-op/gocron/assets/11596985/0cd485c9-e675-4b5e-996e-0175e5b09243">

But then in the kub container, this is the output:
<img width="598" alt="Screen Shot 2023-08-21 at 5 30 59 PM" src="https://github.com/go-co-op/gocron/assets/11596985/da374df6-4d1b-4735-90b8-c5f188a9c43c">

### To Reproduce
I basically tried running [this image](https://github.com/eeshugerman/postgres-backup-s3) locally and on a linux machine.

1. A
1. B
1. C

**Comment by JohnRoesler** [comment]
I believe you have the wrong repository. From the repo you linked: 
- https://github.com/search?q=repo%3Aeeshugerman%2Fpostgres-backup-s3%20go-cron&type=code
- https://github.com/ivoronin/go-cron
