### ISSUE TITLE
[BUG] - Panic on malformed time is inscrutable.

### ISSUE THREAD

**Issue by flowchartsman** [go-co-op/gocron#55]
### Describe the bug

The library panics if a time is malformed. Specifically in this case if the user forgets a preceeding zero, which I feel is probably a relatively easy mistake to make. I beat my head against the wall for an hour or so on this one before intuition lead me to try putting a zero in front of it.

### To Reproduce
Minimal pathological example based on docs.

```go
package main

import (
        "fmt"
        "time"

        "github.com/go-co-op/gocron"
)

func task() {
        fmt.Println("I am running task.")
}

func taskWithParams(a int, b string) {
        fmt.Println(a, b)
}

func main() {
        // defines a new scheduler that schedules and runs jobs
        s1 := gocron.NewScheduler(time.UTC)

        // Do jobs with params
        s1.Every(1).Day().At("1:00").StartImmediately().Do(taskWithParams, 1, "hello")

        s1.StartBlocking()
}
```

Running this results in the following:

```
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 5 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/me/opt/go/src/reflect/value.go:1872 +0x183
github.com/go-co-op/gocron.callJobFuncWithParams(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/me/go/src/github.com/go-co-op/gocron/gocron.go:53 +0xc5
github.com/go-co-op/gocron.(*Job).run(0xc0000c4000)
        /Users/me/go/src/github.com/go-co-op/gocron/job.go:43 +0xd4
created by github.com/go-co-op/gocron.(*Scheduler).run
        /Users/me/go/src/github.com/go-co-op/gocron/scheduler.go:185 +0x167
```

Not particularly descriptive. :(

1. `go build`
1. run the above

### Version

25952fd63f85ccebffad02af43df88621a0982b8

### Expected behavior

You should find a way to present a meaningful error message to the user here, even if you DO have to panic.

**Comment by JohnRoesler** [comment]
Looks like it comes down to bad examples by us not showing error checking when creating the schedule. It's erroring when the `At()` func is called and so the job is nil which is causing the panic.

If you do this, it will fatal out with an error:

```
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/go-co-op/gocron"
)

func taskWithParams(a int, b string) {
	fmt.Println(a, b)
}

func main() {
	// defines a new scheduler that schedules and runs jobs
	s1 := gocron.NewScheduler(time.UTC)

	// Do jobs with params
	_, err := s1.Every(1).Day().At("1:00").StartImmediately().Do(taskWithParams, 1, "hello")
	if err != nil {
		log.Fatalf("error creating schedule: %v", err)
	}

	s1.StartBlocking()
}
```

We should probably have `At` just take a time rather than parsing a string to time, let the user do that and handle the error and our func would be safer then.
