### ISSUE TITLE
gocron v2!

### ISSUE THREAD

**Issue by JohnRoesler** [go-co-op/gocron#576]
Hello there! I am in the midst of starting a v2 for the project! The main focuses are:

- no more sharing our resources across goroutines and therefore no mutexes!
- redesigning the scheduler to be an interface (to allow for easier testing by users)
- the new job definitions will remove all the potential issues of pairing incompatible types / features together and focus on a complete definition of configuration needed for that particular type of job
- keeping feature parity close to v1 (although might be a few minor losses of un-tenable features)

If you have any input / feedback, do please share it! If you’d like to get a feel for how things are looking, check out the branch https://github.com/go-co-op/gocron/tree/v2-wip

Issues that will be addressed in v2 design:
- https://github.com/go-co-op/gocron/issues/568

**Comment by husam-e** [comment]
At the risk of scope creep 😅:

1. What are your thoughts on "abstracting" all usages of `time` libraries to something like the `TimeWrapper`? To facilitate more comprehensive time-related testing in a deterministic way, without actually relying on real time.
Relates to https://github.com/go-co-op/gocron/discussions/377 
1. Maybe a way to define a minimum delay between iterations, to give resources some breathing room when they occasionally take longer than expected, in case they are overwhelmed. Relates to https://github.com/go-co-op/gocron/discussions/564#discussioncomment-7050846

**Comment by JohnRoesler** [comment]
1. Yes, I didn’t list it, but that’s already in the code I’ve written so far. I have https://github.com/jonboulle/clockwork for now, but I’m open to other options if there is a better time mocking package!
2. I think this would fall under a feature request post initial release. I should be easier to add features in the new design.

**Comment by husam-e** [comment]
Sweet, thanks! 

I'll check out that `clockwork` library. I'm curious if it handles tickers properly and triggering functions dependent on it the right number of times as the time is manually advanced. 

And for 2), that makes sense, it is more of a new feature.

**Comment by husam-e** [comment]
Another thing that would be really helpful is if we can achieve the equivalent of `SetMaxConcurrentJobs(1, gocron.RescheduleMode)` for each job on a scheduler, instead of across all jobs on the scheduler. Essentially like if `SingletonMode` didn't queue up jobs and acted more like `RescheduleMode` instead of `WaitMode`.

**Comment by JohnRoesler** [comment]
Early prerelease 😄 https://github.com/go-co-op/gocron/releases/tag/v2.0.0-alpha-1

**Comment by husam-e** [comment]
@JohnRoesler skimming the Go docs for V2 alpha-1, I noticed that the function to set a custom clock is called `WithFakeClock`, but in practice if I use it I would always provide some clock to that func, and just ensure it's a fake impl in tests, and a real one in production code (via dependency injection typically). So just naming it `WithClock` seems more appropriate.

Separate minor naming nit for one of the errors: maybe something like `ErrDurationJobNonPositive` instead of `ErrDurationJobZero`, since it covers negative durations as well? I see other similar errors, so we'd prob want to be consistent one way or the other.

**Comment by JohnRoesler** [comment]
Thanks @husam-e - I really appreciate the input! 

Regarding the error names - your highlighting of the names made me realize there was no reason to even have those errors. All the places I was checking and returning them I've replaced with uints.

**Comment by husam-e** [comment]
Thanks for collecting input and feedback! 

A thought as I explore the `DurationRandomJob` functionality. I can see a use case for this to essentially operate on some cadence but with some jitter. For that use case, it seems like it could be more ergonomic to accept an interval + a jitter duration, that then gets translated to a min/max duration (if I'm understanding the way minDuration and maxDuration work for `DurationRandomJob`).

Rationale: I could specify cadence and jitter in some config, and pass it directly to the Scheduler, as opposed to have to translate it to a min and max duration before passing on to the Scheduler. This `DurationJitterJob` (for example) could potentially just translate to a `DurationRandomJob` internally, but the exposed interface would allow specifying interval + jitter.

Lmk wyt and if I'm misunderstanding `DurationRandomJob`. Ultimately what I'm suggesting is an additional API for functionality that I think already exists.

**Comment by JohnRoesler** [comment]
@husam-e so the only difference really is the terms, if I'm understanding rightly? Some examples:

min = 1s, max = 1500ms is going to select a random value between 1 & 1.5 seconds.

If we're thinking in terms of a jitter. That'd be saying send every 1 second, with, let's say a 500ms jitter? Which would then translate to min =1s, max=1500ms?

**Comment by husam-e** [comment]
Actually, that's a good way to think about it that is pretty easy to do with the current API.

I was thinking of the baseline duration falling in the middle, so:
```
min = baselineDuration - jitter/2
max = baselineDuration + jitter/2
```

which is a bit more calculation, hence the thought. But if we just treat `min = baselineDuration`, it becomes pretty trivial :) 

I guess the main benefit of having baseline in the middle is that the avg cadence should come out to ~the baseline duration. By treating jitter as an addition, the number of repetitions is always going to be fewer.

But yes, it's a minor API thing on naming/behavior - as I write the code, it's not too bad to do `- jitter/2` and `+ jitter/2` either :).
