### ISSUE TITLE
[BUG] - every monday doesn't work

### ISSUE THREAD

**Issue by forstef** [go-co-op/gocron#577]
### Describe the bug

scheduler.Every(1).Monday().At("09:15").Do(func(){})
This suppose to call func(){} at 09:15 every Monday, but doesn't work.

### To Reproduce

1. A
1. B
1. C

### Version

Yes

**Comment by JohnRoesler** [comment]
Need to set .Week()

**Comment by yrcs** [comment]
> Need to set .Week()

If set .Every(2).Weeks().Monday().At("10:00") or .Every(2).Weeks().Monday().Tuesday().At("10:00"), then the NextRun() method returns the next week's execution time, not the expected next two weeks' execution time.
