### ISSUE TITLE
[FEATURE] - Is there a plan to support standard Crontab expressions

### ISSUE THREAD

**Issue by GuanchuShen** [go-co-op/gocron#579]
Is there a plan to support standard Crontab expressions or enhance existing features, such as allowing 'month' to support values from 1 to 31?

**Comment by GuanchuShen** [comment]
Upon reading the source code, I found that currently only days 1 through 28 are allowed for monthly schedules are supported.

**Comment by JohnRoesler** [comment]
Hi @GuanchuShen you can directly use Crontab expressions with the `Cron` and `CronWithSeconds` methods. 

For the monthly schedules, currently only the days that exist in every month are allowed. I can see how allowing more days would be better and just skipping the day if it doesn't exist. 

You can also use the negative values to select the day of month counting from the end. For example, `-1` would be the last day of the month, so a different date each month, but the last day.

Docs: https://pkg.go.dev/github.com/go-co-op/gocron#Scheduler.Month

**Comment by GuanchuShen** [comment]
Thanks for your response. It seems whether it's Cron or MonthLastDay also only support 1-28 days, according to my understanding, if I specify -1, my expected execution time is 10.31 days, but the actual execution time is 10.28 days. Is my understanding correct？
[MonthLastDay](https://github.com/go-co-op/gocron/blob/e287edfdcd6011808bff6999b5518264ec0dabb9/scheduler.go#L1194C3-L1194C3)

**Comment by JohnRoesler** [comment]
@GuanchuShen 

Here, using Months and -1 I can run on 10/31/2023

```golang
package main

import (
	"log"
	"time"

	"github.com/go-co-op/gocron"
)

func main() {
	s := gocron.NewScheduler(time.Local)
	j, err := s.Every(1).Months(-1).Do(func() {})
	if err != nil {
		log.Fatal(err)
	}
	s.StartAsync()
	log.Printf("nextRun: %s\n", j.NextRun())
	s.Stop()
}
```

Or you can use `MonthLastDay` which is just a wrapper around `Months(-1)`. it passes -1 for you or it subtracts -1 from whatever you pass. https://github.com/go-co-op/gocron/blob/main/scheduler.go#L1191 and https://github.com/go-co-op/gocron/blob/main/scheduler.go#L1198

```golang
package main

import (
	"log"
	"time"

	"github.com/go-co-op/gocron"
)

func main() {
	s := gocron.NewScheduler(time.Local)
	j, err := s.Every(1).MonthLastDay().Do(func() {})
	if err != nil {
		log.Fatal(err)
	}
	s.StartAsync()
	log.Printf("nextRun: %s\n", j.NextRun())
	s.Stop()
}
```

**Comment by GuanchuShen** [comment]
@JohnRoesler 
Thank you for your reply. It has solved my problem and has been very helpful to me!
