### ISSUE TITLE
scheduleNextRun when the job create after schedule started

### ISSUE THREAD

**Issue by Chenghu-w** [go-co-op/gocron#58]
job run immediately when I remove the job and create job again after schedule started。

expect:
scheduleNextRun when the job create after schedule started
or
add new funcion 'UpdateInterval'

testing:

```go
package main

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron"
)

var (
	lastTime time.Time
	s        *gocron.Scheduler
)

func task() {
	now := time.Now()
	fmt.Println(now.Sub(lastTime).Seconds())
	lastTime = now
	s.Remove(task)
	s.Every(3).Seconds().Do(task)
}

func main() {
	s = gocron.NewScheduler(time.UTC)
	_close := s.StartAsync()

	lastTime = time.Now()
	s.Every(3).Seconds().Do(task)

	time.AfterFunc(time.Duration(time.Second*10), func() { s.Stop() })

	<-_close
}
```

**Comment by Streppel** [comment]
@Chenghu-w thanks for reporting! this has been fixed now :) please report back here if you see anything usual

**Comment by apremalal** [comment]
@Streppel thanks for the fix. Could you release a new tag with the fix?

**Comment by Streppel** [comment]
@apremalal done!

**Comment by apremalal** [comment]
@Streppel thanks and appreciate your help
