### ISSUE TITLE
[FEATURE/QUESTION] - Possibility to execute job on shutdown

### ISSUE THREAD

**Issue by 0xERR0R** [go-co-op/gocron#580]
I skimmed over the documentation and didn't found the answer. Is it possible to execute a task/job if the scheduler will be stopped?

My use case:

I have a task which periodically writes data to the database. I want also write this data if my application will be terminated. I know, I can achieve it with another functionality (shutdown channel propagation etc). My I think it would be nice if I could use gocron functionality. Something like:

```go
s.Every("5m").OnShutdown().Do(func(){ ... })
```

alternatively a possibility to register a shutdown listener, which will be executed on scheduler shop:

```go
scheduler.RegisterShutdownListener(func(){ ... })
```

**Comment by JohnRoesler** [comment]
hey @0xERR0R 

This isn't exactly how you're describing solving it, but you could grab the job's context, and then create a goroutine that listens for cancellation (`<-j.ctx.Done()`) and runs your shutdown function.

https://pkg.go.dev/github.com/go-co-op/gocron#Job.Context
