### ISSUE TITLE
[FEATURE] - From Datetime string

### ISSUE THREAD

**Issue by MrWildanMD** [go-co-op/gocron#595]
### Is your feature request related to a problem? Please describe

Well actually the problem is, i want to parse Datetime string as the schedule

### Describe the solution you'd like

Maybe something like this
```
// Set the time zone to GMT+7
location := time.FixedZone("Asia/Jakarta", 7*60*60)

// Create a new cron job
s := gocron.NewScheduler(location)

mockDateTime := "2023-10-21 06:00"
// Will start 30 min after 06:00 at 2023-10-21
s.Every("30m").ParseDateTimeString(mockDateTime).Do(func() {...})
s.StartAsync()
```

**Comment by JohnRoesler** [comment]
You can parse the time with the go time package time.Parse and then use gocron.StartAt.

**Comment by MrWildanMD** [comment]
Oh sorry i forget to close this issue...sorry for logical error..seems need more sleep *lol
solved with
```go
// Check if current datetime match if yes then execute UpdateDB()
s.Cron("0 30 * * * *").Do(func() { if time.Now == result.dateTime {
UpdateDB()
} })
```
