### ISSUE TITLE
v1 time mocking

### ISSUE THREAD

**Issue by JohnRoesler** [go-co-op/gocron#598]
@JohnRoesler Actually, after some debugging and digging in the `go-cron` source code I have finally managed to make that example work by simply avoiding to treat the first iteration as a special one (the `firstTime` variable):

```golang
package main

import (
	"log"
	"time"

	"github.com/go-co-op/gocron"
)

type myCustomTime struct {
	now *time.Time
}

var _ gocron.TimeWrapper = (*myCustomTime)(nil)

func (m myCustomTime) Now(_ *time.Location) time.Time {
	return *m.now
}

func (m myCustomTime) Sleep(_ time.Duration) {
	time.Sleep(time.Second)
	return
}

func (m myCustomTime) Unix(sec int64, nsec int64) time.Time {
	panic("implement me")
}

func main() {
	now := time.Now()
	mct := myCustomTime{
		now: &now,
	}

	s := gocron.NewScheduler(time.UTC)
	s.CustomTime(mct)
	s.CustomTimer(func(d time.Duration, f func()) *time.Timer {
		now = now.Add(time.Minute * 10)
		d = time.Second
		return time.AfterFunc(d, f)
	})

	_, err := s.Every(10).Minutes().Do(func() {
		log.Printf("hello: fake time is %s", now.String())
	})
	if err != nil {
		log.Println(err)
	}

	s.StartAsync()

	time.Sleep(10 * time.Second)
	s.Stop()
}
```

The reason is in the call to the job [`setTimer`](https://github.com/go-co-op/gocron/blob/cda6e1ca8b6d1487c8ac9b5804fc6868833041a9/scheduler.go#L625C1-L641C1):

```golang
	job.setTimer(s.timer(nr, func() {
		if !next.dateTime.IsZero() {
			for {
				n := s.now().UnixNano() - next.dateTime.UnixNano()
				if n >= 0 {
					break
				}
				select {
				case <-s.executor.ctx.Done():
				case <-time.After(time.Duration(n)):
				}
			}
		}
		s.runContinuous(job)
	}))
}
```

The custom timer function is called for each job execution and the difference between the current time (mocked) and the time of the next scheduled execution should always be a **positive number** in order to exit from loop and perform the re-scheduling.
Avoiding to add the job interval duration to the mocked current time for the first time, always leads to a **negative number** which, in turn causes the `time.After` call to **immediately** exit.

About the last point, it's still not clear to me the need to wait for a "negative time duration", since by design of Golang `time` package, is a no-op.

_Originally posted by @wandering-tales in https://github.com/go-co-op/gocron/discussions/377#discussioncomment-7359096_

**Comment by JohnRoesler** [comment]
@wandering-tales I converted this to an issue as it's definitely not working as one would expect.

If you're up for playing around with the prerelease of v2 i just pushed, it's using a nice library for controlling time in testing, which i *hope* alleviates these issues.

**Comment by wandering-tales** [comment]
> @wandering-tales I converted this to an issue as it's definitely not working as one would expect.
> 
> If you're up for playing around with the prerelease of v2 i just pushed, it's using a nice library for controlling time in testing, which i _hope_ alleviates these issues.

@JohnRoesler I am going to try it out, tks! I am actually struggling (again) with mocking periodic jobs 💪🏼 .

**Comment by JohnRoesler** [comment]
@wandering-tales let me know how it goes! So far, I've found working with the library (clockwork) to be reasonable, but I haven't done anything complex. 

I also added mocks for the scheduler - but that wouldn't help with actually running the function.
