### ISSUE TITLE
[FEATURE] - Any plan to support Year field in the cron expression

### ISSUE THREAD

**Issue by Tochemey** [go-co-op/gocron#599]
### Is your feature request related to a problem? Please describe

The standard cron expression does accept year field. This for instance helps to schedule tasks to run only once.

From the code I cannot see anything that will help handle that. That means a cron expression like this `0 0 0 4 JUL ? 2014` will fail the parser because I have seen that there is validation done on the cron expression.

reference: https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm

**Comment by Tochemey** [comment]
@JohnRoesler
This is an example:
```
var cronExpressionParser = cron.NewParser(
	cron.SecondOptional | cron.Minute | cron.Hour | cron.Dom | cron.Month | cron.Dow | cron.Descriptor,
)

cronExpression := "0 0 0 4 JUL ? 2014"
spec, err := cronExpressionParser.Parse(cronExpression)
```

and this the outcome:

```
expected 5 to 6 fields, found 7: [0 0 0 4 JUL ? 2014]
```

However this `0 0 0 4 JUL ? 2014` is valid cron expression

**Comment by JohnRoesler** [comment]
Hey @Tochemey,

Couple things:
- I use https://github.com/robfig/cron for crontab support and that lib doesn't support year 
  > Although, note that the year field (optional in Quartz) is not supported.
- I don't agree with the assertion that "The standard cron expression does accept year field. " - that one particular spec you linked does include year, but it doesn't seem to be universal or standard.
  - https://crontab.guru/ notes as non-standard
  - https://www.adminschoice.com/crontab-quick-reference, https://www.ibm.com/docs/en/db2oc?topic=task-unix-cron-format don't mention year (just a few examples

What are you trying to accomplish? I imagine there are other ways to achieve it without the year field?

To answer the title question: no, no plans.
Cheers!

**Comment by Tochemey** [comment]
@JohnRoesler Thanks for the reply.

**Comment by Tochemey** [comment]
@JohnRoesler even on Wikipedia the Cron expression does accept year field. It just not required. https://en.m.wikipedia.org/w/index.php?title=Cron&action=edit&section=9
