### ISSUE TITLE
[BUG] - Handling negative time.Duration as interval param to `Every` func

### ISSUE THREAD

**Issue by husam-e** [go-co-op/gocron#600]
### Describe the bug

Not sure if this is a bug, more of a question to confirm expected behavior: currently no error is returned when a negative `time.Duration` is provided as the interval param to `Every`. Is that intentional? Should it not return an error and fail fast, similar to when providing a negative int? Not clear to me what the intended behavior is for that.

### To Reproduce

```
scheduler := gocron.NewScheduler(time.UTC)
interval := -1 * time.Second
_, err := scheduler.Every(interval).Do(func() { })
```

### Version

v1.35.2

### Expected behavior

`err` is returned non-nil, or otherwise behavior for negative Duration is documented on the `Every` function.

### Additional context

Thinking it would be helpful as input validation to get an error in this scenario to immediately recognize invalid setup, just like how negative int values are treated as errors.

**Comment by JohnRoesler** [comment]
@husam-e I agree this is a bug. it's solved in v2. If you'd like to open a PR for v1 feel free 😄
