### ISSUE TITLE
[ENHANCEMENT] - SetMaxConcurrentJobs to work with singleton jobs

### ISSUE THREAD

**Issue by hspark0582** [go-co-op/gocron#624]
### Describe the bug

Singleton jobs do not follow the limit set with `SetMaxConcurrentJobs`.

### To Reproduce

Test code:
```go
// skipping headers

func main() {
	s := gocron.NewScheduler(time.UTC)

	s.SetMaxConcurrentJobs(2, gocron.WaitMode)
	s.SingletonModeAll()

	for i := 0; i < 4; i++ {
		s.Every(time.Minute).Do(
			func() {
				logrus.Infof("Run some job")
				exec.Command("sleep", "5").Run()
			},
		)
	}

	s.StartBlocking()
}
```
(Error handling omitted for brevity)

Output shows 4 "Run some job"s immediately, ignoring `SetMaxConcurrentJobs` of 2.
When `s.SingletonModeAll()` was removed, only 2 "Run some job"s are displayed as intended.

### Version

v1.36.0

### Expected behavior

`SetMaxConcurrentJobs` also apply to singleton jobs.
The number of jobs, normal and singleton jobs combined, does not exceed the limit set with `SetMaxConcurrentJobs`.

**Comment by JohnRoesler** [comment]
hello @hspark0582, could you help me understand the expected behavior and why you would combine singleton and limit mode together?

**Comment by hspark0582** [comment]
Hello!

I was using gocron to schedule jobs that are somewhat heavy in CPU load, thus I wanted to limit the number of concurrent jobs. Also, those jobs may crash when multiple jobs run simultaneously, so I made them all singleton. Not much to say here really.

I actually have an update, just to provide a bit of my usage: I "solved" this issue with making jobs regular (not singleton) and `if job.RunCount() - job.FinishedRunCount() > 1 { return }`.

Expected behavior is, well, *my* expected behavior, so I wouldn't mind you disagreeing with me.

I don't know if this helped, so if you need more info, please ask. Thank you all for maintaining this wonderful work.

**Comment by JohnRoesler** [comment]
@hspark0582 thanks for the additional context. That makes sense. It would take some thinking about, as far as how to handle it. The current design in v1 & v2 assumes them to be mutually exclusive. v1 gives precedence to singleton mode, whereas v2 gives precedence to limit mode. 

I can see how you'd want to make sure that if you have a limit of 2, that you don't end up with the same job running twice and taking both the limit spots.

**Comment by JohnRoesler** [comment]
@hspark0582 I've updated the v2 branch and tagged a new release candidate that allows for using both max concurrent and singleton mode together.
