### ISSUE TITLE
[BUG] When date changes to before, conJob not work

### ISSUE THREAD

**Issue by zishen** [go-co-op/gocron#626]
### Describe the bug

When I used `timeCron.Every(interval).Seconds().Do()` to start my cronJob. I found if the time on my machine changed before, like using `date -s`  to set the time to an hour ago, it will not work

I found the controll code is:
```go
func (s *Scheduler) runContinuous(job *Job) {
....
	job.setTimer(s.timer(nextRun, func() {
		if !next.dateTime.IsZero() {
			for {
				n := s.now().UnixNano() - next.dateTime.UnixNano()
				if n >= 0 {
					break
				}
				s.time.Sleep(time.Duration(n))
			}
		}
		s.runContinuous(job)
	}))
}
```

### Version

all, but I test 1.19.0 and 1.36.0

### Expected behavior

The time changes do not effect conJob.

Maybe a new interface is more suitable

**Comment by JohnRoesler** [comment]
Duplicate -> https://github.com/go-co-op/gocron/issues/438#issuecomment-1521089020
