### ISSUE TITLE
What is the equivalent of `job.FinishedRunCount()` in v2?

### ISSUE THREAD

**Issue by zx8** [go-co-op/gocron#633]
In v1, I was using a helper like this to execute my jobs immediately, for testing purposes:

```go
func (e *example) runNow(f func() []error) error {
	job, err := e.scheduler.Every(1).Hour().StartImmediately().Do(f)
	if err != nil {
		return err
	}
	job.LimitRunsTo(1)
	for job.FinishedRunCount() == 0 {
		time.Sleep(100 * time.Millisecond)
	}
	return err
}
```

Is there a way to do something similar in v2, i.e. block until a job has fully completed one time?

**Comment by JohnRoesler** [comment]
Hey @zx8 

A couple thoughts:
1. You could utilize `Job.LastRun()` and check for it to be non-zero
2. You could utilize the fake clock, see [testing](https://github.com/go-co-op/gocron/blob/v2/README.md#testing) and just wait until blocked and then fast forward time to when the job would run. 

Testing is an area I'd very much like to have good support for, so if you have ideas or suggestions please share!

**Comment by zx8** [comment]
1. Hmm, I did try `Job.LastRun()` but it seemed to be set to non-zero prior to the job actually having completed (i.e. at the start of the job's execution)? I'll double-check this again tomorrow, though, as I'm not I'm not 100% sure now
2. Oooh, this is very cool! If the above doesn't work, the fake clock looks like a suitable alternative

**Comment by JohnRoesler** [comment]
```golang
package main

import (
	"fmt"
	"time"

	gc "github.com/go-co-op/gocron/v2"
)

func main() {
	scheduler, err := gc.NewScheduler(
		gc.WithLocation(time.UTC),
	)
	if err != nil {
		fmt.Printf("Failed to create scheduler: %s", err)
	}

	job, err := scheduler.NewJob(
		gc.DurationJob(
			time.Second,
		),
		gc.NewTask(func() {
			fmt.Printf("Task ran!\n")
		}),
	)

	if err != nil {
		fmt.Printf("Failed to schedule job: %s", err)
	}

	scheduler.Start()

	var lastRun time.Time
	for ; lastRun.IsZero(); lastRun, err = job.LastRun() {
	}
	fmt.Printf("job last run: %s\n", lastRun)

	err = scheduler.StopJobs()
	if err != nil {
		fmt.Printf("Failed to stop jobs: %s", err)
	}
	err = scheduler.Shutdown()
	if err != nil {
		fmt.Printf("Failed to shutdown scheduler: %s", err)
	}
}
```

Output:
```
Task ran!
job last run: 2023-12-14 16:34:39.432116 +0000 UTC
```

LastRun is set after the job is run 👍

**Comment by zx8** [comment]
Perfect, thank you!
