### ISSUE TITLE
[BUG] - Pointer to the a scheduler instance

### ISSUE THREAD

**Issue by alex-savin** [go-co-op/gocron#636]
Hey Folks,

Is there any way to use a pointer to a newly created instance of the scheduler?

I was trying to point to `gocron.Scheduler`, but it doesn't work because of the gocron.Scheduler is the interface.

Any suggestions will be appreciated

**Comment by JohnRoesler** [comment]
Hi @alex-savin 

The underlying struct is a pointer to the scheduler. So there is no need to try and reference a pointer to the interface. Just pass the gocron.Scheduler into the struct or function that you need it in.
