### ISSUE TITLE
[BUG] - Job execution fails silently on argument mismatch

### ISSUE THREAD

**Issue by tahamr83** [go-co-op/gocron#637]
### Describe the bug
If there is a mismatch in the length of the arguments the task does not (makes sense) silently, and we don't see any log as to what is wrong. 

### To Reproduce

```go
func main()
	// create a scheduler
	s, err := gocron.NewScheduler()
	if err != nil {
		// handle error
	}

	// add a job to the scheduler
	j, err := s.NewJob(
		gocron.DurationJob(
			10*time.Second,
		),
		gocron.NewTask(
			func(a string, b int) {
				fmt.Println(a, b)
			},
			"hello", // Only 1 argument provided
		),
	)
	if err != nil {
		// handle error
	}
	// each job has a unique id
	fmt.Println(j.ID())

	// start the scheduler
	s.Start()
	ctx, _ := signal.NotifyContext(context.Background(), os.Interrupt)
	<-ctx.Done()

	// when you're done, shut it down
	err = s.Shutdown()
	if err != nil {
		// handle error
	}
}

```
### Version

2.0.0

Have you tried the latest version?
No, The latest as of this writing is 2.0.1 which doesn't have the fix for this. 

### Expected behavior
There should be a log message saying that the task cannot be called. 
### Additional context
N/A

**Comment by JohnRoesler** [comment]
@tahamr83 Thanks for calling that out. This is fixed in [v2.0.2](https://github.com/go-co-op/gocron/releases/tag/v2.0.2)
