### ISSUE TITLE
[BUG] - V2 scheduler stop immediatly

### ISSUE THREAD

**Issue by benoitdm-oslandia** [go-co-op/gocron#647]
### Describe the bug

I create cron job and start the scheduler. The scheduler quit without waiting  any cron job.

### To Reproduce

```golang
	var err error = nil
	scheduler, err = gocron.NewScheduler(gocron.WithLogger(gocron.NewLogger(gocron.LogLevelDebug)))
	if err != nil {
		log.Fatalf("Unable to instanciate gocron scheduler: %v", err.Error())
	}

	retrieveConfigJob, err = scheduler.NewJob(
		gocron.CronJob(
			// standard cron tab parsing
			"1 * * * *",
			false,
		),
		gocron.NewTask(
			func() {
				// do something
			},
		),
		gocron.WithName("RetrieveConfigJob"),
	)

	if err != nil {
		log.Fatalf("Unable to instanciate job: %v", err.Error())
	}


	log.Infof("Ready to run %d jobs!", len(scheduler.Jobs()))
	for _, job := range scheduler.Jobs() {
		log.Infof("      job: %s", job.Name())
	}
	scheduler.Start()
	log.Warningln("scheduler quit!")
```

output:

```log
time="2023-12-20T12:37:17+01:00" level=info msg="Ready to run 1 jobs!"
time="2023-12-20T12:37:17+01:00" level=info msg="      job: RetrieveConfigJob"
time="2023-12-20T12:37:17+01:00" level=warning msg="scheduler quit!"
```

### Version

v2.1.0

### Expected behavior

Scheduler should wait for the job to run!

**Comment by JohnRoesler** [comment]
Hi @benoitdm-oslandia 

Can you share more code after you started the scheduler? Start is non-blocking. So, you'll need to block in some way or, yes the program will just exit without allowing the scheduler to run any jobs.

**Comment by benoitdm-oslandia** [comment]
My bad! I was believing the `Start` function was blocking. But I see you just fixed the doc! Thanks!

According to you, what is the best way to block without chan notification?

**Comment by JohnRoesler** [comment]
Lot's of options, but if you simply want to block, until you decide to interrupt the program, I'd use an empty `select {}` block.
