### ISSUE TITLE
[FEATURE] Allow setting a stopTime on jobs to run the job until that date/time is reached

### ISSUE THREAD

**Issue by 15930245014** [go-co-op/gocron#654]
The v2 jobs requires an end time. Now it only has a start time. It would be better to add the end time to the attribute configuration.

**Comment by JohnRoesler** [comment]
This is a feature request to support setting a `StopTime` on a job in addition to currently being able to set a `StartTime`?

**Comment by 15930245014** [comment]
yes,I think it's necessary

**Comment by Higan** [comment]
Hi @JohnRoesler should this `StopTime` be inclusive or exclusive?

**Comment by JohnRoesler** [comment]
Depending on how it's implemented exactly, could have both options, but could also go with something explicitly named like StopBefore

**Comment by JohnRoesler** [comment]
Similar to how the StartAt option works, this could support a Stop time job option that then provides StopAt and StopBefore. 

Or, keep it simple at just start with one, id lean towards StopAt and document clearly that it's inclusive
