### ISSUE TITLE
[BUG] - gocron: job not found

### ISSUE THREAD

**Issue by m-s-sh** [go-co-op/gocron#656]
### Describe the bug

When I add a new job (let's say j) and after that calling  j.NextRun(),  it fails unpredictable with ErrJobNotFound.

### To Reproduce

```go
func TestNextRun(t *testing.T) {
	clock := clockwork.NewFakeClock()
	sch, err := gocron.NewScheduler(gocron.WithClock(clock))
	require.NoError(t, err)
	for i := 0; i < 10; i++ {
		var c int
		j, err := sch.NewJob(
			gocron.DurationJob(time.Second),
			gocron.NewTask(func() error {
				c++
				t.Log("c", c)
				return nil
			}),
			gocron.WithName("calcJob"),
			gocron.WithSingletonMode(gocron.LimitModeReschedule),
		)
		require.NoError(t, err)
		sch.Start()
		r, err := j.NextRun()
		require.NoError(t, err, "i=%d", i)
		t.Log("nextRun", r)
	}
}
```

### Version
v2.1.2

### Expected behavior
I expect not to fail with ErrJobNotFound, when I added job few lines above.

**Comment by JohnRoesler** [comment]
@mihailstefanov thanks for reporting this! An issue with not properly waiting for the new job to be instantiated before returning. I'll have a fix up soon.
