### ISSUE TITLE
[BUG] - monthlyJob daysOfTheMonth only -1

### ISSUE THREAD

**Issue by elemhan** [go-co-op/gocron#660]
### Describe the bug

I have created a MonthlyJob and the param daysOfTheMonth is -1, the scheduling time is incorrect, current time is 2024-01-19 ，the next scheduling time is 2024-01-31 00:00:00, the next scheduling time is 2024-03-31 00:00:00, the reason is when the time is  2024-01-31 ,then the firstDayNextMonth is 2024-02-01, subtraction -1  the last day of the month is 31, when you calculate the next month, if the next month do not have 31 day, the next month will be ignored.

### Version

[v2.1.2]

### Solution

I have solved the  bug in my forked repo https://github.com/elemhan/gocron/commit/d3fbc79e381a7f21b71395629683464f88c5e3f9

but I have added some features in my forked repo，so I cannot commit mr to this repo.
In my forked repo I added  some features:
1. The job scheduling time support delay time 
2. When I defined a job, I can compute the next scheduling time when I set a lastRun time

If you think these two features is necessary, I can commit mr to this repo.

**Comment by JohnRoesler** [comment]
Feel free to open feature requests and describe 1 & 2 in more detail. If they seem like good additions, happy to accept an MR 👍
