### ISSUE TITLE
[BUG] - Lazy evaluation for schedule values

### ISSUE THREAD

**Issue by KaibutsuX** [go-co-op/gocron#673]
### Describe the bug

I'm trying to maintain an array of jobs to be executed with each entry in the array representing a name and a *Scheduler. But it seem when iterating the list of jobs, gocron expects the scheduler values to be invoked with `Do()` immediately before setting up the next Scheduler.

Is there any way to accomplish what I'm looking to do?

### To Reproduce

Code is illustrative only. Only the last entry in the []Jobs array is actually scheduled and running.

```
schedule := gocron.NewScheduler(time.Local)
for _, job := range []Jobs{
   { name: "Every 5s", schedule: scheduler.Every(5).Second(), func: func() { fmt.Printf("Every 5s\n") }},
   { name: "Every 3s", schedule: scheduler.Every(3).Second(), func: func() { fmt.Printf("Every 3s\n") }},
} {
    job.schedule.Do(job.func)
}
```

### Version

v1.37.0

### Expected behavior

I would expect to see both jobs run at each interval. I am actually only seeing the last job run.

**Comment by JohnRoesler** [comment]
Because of how the scheduler functions are chained, what's actually happening is, when you define the slice of jobs in that example above, the scheduler has the interval set to 5 and then for seconds. Then, on the next definition in the slice the scheduler has the interval set to 3.

Then when you iterate through it, it's calling Do firstly on the interval 3 seconds, and I would guess the 2nd time it's returning an error.

**Comment by KaibutsuX** [comment]
That's what I assumed. Do you know of any way I can iterate and tell the scheduler to reset or maybe get a new copy of each scheduler for each entry?

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by KaibutsuX** [comment]
I can't think of a way to pre-create a list of jobs using the `scheduler` syntax without overwriting the previous values. I need a valid `*Scheduler` in order to use that syntax, but I want to execute all of the jobs using a single schedule so then at the end I can call `schedule.StartBlocking()`

**Comment by JohnRoesler** [comment]
This isn't an issue with gocron, but more of a go design question. In order to accomplish what you want, you can use a function as a struct param, like

```go
package main

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron"
)

type Jobs struct {
	name     string
	schedule func(scheduler *gocron.Scheduler) *gocron.Scheduler
	f        func()
}

func main() {

	schedule := gocron.NewScheduler(time.Local)
	for _, job := range []Jobs{
		{
			name: "Every 5s", schedule: func(scheduler *gocron.Scheduler) *gocron.Scheduler {
				scheduler.Every(5).Second()
				return schedule
			},
			f: func() { fmt.Printf("Every 5s\n") }},
		{
			name: "Every 3s", schedule: func(scheduler *gocron.Scheduler) *gocron.Scheduler {
				scheduler.Every(3).Second()
				return schedule
			},
			f: func() { fmt.Printf("Every 3s\n") }},
	} {
		_, err := job.schedule(schedule).Do(job.f)
		if err != nil {
			return
		}
	}
	schedule.StartBlocking()
}
```

**Comment by JohnRoesler** [comment]
I'd encourage you to use v2 as I'm not maintaining v1 any longer. Equivalent code:

```go
package main

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron/v2"
)

type Jobs struct {
	name     string
	duration time.Duration
	f        func()
}

func main() {
	scheduler, err := gocron.NewScheduler()
	if err != nil {
		fmt.Println("Failed to create new scheduler")
		fmt.Print(err)
		return
	}

	jobs := []Jobs{
		{"Every 5s", time.Second * 5, func() { fmt.Printf("Every 5s\n") }},
		{"Every 3s", time.Second * 3, func() { fmt.Printf("Every 3s\n") }},
	}
	for i := range jobs {
		_, err = scheduler.NewJob(
			gocron.DurationJob(jobs[i].duration),
			gocron.NewTask(jobs[i].f),
			// if you want parity with v1, you can set the job to start immediately
			// otherwise it will wait for 3 or 5 seconds respectively
			gocron.WithStartAt(gocron.WithStartImmediately()),
		)
		if err != nil {
			// do something
		}
	}

	scheduler.Start()
	select {
	// do something here to handle stopping your app
	}
}
```
