### ISSUE TITLE
[BUG] - Cannot create job with task with variadic args 

### ISSUE THREAD

**Issue by bbompk** [go-co-op/gocron#677]
### Describe the bug

When creating a job with a task that has variadic args, the validator in the library will expect the variadic args to be "1" argument (suspect to be a slice of that type). So creating a job with a task that has function of variadic arguments will always return `ErrNewJobWrongNumberOfParameters`. 

### To Reproduce

1. Create a function that has variadic args
2. Try create a cronjob from that

```go
scheduler, _ := gocron.NewScheduler()

myfunc := func(args ...string) {
  panic("This works")
}

// will have error
job, err := scheduler.NewJob(
  gocron.CronJob("* * * * 1", false),
  gocron.NewTask(myfunc), // the validator will expect num param to be 1 (slice of string)
)

```

### Version

v2.2.1

### Expected behavior

should be able to execute task with variadic parameters.

**Comment by bbompk** [comment]
Well I guess I should use slice as an argument instead of variadic args..

**Comment by JohnRoesler** [comment]
That's an option. But may be a way to handle variadic args.

**Comment by Higan** [comment]
Hi @JohnRoesler I just created a PR https://github.com/go-co-op/gocron/pull/755 to resolve this issue.

**Comment by JohnRoesler** [comment]
Thanks @Higan 👏
