### ISSUE TITLE
[BUG] - cron expression failed to be parsed - unknown unit "d"

### ISSUE THREAD

**Issue by milahu** [go-co-op/gocron#679]
gocron v1.37.0 fails to parse the duration `@every 3d`
and instead, i have to use `@every 72h`

> `Error: gocron: cron expression failed to be parsed: failed to parse duration @every 3d: time: unknown unit "d" in duration "3d"`

gitea uses an old version of gocron to fix tests
see [go.mod](https://github.com/go-gitea/gitea/blob/403766cd81697288804fd218d68c458c6aa5b73d/go.mod#L44) and https://github.com/go-gitea/gitea/pull/27511

**Comment by JohnRoesler** [comment]
This is controlled by the underlying cron library: https://pkg.go.dev/github.com/robfig/cron#hdr-Intervals which states

> where "duration" is a string accepted by time.ParseDuration (http://golang.org/pkg/time/#ParseDuration).

And that link:

> ParseDuration parses a duration string. A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
