### ISSUE TITLE
[BUG] - Singleton jobs can fail to get rescheduled in LimitModeReschedule on any overrun due to a channel error.

### ISSUE THREAD

**Issue by kj87au** [go-co-op/gocron#683]
### Describe the bug

Singleton jobs can fail to get rescheduled due to a channel error causing the executioner to never rerun the job and raise no error.

There is a race condition in the executioner which causes a singleton job to not get re-scheduled properly.

The error is in the executioner pushing a job to the jobIDsOut channel  (executor.go  line 180)

![image](https://github.com/go-co-op/gocron/assets/35207321/a6bca340-f48f-4a4d-9f50-8046f023266a)

There seems to be an issue where there is something already in the channel, therefore it is skipping placing the job in the channel via the "default" case.

Removing the default case fixes the issue.

### To Reproduce

1. Run a overlapping gocron job in singleton format with LimitModeReschedule. Example:
```go
package main

import (
    "runtime"
    "time"
 
    gocron "github.com/go-co-op/gocron/v2"
    "go.uber.org/zap"
)

const sleepTime = 30 * time.Second

func main() {
    zlog := zap.NewExample().Sugar()

    zlog.Info("Starting")

    s, _ := gocron.NewScheduler(
        gocron.WithLocation(time.UTC),
        gocron.WithLogger(gocron.NewLogger(gocron.LogLevelDebug)),
    )

    defer func() { _ = s.Shutdown() }()

    j, err := s.NewJob(
        gocron.CronJob(
            "*/1 * * * * *",
            true,
        ),
        gocron.NewTask(
            taskToRun,
            zlog,
        ),
        gocron.WithName("Job1"),
        gocron.WithSingletonMode(gocron.LimitModeReschedule),
    )

    if err != nil {
        zlog.Errorw("Error creating job", "error", err)
    }

 

    s.Start()
    // Do something else
    var count = 0
    for {
        time.Sleep(1 * time.Second)
        nextRun, err := j.NextRun()

        if err != nil {
            zlog.Errorw("Error getting next run", "error", err)
        } else {
            // If we overrun the next run, we will raise a Fatal error
            if time.Now().After(nextRun.Add(30 * time.Second)) {
                zlog.Fatal("Overrun")
            }
        }

        count += 1
        zlog.Infow("Main Loop",
            "time", time.Now(),
            "jobs", len(s.Jobs()),
            "nextRun", nextRun,
            "count", count,
            "goroutines", runtime.NumGoroutine(),
        )
    }
}

 

func taskToRun(log *zap.SugaredLogger) {
    log.Infow(
        "Job Running",
        "time", time.Now(),
        "sleepTime", sleepTime,
    )
    time.Sleep(sleepTime)
}
```
2. Run this with the latest, fatal should be raised.
3. Comment out executor.go, line 181.
4. Rerun main, no problem

### Version

Latest Version (v2.2.4)

### Expected behaviour

Job should be re-scheduled

**Comment by cpj555** [comment]
It should be the same problem, my task will exceed the execution time, and after a while, it will not be executed

**Comment by JohnRoesler** [comment]
Would you be willing to validate the release candidate solves the issue? [v2.2.5-rc1](https://github.com/go-co-op/gocron/releases/tag/v2.2.5-rc1)

**Comment by kj87au** [comment]
@JohnRoesler Release candidate [v2.2.5-rc1](https://github.com/go-co-op/gocron/releases/tag/v2.2.5-rc1) solves the issue, great work.

**Comment by JohnRoesler** [comment]
Thank you for confirming!!
