### ISSUE TITLE
How to schedule job to run on every 2nd thursday of month at 10:10 AM using gocron v1 or v2

### ISSUE THREAD

**Issue by maddalieswar** [go-co-op/gocron#687]
How to schedule job to run on every 2nd thursday of month at 10:10 AM using gocron v1 or v2 using cron expression or predefined functions.

I tried multiple ways but it did not work.Can someone please help

**Comment by JohnRoesler** [comment]
Hi @maddalieswar 

This functionality isn't currently supported out of the box. You could accomplish this by running a weekly job on Thursdays and inside your job, check whether it is in the 2nd Thursday of the month, i.e. is the day number between 8 & 14.

Here is a playground example of the date check: https://goplay.space/#duRgcE_-SgK

Here is a full example with gocron:

```golang
package main

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron/v2"
)

func main() {
	scheduler, err := gocron.NewScheduler()
	if err != nil {
		return
	}

	scheduler.NewJob(
		gocron.WeeklyJob(
			1,
			gocron.NewWeekdays(time.Thursday),
			gocron.NewAtTimes(
				gocron.NewAtTime(10, 10, 0),
			),
		),
		gocron.NewTask(func() {
			if d := time.Now().Day(); d < 8 || d > 14 {
				fmt.Println("not the 2nd Thursday")
				return
			}
		}),
	)

	scheduler.Start()
	select {
	// do something here to handle stopping your app
	}
}

```

**Comment by maddalieswar** [comment]
HI
Thanks alot @JohnRoesler, It worked fine 
But somehow when i tried to define specific dates in cron expression, its not working.Lets say I want job to schedule on Monday if the date is in between 1-7.Job is getting triggered on every monday irrespective of given dates.

Here is the snippet i used.Any idea on this
_, _ = sch.NewJob(
		gocron.CronJob(
			"CRON_TZ=Asia/Kolkata 4 24 13 1-7 * MON",
			true,
		),
		gocron.NewTask(
			task,
			1,
		),
	)

**Comment by JohnRoesler** [comment]
Closing in favor of #689
