### ISSUE TITLE
Date Range not working using cron expression in gocron v1 v1.37.0

### ISSUE THREAD

**Issue by maddalieswar** [go-co-op/gocron#689]
when i tried to define specific dates in cron expression, scheduling is not working as expected. Let's say I want to schedule a job on Monday which exists between 1-7 dates. Job is getting triggered on every monday irrespective of given date range.

version Using : gocron v1.37.0

Here is the snippet i used.Any idea on this
_, _ = sch.NewJob(
gocron.CronJob(
"CRON_TZ=Asia/Kolkata 4 24 13 1-7 * MON",
true,
),
gocron.NewTask(
task,
1,
),
)

**Comment by JohnRoesler** [comment]
When I put that into -> https://crontab.guru/#24_13_1-7_*_MON it says
> At 13:24 on every day-of-month from 1 through 7 and on Monday.

I'm not sure that Cron can accomplish your goal.
