### ISSUE TITLE
[BUG] - switch from daylight saving time to standard time causes problem

### ISSUE THREAD

**Issue by arigon** [go-co-op/gocron#69]
### Describe the bug
I am running a job on 00:01 every day. Today was the switch from daylight saving time to standard time in Europe. The job did run one hour too early at 23:01.
Update: And I just realized the job was executed twice.

### To Reproduce

`_, err := s.Every(1).Day().At("00:01").Do(reports.RunDailyReport)`

### Version

0.3.1

### Expected behavior

It should not run at 23:01. It should only run once.

**Comment by Streppel** [comment]
Thanks for the report @arigon. Will take a look at it.

**Comment by JohnRoesler** [comment]
What time zone are you using? I'm wondering if it's set to UTC and was the same but then got off by an hour when your time changed?

**Comment by arigon** [comment]
I am using Europe/Berlin which is my time zone, otherwise it wouldn't start at 00:01 as expected. By the way, it hasn't started at 00:01 now either. I am now wondering if it will work Tuesday at 00:01.

**Comment by arigon** [comment]
Okay.. The job did just run, at 23:01.. How can I switch it back to 00:01?

**Comment by Streppel** [comment]
This is unfortunate, I'm sorry. I believe I've already found what's up and will make a commit soon. Meanwhile, can you try to restart your worker application? I know this is not ideal, but hopefully it'll work while we don't merge a fix.

**Comment by arigon** [comment]
I already restarted that container yesterday. But I will do so again.

**Comment by arigon** [comment]
after intensive research with @Streppel (thx a lot!) we found the problem is in the alpine docker image which didn't update properly from CEST to CET. I will close this :)
