### ISSUE TITLE
Is there a way to run scheduler forever?

### ISSUE THREAD

**Issue by yashh** [go-co-op/gocron#697]
The current example code 

```select {
case <-time.After(time.Minute):
}
```

Is moving on after 1 minute. Some of the issues in this tracker use `startBlocking` but I have nt found that in the code. Whats the ideal way to block scheduler forever?

Also is there a way to set the ID of the job while creation? If not we have to keep track of the IDs to job which is not a big deal.

**Comment by JohnRoesler** [comment]
Hi @yashh 

You can block for ever in Go by simply doing an empty `select{}` block.

No way to set the job ID currently. You can use job tags to achieve similar behavior.

**Comment by yashh** [comment]
thank you
