### ISSUE TITLE
[FEATURE] - Get Metrics about jobs which are in waiting queue after concurrent job limit is reached

### ISSUE THREAD

**Issue by 0x01F4** [go-co-op/gocron#708]
### Is your feature request related to a problem? Please describe

When we using `WithLimitConcurrentJobs` with `LimitModeWait` there is no way to monitor how many jobs are waiting and how long.

### Describe the solution you'd like

Maybe provide a way to get all jobs which are in waiting state and how long or count of jobs by name/tag.
I don't have strong opinions on how it should be implemented. At minimum we should be able to get number of jobs in waiting state and how long it is waiting for.

**Comment by JohnRoesler** [comment]
I think the monitor could be expanded upon to support metrics for this https://github.com/go-co-op/gocron/blob/v2/monitor.go

**Comment by 0x01F4** [comment]
If we increment the wait metrics https://github.com/go-co-op/gocron/blob/3faf525f98525af7cc2929426875d7b37f4f11ad/executor.go#L133C1-L134C1

Should we decrement it when the job starts?

**Comment by 0x01F4** [comment]
@JohnRoesler  Maybe we can added something like this.What do you think?
`func (s *scheduler) WaitingInQueue() int {
	if s.exec.limitMode != nil && s.exec.limitMode.mode == LimitModeWait {
		return len(s.exec.limitMode.in)
	}
	return 0
}`

**Comment by JohnRoesler** [comment]
@giri-vsr that seems pretty reasonable
