### ISSUE TITLE
Is Every(1).Day().At working properly?

### ISSUE THREAD

**Issue by KnBrBz** [go-co-op/gocron#71]
Wrote a simple code

```
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-co-op/gocron"
)

func daily() {
	fmt.Println("Daily ", time.Now())
}

func main() {	
	s2 := gocron.NewScheduler(time.UTC)	
	s2.Every(1).Day().At("17:40").Do(daily)	
	s2.Every(1).Day().At("17:41").Do(daily)
	
	s2.StartAsync()

	c := make(chan os.Signal, 1)
	signal.Notify(c, syscall.SIGINT, syscall.SIGTERM)
	for sig := range c {		
		fmt.Printf("Signal stop >> %s", sig.String())		
		os.Exit(1)
	}	
}
```

Expecting that if porgram started at 17:38, at 17:40 and 17;41 the message will appear. But nothing happens. What I am doing wrong?

**Comment by JohnRoesler** [comment]
Hi @KnBrBz, I tried your code snippet (updating to an appropriate UTC time to make it run soon) and it ran as expected for me. Could you give it another go - perhaps your times weren't lined up properly?

**Comment by KnBrBz** [comment]
It was timezone issue - substracting 2 hours fixed the problem. Thanks for help.
