### ISSUE TITLE
[FEATURE] - Ability to reschedule a task 

### ISSUE THREAD

**Issue by apremalal** [go-co-op/gocron#72]
### Is your feature request related to a problem? Please describe

I want to be able to change the scheduling time based on the settings received while executing a task

### Describe the solution you'd like

I tried adding a separate channel to capture a message on task frequency change and clearing the existing task and the adding a new one with the new frequency. However this causes race conditions.

**Comment by Streppel** [comment]
@apremalal thanks for the idea, that's a very interesting usecase indeed. Could you provide an example? Like, for a job running Every(3).Seconds(), then during runtime for whatever reason it should be changed to Every(5).Hours()?

**Comment by apremalal** [comment]
@Streppel exactly. Inside the task it receives the job frequency as a setting from an api, if the frequency is different from current running frequency, it has to change the scheduling of the current job.

**Comment by mjammer** [comment]
Sometimes, I need to remove a job by tag, and then add a new job,  `scheduler Next Run` this job. Otherwise, this job would be run quickly.

**Comment by JohnRoesler** [comment]
@apremalal hey! we've made quite a few changes to the library since you opened this issue. Now that jobs are scheduled using the timer after func, we have the remove job logic stop that timer which will stop any more jobs from being scheduled. Would this work to meet your need or are you still looking for a way to directly update the job's settings?

Example or removing a job, waiting a bit and scheduling a new one:

```
func main() {
	s := gocron.NewScheduler(time.UTC)
	j, err := s.Every("1s").Do(func() { log.Println("hello") })
	if err != nil {
		log.Fatalf("something bad happened: %v", err)
	}

	s.StartAsync()
	time.Sleep(2 * time.Second)

	s.RemoveByReference(j)

	time.Sleep(2 * time.Second)

	_, err = s.Every("3s").Do(func() { log.Println("hello") })
	if err != nil {
		log.Fatalf("something bad happened: %v", err)
	}
	time.Sleep(10 * time.Second)
}
```

I could see merit in being able to reschedule a job, and that's something we could look into further 👍

**Comment by JohnRoesler** [comment]
@apremalal @mjammer @Streppel  I've been thinking about the design of rescheduling and have some questions as well as my ideas to share:

- The way I am thinking this would work, is that we'd update the scheduler with a new method `UpdateJob(job *Job)`
- This method could then be called like so:

```go
func main() {
    s := gocron.NewScheduler(time.UTC)
    j, err := s.Every("1s").Do(func() {})
    time.Sleep(10 * time.Second)
    s.UpdateJob(j).Every("10m)
    time.Sleep(10 * time.Second)
    s.UpdateJob(j).Every(1).Day().At("02:00")
}
```

- I think then that this method would trigger the job to be stopped, and started as if it were running for the first time again, except that it would have a `lastRun` time to go off of. 

How does that sound? Does it address the desired behavior you'd like to see?

**Comment by Streppel** [comment]
@JohnRoesler I like this approach, looks very clean and intuitive to me!

**Comment by JohnRoesler** [comment]
hey all (@apremalal @mjammer @Streppel) - take a look at the PR #145 when you have a chance and test it out. The syntax is slightly different from my original idea, but I think it's still pretty clean.

**Comment by JohnRoesler** [comment]
This is out in release [v1.2.0](https://github.com/go-co-op/gocron/releases/tag/v1.2.0)
