### ISSUE TITLE
Data race

### ISSUE THREAD

**Issue by josvegit** [go-co-op/gocron#73]
There is a data race problem with this lib

![image](https://user-images.githubusercontent.com/24354568/98443943-00686600-210f-11eb-8f87-a773be9473aa.png)

**Comment by josvegit** [comment]
![image](https://user-images.githubusercontent.com/24354568/98522059-87831e80-2274-11eb-81fa-6ed099a2df6c.png)
![image](https://user-images.githubusercontent.com/24354568/98522100-91a51d00-2274-11eb-9850-2a8e66c11ca8.png)


Reproduce above

**Comment by JohnRoesler** [comment]
Thanks for reporting this! Hoping to get a chance to look into in the next few days.

**Comment by JohnRoesler** [comment]
That should be fixed on master now. Please confirm and I'll close this out 👍

**Comment by josvegit** [comment]
Works now ! no race issues ! WP

**Comment by farwydi** [comment]
💩

**Comment by JohnRoesler** [comment]
Resolved in [v0.3.3](https://github.com/go-co-op/gocron/releases/tag/v0.3.3)
