### ISSUE TITLE
[BUG] - OneTime (and potential future jobs) do not clear `NextRun` after last schedule is run

### ISSUE THREAD

**Issue by rbroggi** [go-co-op/gocron#742]
### Describe the bug

After all the schedules of a job are run I would expect the `NextRun` to return an empty `time.Time{}` instead of a time in the past. This would be consistent with how the `LastRun` method works (returns empty `time.Time{}` before all schedules are run).

### To Reproduce

I've created a unit test PR to show that.

### Version

v2.5.0

### Expected behavior

After all the schedules of a job are run I would expect the `NextRun` to return an empty `time.Time{}`

**Comment by JohnRoesler** [comment]
For the one time job, should be an easy fix, just zero out job.nextScheduled here -> https://github.com/go-co-op/gocron/blob/v2/scheduler.go#L321-L324

For cron, we'll need to do a little digging and see what is returned when you call next on an exhausted crontab schedule.

**Comment by rbroggi** [comment]
> ll need to do a little digging and see what is returned when you call next on an exhausted crontab schedule

I have accidentally found another way for doing that - see in the PR - just let me know which one you think is preferable and I will implement that

**Comment by JohnRoesler** [comment]
I like the way you did it! That seems like the more correct logic as the way I had it before it was always keeping 1 value in nextSchedule which would end up being in the past 👍

**Comment by JohnRoesler** [comment]
[v2.7.1](https://github.com/go-co-op/gocron/releases/tag/v2.7.1)
