### ISSUE TITLE
[FEATURE] - Provide more details of ErrPanicRecovered

### ISSUE THREAD

**Issue by Higan** [go-co-op/gocron#747]
### Is your feature request related to a problem? Please describe

When the task function panics, the `err` captured in `eventListeners` is `ErrPanicRecovered` with simple error message `gocron: panic recovered`, which is insufficient to figure out the root cause of panic. Given the code below, the actual desired message is `the actual cause of panic` instead of `gocron: panic recovered`.

```
package main

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron/v2"
)

func main() {) {
	// create a scheduler
	s, err := NewScheduler()
	if err != nil {
		// handle error
	}

	// add a job to the scheduler
	j, err := s.NewJob(
		DurationJob(
			1*time.Second,
		),
		NewTask(
			func() {
				panic("the actual cause of panic")
			},
		), WithEventListeners(
			AfterJobRunsWithError(
				func(jobID uuid.UUID, jobName string, err error) {
					fmt.Printf("Job %s failed with error: %s\n", jobName, err)
				},
			),
		),
	)
	if err != nil {
		// handle error
		fmt.Println(err)
	}
	// each job has a unique id
	fmt.Println(j.ID())

	// start the scheduler
	s.Start()

	select {
	case <-time.After(10 * time.Second):
	}

	// when you're done, shut it down
	err = s.Shutdown()
	if err != nil {
		// handle error
	}
}
```

### Describe the solution you'd like

In `executor`'s function `callJobWithRecover`, we could wrap `recoverData` within `err` and this makes it easier to find the root cause of panic.

**Comment by JohnRoesler** [comment]
Sounds like a good addition

**Comment by Higan** [comment]
Hi @JohnRoesler I've created a PR https://github.com/go-co-op/gocron/pull/749 regarding this issue.
