### ISSUE TITLE
[BUG] - Timing cycle trigger problem

### ISSUE THREAD

**Issue by zhangyuanxue** [go-co-op/gocron#750]
### Describe the bug
I set the code to execute every 30 minutes, but one of them was triggered again only ten minutes after the last time.

![image](https://github.com/go-co-op/gocron/assets/32893410/8044588a-7293-4df7-9bb5-0ff8c1fbfa16)

![image](https://github.com/go-co-op/gocron/assets/32893410/2cad6db9-a1e2-4a84-9e9f-72a1b8b4be98)

**Comment by Higan** [comment]
Hi @zhangyuanxue according to the project's [readme](https://github.com/go-co-op/gocron/blob/v1/README.md), v1 is no longer maintained. Could you try switching to v2?

**Comment by zhangyuanxue** [comment]
您发的邮件我已收到，我会马上查看的 ，谢谢。

**Comment by JohnRoesler** [comment]
Correct, v1 is not maintained, due to bugs such as this that I did not consider worth solving and instead designed v2 in ways that these issues do not occur.
