### ISSUE TITLE
[FEATURE] - Allow UUID to be set in the job

### ISSUE THREAD

**Issue by pcfreak30** [go-co-op/gocron#753]
I have https://github.com/LumeWeb/gocron/commit/6e1fcc64e8b6a5b4ae0025ac71f25a3e7b67a79b though im not sure if you require anything else.

would like to submit a PR so I don't need to keep a fork. Its a small detail but important for my use case.

Thanks.

@JohnRoesler

**Comment by JohnRoesler** [comment]
Sure, I'd accept a PR for that 👍

**Comment by JohnRoesler** [comment]
https://github.com/go-co-op/gocron/releases/tag/v2.9.0

**Comment by pcfreak30** [comment]
> https://github.com/go-co-op/gocron/releases/tag/v2.9.0

kudos! got this going downstream and removed use of the fork.
