### ISSUE TITLE
[BUG] - cannot handle variadic interface parameters

### ISSUE THREAD

**Issue by apocelipes** [go-co-op/gocron#756]
This code does not work:

```go
func main() {
	j, err := s.NewJob(
		gocron.DurationJob(
			10*time.Second,
		),
		gocron.NewTask(
			func(parameters ...any) {
				for i := range parameters {
					fmt.Println(parameters[i])
				}
			},
			1,
			"2",
		),
	)
	if err != nil {
		panic(err)
	}
}
```
It panicked like this: 
![image](https://github.com/user-attachments/assets/a4aa2c4c-ddb2-4f76-9380-afd449b12059)

This because the verifyVariadic only checks the first element's underlying type of `parameters ...any`, the first element's underlying type is `int` here and the second element's underlying type is `string`.

What I want: This code runs well without any panicking and keeps type-safe.

The correct behavior is that if the variadic parameter's type is interface, we only need to check if the actual parameters implement that interface.

I'd like to send a PR to fix this issue.

**Comment by JohnRoesler** [comment]
Thank you for reporting and fixing!
