### ISSUE TITLE
[FEATURE] - go version request

### ISSUE THREAD

**Issue by Xavierxhq** [go-co-op/gocron#769]
I have a project attached to go version=1.18, and it let me fail using this repo, is there anything can be done to let me use it? may be fork a new branch and specify the go version=1.18 if it works?

**Comment by Xavierxhq** [comment]
I have forked the repo and edit it in that one, and it worked.

**Comment by jary-287** [comment]
same issue,  how can I do for using it.

@Xavierxhq

**Comment by Xavierxhq** [comment]
Hi there, i am Xavier, if u r seeing this, it means that i have received your letter and i will try to reply sooner. Ur respectfully.

**Comment by Xavierxhq** [comment]
@jary-287 I just fork one repo for myself, revise the go version to 1.18 and use it in my project. u may try as well~
