### ISSUE TITLE
[FEATURE] - Add JobStatus to RecordJobTiming in Monitor Interface

### ISSUE THREAD

**Issue by FalcoSuessgott** [go-co-op/gocron#775]
Morning fellas, really loving working with `gocron`, it allows me to quickly schedule repeating tasks! :) 

Im currently building a Prometheus Exporter and using the `Monitor` interface to measure task durations and add the results to a Prometheus Histogram. I would love to be able to also add whether a task was successful or not as a label to the metric.

I was wondering whether its possible to add the `JobStatus` to the `RecordJobTiming` function, similar as `IncrementJob` already has it in the `Monitor` interface.

I believe, we could pass the JobStatus, based on the error result when running `e.callJobWithRecover(j)` in:  
https://github.com/go-co-op/gocron/blob/c84d8f70c4038b86776433651a307c831e3daa78/executor.go#L399-L408

Im aware, that this is probably a breaking change, but just wanted to get your thoughts on that one.

**Comment by JohnRoesler** [comment]
@FalcoSuessgott I was thinking you could add another method to the interface `RecordJobTimingWithStatus`, but that's breaking as well. I'm good with adding it, just trying to think through the best way to roll it out as far as releases
