### ISSUE TITLE
question

### ISSUE THREAD

**Issue by wanghuashun** [go-co-op/gocron#78]
how to check all jobs

**Comment by Streppel** [comment]
@wanghuashun Hello! What do you mean by "check all jobs"? Can you be a little more specific?

**Comment by wanghuashun** [comment]
View all scheduled tasks list







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "go-co-op/gocron"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月16日(星期一) 中午11:23
收件人:&nbsp;"go-co-op/gocron"<gocron@noreply.github.com&gt;;
抄送:&nbsp;"李香兰"<957004161@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [go-co-op/gocron] question (#78)





 
@wanghuashun Hello! What do you mean by "check all jobs"? Can you be a little more specific?

**Comment by Streppel** [comment]
You can do that by calling the .Jobs method on the scheduler

**Comment by wanghuashun** [comment]
OK, I'll try first


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "go-co-op/gocron"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月16日(星期一) 中午11:28
收件人:&nbsp;"go-co-op/gocron"<gocron@noreply.github.com&gt;;
抄送:&nbsp;"李香兰"<957004161@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [go-co-op/gocron] question (#78)





 
You can do that by calling the .Jobs method on the scheduler

**Comment by wanghuashun** [comment]
s1 := gocron.NewScheduler(time.UTC)
	//_, _ = app.Name.Every(5).Seconds().Do(task)
	s1.Every(1).Day().At("14:08:00").Do(task)
	// scheduler starts running jobs and current thread continues to execute
	s1.StartAsync()

**Comment by wanghuashun** [comment]
It was not implemented at the specific time

**Comment by Streppel** [comment]
Is UTC your local time zone?

**Comment by wanghuashun** [comment]
It should be




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "go-co-op/gocron"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月16日(星期一) 下午2:16
收件人:&nbsp;"go-co-op/gocron"<gocron@noreply.github.com&gt;;
抄送:&nbsp;"李香兰"<957004161@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [go-co-op/gocron] question (#78)





 
Is UTC your local time zone?

**Comment by Streppel** [comment]
Closing this due to lack of information. If desired, repoen the issue with the current code, what was expected and what was gotten instead.
