### ISSUE TITLE
[BUG] - you have a lot of goroutine leaks

### ISSUE THREAD

**Issue by zV3KT0R** [go-co-op/gocron#802]
For example:
https://github.com/go-co-op/gocron/blob/d856be5a410cf8306e8f8aa599e572d43d6e9788/scheduler.go#L747

**Comment by JohnRoesler** [comment]
Consider proposing a fix

**Comment by jhowrez** [comment]
This might be relevant for this issue specifically:  https://go.dev/wiki/Go123Timer 

.Edit typo

**Comment by JohnRoesler** [comment]
@zV3KT0R in the future, I'd appreciate it if you could open a ticket with:
- more details, including what you'd like to see fixed, anything you've tried, etc.
  - The `[BUG]` issue template has quite a few fields that I note are not present or populated.
- a more helpful and polite title

Cheers

**Comment by zV3KT0R** [comment]
Yes, I agree.
