### ISSUE TITLE
[FEATURE] - Persist schedule between runs

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [go-co-op/gocron#96]
Hi,

Do I understand correctly that when the process stops, all scheduled jobs are lost?

I would like to save the jobs to disk, so they can be reloaded and scheduled again when my app is started.

I need to do this anyway, but I was wondering whether it makes sense that I create a pull request, so it can be added to the package?

Jo

**Comment by JohnRoesler** [comment]
Hi,

we had a similar request here https://github.com/go-co-op/gocron/issues/22 and we decided not to add it to the package. Let know if that makes sense for what you are trying to do.

**Comment by PolyglotOpenstreetmap** [comment]
I forked the repo a few hours ago. If I figure out something that works, I'll create a PR, so you can evaluate what I did. It may not fit after all, so you can always reject it.

**Comment by PolyglotOpenstreetmap** [comment]
I'm sorry. I have been overthinking this. I have to persist the jobs on my side. Looking at your code has taught me a few things, so it was worth it.

Thanks for your work!

Jo

**Comment by JohnRoesler** [comment]
You’re very welcome! We’re always on Slack if you’d like to discuss anything more real time 😊
